'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Card, SectionHeader } from '../../../../components/ui';
import { createBrowserSupabaseClient } from '../../../../lib/supabase';
import { getPublishedDashboard, previewDashboard, type Dashboard, type Widget } from '../../../../lib/dashboards-api';

type PreviewResult = { status?: string; value?: unknown; display_value?: string | null; table?: Record<string, unknown>[]; series?: Record<string, unknown>[]; message?: string };
function rows(result?: PreviewResult) { return (result?.table?.length ? result.table : result?.series) ?? []; }
function WidgetRender({ widget, result }: { widget: Widget; result?: PreviewResult }) { const data = rows(result); if (!result) return <div className="mt-4 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Carregando dados...</div>; if (!data.length && result.value === null) return <div className="mt-4 rounded-xl bg-amber-50 p-5 text-sm text-amber-700">{result.message ?? 'Dados insuficientes.'}</div>; if (widget.visual_type === 'kpi') return <div className="mt-5 text-4xl font-black text-blue-600">{result.display_value ?? String(result.value ?? data.length)}</div>; if (widget.visual_type === 'bar' || widget.visual_type === 'line') return <div className="mt-4 flex h-32 items-end gap-1 rounded-xl bg-slate-50 p-3">{data.slice(0, 16).map((row, index) => { const value = Number(Object.values(row).at(-1) ?? 0); return <div key={index} className="flex-1 rounded-t bg-blue-500" style={{ height: `${Math.max(8, Math.min(100, Number.isFinite(value) ? Math.abs(value) : 8))}%` }} />; })}</div>; if (widget.visual_type === 'pie') return <ul className="mt-4 space-y-2 text-sm">{data.slice(0, 6).map((row, index) => <li key={index} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2"><span>{String(Object.values(row)[0] ?? `Fatia ${index + 1}`)}</span><b>{String(Object.values(row).at(-1) ?? '-')}</b></li>)}</ul>; return <div className="mt-4 overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{Object.keys(data[0] ?? {}).map((key) => <th key={key} className="border-b p-2">{key}</th>)}</tr></thead><tbody>{data.slice(0, 8).map((row, index) => <tr key={index}>{Object.values(row).map((value, cell) => <td key={cell} className="border-b p-2">{String(value ?? '-')}</td>)}</tr>)}</tbody></table></div>; }

export default function PublishedDashboard() {
  const { id } = useParams<{ id: string }>();
  const [dash, setDash] = useState<Dashboard>();
  const [previews, setPreviews] = useState<Record<string, PreviewResult>>({});
  const [message, setMessage] = useState('');
  useEffect(() => { createBrowserSupabaseClient().from('users_profile').select('active_tenant_id').maybeSingle().then(async ({ data }) => { const tenant = (data as { active_tenant_id?: string } | null)?.active_tenant_id ?? ''; if (!tenant) return; try { const version = await getPublishedDashboard(tenant, id); setDash(version.snapshot); const filters = ((version.snapshot.layout_config as { global_filters?: Record<string, unknown>[] } | undefined)?.global_filters) ?? []; const response = await previewDashboard(tenant, id, filters, true); setPreviews(Object.fromEntries(response.data.map((item) => [item.widget_id, item.result as PreviewResult]))); } catch { setMessage('Dashboard ainda não publicado.'); } }); }, [id]);
  return <div className="space-y-5"><SectionHeader eyebrow="Dashboards" title={dash?.title ?? 'Dashboard publicado'} description="Visualização publicada com snapshot de configuração e preview dinâmico controlado pelo backend." />{message && <Card>{message}</Card>}<div className="grid grid-cols-12 gap-4 rounded-3xl border bg-white/60 p-4">{[...(dash?.widgets ?? [])].sort((a, b) => (a.position.y ?? 0) - (b.position.y ?? 0) || (a.position.x ?? 0) - (b.position.x ?? 0)).map((w) => <Card key={w.id} className="col-span-12 md:col-span-6 xl:col-span-4" style={{ minHeight: `${Math.max(1, w.position.h || 2) * 96}px` }}><h2 className="font-bold">{w.title}</h2><p className="text-xs uppercase text-slate-500">{w.visual_type}</p><WidgetRender widget={w} result={previews[w.id]} /></Card>)}</div></div>;
}
