import type { ReactNode } from 'react';

export type WidgetVisualType = 'kpi' | 'table' | 'matrix' | 'bar' | 'pie' | 'line';
type Row = Record<string, unknown>;
const colors = ['#2563eb', '#06b6d4', '#8b5cf6', '#10b981', '#f59e0b', '#f43f5e'];
const hidden = /(^|_)(id|tenant_id|indicator_id|source|used_count|records_used|count_used)$/i;
const object = (v: unknown): v is Row => !!v && typeof v === 'object' && !Array.isArray(v);
const value = (v: unknown, label = '') => { if (v === null || v === undefined || v === '') return '—'; const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN; if (!Number.isFinite(n)) return String(v); if (/percent|taxa|%/i.test(label)) return new Intl.NumberFormat('pt-BR', { style: 'percent', maximumFractionDigits: 2 }).format(Math.abs(n) <= 1 ? n : n / 100); return new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(n); };
function rowsFrom(data: unknown): Row[] { const d = object(data) ? data : {}; const nested = object(d.data) ? d.data : {}; for (const candidate of [d.rows, nested.rows, d.records, object(d.table) ? d.table.rows : undefined, d.series, nested.data, Array.isArray(data) ? data : undefined]) if (Array.isArray(candidate)) return candidate.filter(object); return []; }
function points(data: unknown) { return rowsFrom(data).slice(0, 10).map((row, i) => { const vals = Object.values(row); const raw = row.value ?? row.count ?? row.total ?? row.records ?? vals.find((x) => typeof x === 'number' || (typeof x === 'string' && x.trim() !== '' && Number.isFinite(Number(x)))); return { label: String(row.label ?? row.name ?? row.category ?? row.period ?? vals[0] ?? `Item ${i + 1}`), number: Number(raw) }; }).filter((p) => Number.isFinite(p.number)); }
function Empty({ children }: { children: ReactNode }) { return <p className="mt-4 rounded-xl border border-amber-100 bg-amber-50 px-4 py-4 text-sm text-amber-800">{children}</p>; }
function Table({ data }: { data: unknown }) { const rows = rowsFrom(data); const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))].filter((key) => !hidden.test(key)).slice(0, 8); if (!rows.length || !columns.length) return <Empty>Dados insuficientes para esta visualização.</Empty>; return <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-500"><tr>{columns.map((c) => <th className="px-3 py-3" key={c}>{c.replace(/_/g, ' ')}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.slice(0, 10).map((row, i) => <tr key={i}>{columns.map((c) => <td className="whitespace-nowrap px-3 py-3 text-slate-700" key={c}>{value(row[c], c)}</td>)}</tr>)}</tbody></table></div>; }
function Kpi({ data, title }: { data: unknown; title: string }) { const d = object(data) ? data : {}; const nested = object(d.data) ? d.data : {}; const result = object(d.result) ? d.result : {}; const raw = [d.value, nested.value, result.value, d.total, d.count].find((x) => typeof x === 'number' || typeof x === 'string') ?? Object.values(d).find((x) => typeof x === 'number'); if (raw === undefined) return <Empty>Dados insuficientes para este indicador.</Empty>; return <div className="mt-5"><p className="text-4xl font-black tracking-tight text-slate-950">{value(raw, title)}</p>{typeof d.subtitle === 'string' && <p className="mt-2 text-sm text-slate-500">{d.subtitle}</p>}{d.variation !== undefined && <p className="mt-2 text-sm font-semibold text-emerald-700">Variação: {value(d.variation, 'percentual')}</p>}</div>; }
function Bar({ data }: { data: unknown }) { const ps = points(data); if (!ps.length) return <Empty>Dados insuficientes para o gráfico de barras.</Empty>; const max = Math.max(...ps.map((p) => Math.abs(p.number)), 1); return <div className="mt-5 space-y-3">{ps.map((p, i) => <div key={`${p.label}-${i}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-medium text-slate-700">{p.label}</span><strong>{value(p.number)}</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(3, Math.abs(p.number) / max * 100)}%` }} /></div></div>)}</div>; }
function Pie({ data }: { data: unknown }) { const ps = points(data); if (!ps.length) return <Empty>Dados insuficientes para o gráfico de pizza.</Empty>; const total = ps.reduce((sum, p) => sum + Math.max(p.number, 0), 0) || 1; let offset = 0; return <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-center"><svg viewBox="0 0 42 42" className="h-36 w-36 shrink-0 -rotate-90"><circle cx="21" cy="21" r="15.915" fill="transparent" stroke="#e2e8f0" strokeWidth="7" />{ps.map((p, i) => { const dash = Math.max(p.number, 0) / total * 100; const el = <circle key={i} cx="21" cy="21" r="15.915" fill="transparent" stroke={colors[i % colors.length]} strokeWidth="7" strokeDasharray={`${dash} ${100 - dash}`} strokeDashoffset={-offset} />; offset += dash; return el; })}</svg><div className="min-w-0 flex-1 space-y-2">{ps.map((p, i) => <div className="flex items-center gap-2 text-sm" key={`${p.label}-${i}`}><i className="h-2.5 w-2.5 rounded-full" style={{ background: colors[i % colors.length] }} /><span className="min-w-0 flex-1 truncate">{p.label}</span><strong>{value(p.number)} · {(p.number / total * 100).toFixed(1)}%</strong></div>)}</div></div>; }
function Line({ data }: { data: unknown }) { const ps = points(data); if (ps.length < 2) return ps.length ? <Bar data={data} /> : <Empty>Dados insuficientes para o gráfico de linha.</Empty>; const max = Math.max(...ps.map((p) => p.number)), min = Math.min(...ps.map((p) => p.number)), range = max - min || 1; const coords = ps.map((p, i) => `${i / (ps.length - 1) * 100},${88 - (p.number - min) / range * 72}`).join(' '); return <div className="mt-5"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-40 w-full rounded-xl border border-slate-100 bg-slate-50 p-3"><path d="M0 88H100" stroke="#cbd5e1" strokeWidth="1" /><polyline points={coords} fill="none" stroke="#2563eb" strokeWidth="3" vectorEffect="non-scaling-stroke" />{ps.map((p, i) => <circle key={i} cx={i / (ps.length - 1) * 100} cy={88 - (p.number - min) / range * 72} r="2" fill="#2563eb" />)}</svg><div className="mt-2 flex justify-between gap-2 text-xs text-slate-500">{ps.map((p, i) => <span className="truncate" key={i}>{p.label}</span>)}</div></div>; }
export function WidgetRenderer({ visualType, data, title, message }: { visualType: WidgetVisualType; data: unknown; title: string; message?: string }) { if (message) return <Empty>{message}</Empty>; if (!data) return <Empty>Aguardando dados suficientes para exibir este indicador.</Empty>; if (object(data) && ['empty', 'waiting_data'].includes(String(data.status))) return <Empty>{String(data.message ?? 'Aguardando dados suficientes para exibir este indicador.')}</Empty>; switch (visualType) { case 'kpi': return <Kpi data={data} title={title} />; case 'bar': return <Bar data={data} />; case 'pie': return <Pie data={data} />; case 'line': return <Line data={data} />; case 'matrix': case 'table': return <Table data={data} />; } }
