'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react';
import { createBrowserSupabaseClient } from '../../../../lib/supabase';
import { knowledgeCreate, knowledgeList, knowledgeUpdate } from '../../../../lib/knowledge-api';

export default function Knowledge(){
 const[t,setT]=useState(''),[docs,setDocs]=useState<any[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false),[updating,setUpdating]=useState<string|null>(null);
 const load=async(tenant:string)=>setDocs(await knowledgeList(tenant));
 useEffect(()=>{void createBrowserSupabaseClient().from('users_profile').select('active_tenant_id').maybeSingle().then(async({data}:any)=>{if(data?.active_tenant_id){setT(data.active_tenant_id);try{await load(data.active_tenant_id)}catch{setError('Não foi possível carregar os documentos agora.')}}});},[]);
 const create=async()=>{if(creating||!t)return;setCreating(true);setError('');setNotice('');try{await knowledgeCreate(t,{title,content,document_type:'manual'});setTitle('');setContent('');await load(t);setNotice('Documento criado como rascunho. Publique para que o Agente Geral consiga consultar.');}catch(e:any){setError(e?.message||'Não foi possível criar o documento. Confira os dados e tente novamente.');}finally{setCreating(false)}};
 const changeStatus=async(doc:any)=>{if(updating||!t)return;const publishing=doc.status!=='published';setUpdating(doc.id);setError('');setNotice('');try{await knowledgeUpdate(t,doc.id,{status:publishing?'published':'archived'});await load(t);setNotice(publishing?'Documento publicado. O Agente Geral já pode consultá-lo.':'Documento arquivado. Ele não será mais consultado pelo Agente Geral.');}catch(e:any){setError(e?.message||'Não foi possível atualizar o documento. Tente novamente.');}finally{setUpdating(null)}};
 return <section className="mx-auto max-w-4xl space-y-5"><h1 className="text-2xl font-bold">Base de conhecimento</h1><p className="text-slate-600">Upload de arquivos será implementado em etapa posterior. Nesta versão, cadastre conteúdos textuais.</p>{error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded border border-emerald-200 bg-emerald-50 p-3 text-emerald-800">{notice}</p>}<div className="space-y-2 rounded border bg-white p-4"><input className="w-full rounded border p-2" placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)} disabled={creating}/><textarea className="min-h-40 w-full rounded border p-2" placeholder="Conteúdo" value={content} onChange={e=>setContent(e.target.value)} disabled={creating}/><button className="btn-primary disabled:cursor-not-allowed disabled:opacity-60" onClick={()=>void create()} disabled={creating||!title.trim()||!content.trim()}>{creating?'Criando...':'Criar documento'}</button></div><div className="space-y-2">{docs.map(d=>{const working=updating===d.id;const published=d.status==='published';return <article className="flex items-center justify-between rounded border bg-white p-4" key={d.id}><div><b>{d.title}</b><p className="mt-1 text-sm text-slate-500"><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${published?'bg-emerald-100 text-emerald-800':d.status==='draft'?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-700'}`}>{d.status}</span> <span className="ml-1">· {d.document_type}</span></p>{d.status==='draft'&&<p className="mt-2 text-xs text-amber-800">Rascunho: publique para permitir consulta no Agente Geral.</p>}</div><div className="flex gap-2"><button onClick={()=>void changeStatus(d)} disabled={Boolean(updating)} className="rounded border px-2 py-1 text-sm disabled:cursor-not-allowed disabled:opacity-60">{working?(published?'Arquivando...':'Publicando...'):(published?'Arquivar':'Publicar')}</button></div></article>})}</div></section>;
}
