import { createBrowserSupabaseClient } from './supabase';

const dataSourceEmbed = 'data_source:data_sources!data_contracts_data_source_tenant_fk(name)';
const dataContractSelect = `id,tenant_id,data_source_id,name,description,module_key,entity_key,contract_version,format,direction,status,periodicity,${dataSourceEmbed}`;

export type DataSource = { id:string; tenant_id:string; name:string; description:string|null; source_type:string; module_key:string; status:string; owner_user_id:string|null };
export type DataContract = { id:string; tenant_id:string; data_source_id:string; name:string; description:string|null; module_key:string; entity_key:string; contract_version:number; format:string; direction:string; status:string; periodicity:string|null; data_source?:{name:string}|null };
export type DataContractField = { id:string; tenant_id:string; data_contract_id:string; field_key:string; source_field_name:string; description:string|null; data_type:string; is_required:boolean; is_unique:boolean; allow_null:boolean; min_length:number|null; max_length:number|null; min_value:number|null; max_value:number|null; regex_pattern:string|null; date_format:string|null; sort_order:number };
export type AllowedValue = { id:string; tenant_id:string; data_contract_id:string; data_contract_field_id:string; value:string; label:string|null; normalized_value:string|null; is_active:boolean; sort_order:number };
export async function listDataSources(tenantId:string){const {data,error}=await createBrowserSupabaseClient().from('data_sources').select('id,tenant_id,name,description,source_type,module_key,status,owner_user_id').eq('tenant_id',tenantId).order('name'); if(error) throw error; return data as DataSource[];}
export async function createDataSource(tenantId:string,p:Partial<DataSource>){const {error}=await createBrowserSupabaseClient().from('data_sources').insert({...p,tenant_id:tenantId}); if(error) throw error;}
export async function listDataContracts(tenantId:string){const {data,error}=await createBrowserSupabaseClient().from('data_contracts').select(dataContractSelect).eq('tenant_id',tenantId).order('created_at',{ascending:false}); if(error) throw error; return data as DataContract[];}
export async function getDataContract(tenantId:string,id:string){const {data,error}=await createBrowserSupabaseClient().from('data_contracts').select(dataContractSelect).eq('tenant_id',tenantId).eq('id',id).maybeSingle(); if(error) throw error; return data as DataContract|null;}
export async function createDataContract(tenantId:string,p:Partial<DataContract>){const {error}=await createBrowserSupabaseClient().from('data_contracts').insert({...p,tenant_id:tenantId}); if(error) throw error;}
export async function updateDataContract(tenantId:string,id:string,p:Partial<DataContract>){const {error}=await createBrowserSupabaseClient().from('data_contracts').update(p).eq('tenant_id',tenantId).eq('id',id); if(error) throw error;}
export async function listContractFields(tenantId:string,contractId:string){const {data,error}=await createBrowserSupabaseClient().from('data_contract_fields').select('*').eq('tenant_id',tenantId).eq('data_contract_id',contractId).order('sort_order'); if(error) throw error; return data as DataContractField[];}
export async function createContractField(tenantId:string,contractId:string,p:Partial<DataContractField>){const {error}=await createBrowserSupabaseClient().from('data_contract_fields').insert({...p,tenant_id:tenantId,data_contract_id:contractId}); if(error) throw error;}
export async function updateContractField(tenantId:string,id:string,p:Partial<DataContractField>){const {error}=await createBrowserSupabaseClient().from('data_contract_fields').update(p).eq('tenant_id',tenantId).eq('id',id); if(error) throw error;}
export async function listAllowedValues(tenantId:string,fieldId:string){const {data,error}=await createBrowserSupabaseClient().from('data_contract_allowed_values').select('*').eq('tenant_id',tenantId).eq('data_contract_field_id',fieldId).order('sort_order'); if(error) throw error; return data as AllowedValue[];}
export async function createAllowedValue(tenantId:string,contractId:string,fieldId:string,value:string){const {error}=await createBrowserSupabaseClient().from('data_contract_allowed_values').insert({tenant_id:tenantId,data_contract_id:contractId,data_contract_field_id:fieldId,value,label:value,normalized_value:value}); if(error) throw error;}
