const labels: Record<string, string> = {
  transport:'Transporte', transporte:'Transporte', finance:'Financeiro', financeiro:'Financeiro', attendance:'Atendimento', atendimento:'Atendimento', warehouse:'Armazém', armazem:'Armazém', team:'Equipes', equipes:'Equipes', core:'Core',
  draft:'Rascunho', active:'Ativo', archived:'Arquivado', published:'Publicado', completed:'Concluído', failed:'Falhou', pending:'Pendente', processing:'Processando', manual:'Manual', scheduled:'Agendado', daily:'Diária', weekly:'Semanal', monthly:'Mensal',
  kpi:'KPI', table:'Tabela', matrix:'Matriz', bar:'Barra', pie:'Pizza', line:'Linha', native_indicator:'Indicador nativo', custom_indicator:'Indicador personalizado', native:'Nativo', custom:'Personalizado', date_range:'Período', multi_select:'Seleção múltipla',
  issued_at:'Data de emissão', expected_date:'Data prevista', completed_at:'Data de entrega', updated_at:'Data de atualização', customer_name:'Cliente', shipper_name:'Embarcador', recipient_name:'Destinatário', origin_city:'Cidade origem', origin_state:'UF origem', destination_city:'Cidade destino', destination_state:'UF destino', status:'Status', document_type:'Tipo de documento', driver_name:'Motorista', driver_phone:'Telefone do motorista', driver_whatsapp:'WhatsApp do motorista', vehicle_plate:'Veículo', vehicle_type:'Tipo de veículo', carrier_name:'Transportadora', cargo_type:'Tipo de carga', priority:'Prioridade', delivery_status:'Status da entrega', occurrence_status:'Status da ocorrência', pod_status:'Status do canhoto', billing_status:'Status de faturamento', billing_block_status:'Bloqueio financeiro', payment_status:'Status de pagamento',
  occurrences:'Ocorrências', occurrence_analytics_view:'Ocorrências', occurrence_number:'Número da ocorrência', current_status:'Status', current_priority:'Prioridade', source_channel:'Canal de origem', opened_at:'Data de abertura', due_at:'Prazo', resolved_at:'Data de resolução', closed_at:'Data de fechamento', sla_status:'SLA', reason_code:'Código do motivo', reason_name:'Motivo', reason_category:'Categoria do motivo', responsible_team:'Equipe responsável', linked_document_number:'Documento vinculado', linked_invoice_number:'NF vinculada', linked_cte_number:'CT-e vinculado', linked_delivery_number:'Entrega vinculada', has_operation_link:'Possui vínculo operacional', has_pending_actions:'Possui pendências', pending_actions_count:'Pendências', overdue_pending_actions_count:'Pendências vencidas', treatments_count:'Tratativas', open_treatments_count:'Tratativas abertas', financial_entries_total:'Total financeiro', documents_count:'Documentos', attachments_count:'Anexos', resolution_minutes:'Tempo de resolução (minutos)',
};
export const displayLabel = (key: string) => labels[key] ?? key.replace(/_/g, ' ');
export const reportFilterLabel = (key: string) => labels[key] ?? 'Filtro do relatório';
export const reportFrequencyLabel = (frequency: string) => displayLabel(frequency);
