import { createBrowserSupabaseClient } from './supabase';

export type StagingBatch = { id:string; tenant_id:string; data_source_id:string; data_contract_id:string; batch_code:string|null; source_reference:string|null; status:string; total_records:number; valid_records:number; invalid_records:number; error_count:number; metadata:Record<string,unknown>; received_at:string|null; validated_at:string|null; created_at:string; data_source?:{name:string}|null; data_contract?:{name:string}|null };
export type StagingRecord = { id:string; tenant_id:string; staging_batch_id:string; data_contract_id:string; row_number:number; raw_payload:Record<string,unknown>; normalized_payload:Record<string,unknown>; validation_status:string; error_count:number; validated_at:string|null; created_at:string };
export type StagingError = { id:string; tenant_id:string; staging_batch_id:string; staging_record_id:string|null; error_code:string; severity:string; field_key:string|null; source_field_name:string|null; raw_value:string|null; expected_rule:string|null; message:string; created_at:string };
const batchSelect = 'id,tenant_id,data_source_id,data_contract_id,batch_code,source_reference,status,total_records,valid_records,invalid_records,error_count,metadata,received_at,validated_at,created_at,data_source:data_sources!staging_batches_data_source_tenant_fk(name),data_contract:data_contracts!staging_batches_data_contract_tenant_fk(name)';
export async function listStagingBatches(tenantId:string){const {data,error}=await createBrowserSupabaseClient().from('staging_batches').select(batchSelect).eq('tenant_id',tenantId).order('created_at',{ascending:false}); if(error) throw error; return data as StagingBatch[];}
export async function getStagingBatch(tenantId:string,id:string){const {data,error}=await createBrowserSupabaseClient().from('staging_batches').select(batchSelect).eq('tenant_id',tenantId).eq('id',id).maybeSingle(); if(error) throw error; return data as StagingBatch|null;}
export async function createStagingBatch(tenantId:string,p:{data_source_id:string;data_contract_id:string;batch_code?:string;source_reference?:string}){const {data,error}=await createBrowserSupabaseClient().from('staging_batches').insert({...p,tenant_id:tenantId,status:'draft'}); if(error) throw error; return (data as StagingBatch[])[0];}
export async function updateStagingBatchReceived(tenantId:string,id:string,total:number){const {error}=await createBrowserSupabaseClient().from('staging_batches').update({total_records:total,status:'received',received_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id); if(error) throw error;}
export async function createStagingRecords(tenantId:string,batch:StagingBatch,records:Record<string,unknown>[]){const payload=records.map((raw_payload,i)=>({tenant_id:tenantId,staging_batch_id:batch.id,data_contract_id:batch.data_contract_id,row_number:i+1,raw_payload})); const {error}=await createBrowserSupabaseClient().from('staging_records').insert(payload); if(error) throw error; await updateStagingBatchReceived(tenantId,batch.id,records.length);}
export async function listStagingRecords(tenantId:string,batchId:string){const {data,error}=await createBrowserSupabaseClient().from('staging_records').select('*').eq('tenant_id',tenantId).eq('staging_batch_id',batchId).order('row_number'); if(error) throw error; return data as StagingRecord[];}
export async function listStagingErrors(tenantId:string,batchId:string){const {data,error}=await createBrowserSupabaseClient().from('staging_errors').select('*').eq('tenant_id',tenantId).eq('staging_batch_id',batchId).order('created_at'); if(error) throw error; return data as StagingError[];}
export async function validateStagingBatch(batchId:string){const {data,error}=await createBrowserSupabaseClient().rpc('validate_staging_batch',{p_batch_id:batchId}); if(error) throw error; return data;}
