'use client';
import { FormEvent, useEffect, useState } from 'react';
import { MessageCircle, RefreshCw, Send, X } from 'lucide-react';
import { useParams } from 'next/navigation';

type Message={id:string;direction:'inbound'|'outbound';sender_type:string;body:string|null;created_at:string};
const apiBase=()=>process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,'')??'http://localhost:3001';

export default function PublicAttendancePage(){
 const {tenantSlug}=useParams<{tenantSlug:string}>(),[open,setOpen]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[initial,setInitial]=useState(''),[draft,setDraft]=useState(''),[messages,setMessages]=useState<Message[]>([]),[sessionId,setSessionId]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const storageKey=`sli_public_chat_${tenantSlug}`;
 const request=async(path:string,init?:RequestInit)=>{const response=await fetch(`${apiBase()}${path}`,{...init,headers:{'Content-Type':'application/json',...init?.headers}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message??'Não foi possível concluir o atendimento.');return data;};
 const refresh=async(id=sessionId,key=token)=>{if(!id||!key)return;setBusy(true);try{const data=await request(`/public/${encodeURIComponent(tenantSlug)}/chat/session/${encodeURIComponent(id)}?token=${encodeURIComponent(key)}`);setMessages(data.messages);setOpen(true);setNotice('');}catch(e){localStorage.removeItem(storageKey);setSessionId('');setToken('');setMessages([]);setNotice(e instanceof Error?e.message:'A sessão expirou. Inicie um novo atendimento.');}finally{setBusy(false)}};
 useEffect(()=>{const raw=localStorage.getItem(storageKey);if(!raw)return;try{const saved=JSON.parse(raw);if(saved.tenantSlug===tenantSlug){setSessionId(saved.session_id);setToken(saved.session_token);void refresh(saved.session_id,saved.session_token);}}catch{localStorage.removeItem(storageKey);}
 },[tenantSlug]);
 const start=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setNotice('');try{const data=await request(`/public/${encodeURIComponent(tenantSlug)}/chat/start`,{method:'POST',body:JSON.stringify({name,phone,message:initial})});setSessionId(data.session_id);setToken(data.session_token);setMessages(data.messages);localStorage.setItem(storageKey,JSON.stringify({session_id:data.session_id,session_token:data.session_token,tenantSlug}));}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível iniciar.');}finally{setBusy(false)}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!draft.trim())return;setBusy(true);try{const data=await request(`/public/${encodeURIComponent(tenantSlug)}/chat/messages`,{method:'POST',body:JSON.stringify({session_id:sessionId,session_token:token,message:draft})});setMessages(data.messages);setDraft('');}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível enviar.');}finally{setBusy(false)}};
 const reset=()=>{localStorage.removeItem(storageKey);setSessionId('');setToken('');setMessages([]);setNotice('');};
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 px-6 py-16 text-slate-900"><div className="mx-auto max-w-4xl"><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-medium text-blue-700">Canal seguro</span><h1 className="mt-5 text-4xl font-bold tracking-tight">Atendimento operacional</h1><p className="mt-3 max-w-xl text-lg text-slate-600">Clique no chat para registrar uma situação da entrega.</p></div>
 {open&&<section aria-label="Chat de atendimento" className="fixed bottom-24 right-5 z-20 flex h-[min(640px,calc(100vh-8rem))] w-[min(400px,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between bg-blue-700 px-5 py-4 text-white"><div><h2 className="font-semibold">Atendimento operacional</h2><p className="text-xs text-blue-100">Sua mensagem será registrada no Inbox.</p></div><button aria-label="Fechar chat" onClick={()=>setOpen(false)}><X/></button></header>
 {!sessionId?<form onSubmit={start} className="flex flex-1 flex-col gap-4 overflow-auto p-5"><label className="text-sm font-medium">Nome<input required maxLength={150} value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label><label className="text-sm font-medium">Telefone<input required maxLength={30} inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label><label className="text-sm font-medium">Mensagem inicial<textarea required maxLength={10000} rows={5} value={initial} onChange={e=>setInitial(e.target.value)} className="mt-1 w-full resize-none rounded-lg border p-3 font-normal"/></label>{notice&&<p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{notice}</p>}<button disabled={busy} className="mt-auto rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy?'Iniciando…':'Iniciar atendimento'}</button></form>:<><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{messages.map(m=><div key={m.id} className={`flex ${m.direction==='inbound'?'justify-end':'justify-start'}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm shadow-sm ${m.direction==='inbound'?'rounded-br-sm bg-blue-700 text-white':'rounded-bl-sm border bg-white text-slate-800'}`}>{m.body}</div></div>)}{notice&&<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{notice} <button className="underline" onClick={reset}>Iniciar novo atendimento</button></div>}</div><form onSubmit={send} className="border-t bg-white p-3"><div className="flex gap-2"><input aria-label="Digite sua mensagem" placeholder="Digite sua mensagem" maxLength={10000} value={draft} onChange={e=>setDraft(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-3"/><button aria-label="Enviar" disabled={busy} className="rounded-lg bg-blue-700 p-3 text-white"><Send size={18}/></button></div><button type="button" disabled={busy} onClick={()=>void refresh()} className="mt-3 flex items-center gap-2 text-xs font-medium text-blue-700"><RefreshCw size={14}/>Atualizar conversa</button></form></>}</section>}
 <button aria-label="Abrir chat" onClick={()=>setOpen(v=>!v)} className="fixed bottom-6 right-6 z-30 grid h-14 w-14 place-items-center rounded-full bg-blue-700 text-white shadow-lg transition hover:scale-105"><MessageCircle/></button></main>;
}
