import { BadRequestException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { SupabaseService } from '../supabase/supabase.service';
import { AttendanceAgentService } from '../agents/attendance-agent.service';

@Injectable()
export class PublicChatService {
 constructor(private readonly db:SupabaseService,private readonly attendance:AttendanceAgentService){}
 private text(v:unknown,n:string,max:number){if(typeof v!=='string'||!v.trim()||v.length>max)throw new BadRequestException(`${n} inválido.`);return v.trim();}
 private normalizePhone(v:unknown){const p=this.text(v,'Telefone',30).replace(/\D/g,'');if(p.length<8||p.length>15)throw new BadRequestException('Telefone inválido.');return p;}
 private hash(token:string){return createHash('sha256').update(token).digest('hex');}
 private async tenant(slug:string){if(!/^[a-z0-9-]{2,80}$/i.test(slug))throw new NotFoundException('Organização não encontrada.');const rows=await this.db.select<any[]>('tenants',`select=id,slug&slug=eq.${encodeURIComponent(slug)}&limit=1`);if(!rows[0])throw new NotFoundException('Organização não encontrada.');return rows[0];}
 private async validateSession(tenantId:string,id:string,token:string){if(!token||typeof token!=='string')throw new UnauthorizedException('Sessão inválida.');const rows=await this.db.select<any[]>('public_chat_sessions',`select=id,tenant_id,conversation_id,contact_id,session_token_hash,status&tenant_id=eq.${tenantId}&id=eq.${id}&limit=1`),s=rows[0];if(!s)throw new UnauthorizedException('Sessão inválida.');const actual=Buffer.from(this.hash(token)),expected=Buffer.from(String(s.session_token_hash));if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new UnauthorizedException('Sessão inválida.');if(s.status!=='open')throw new BadRequestException('Esta conversa foi encerrada. Inicie um novo atendimento.');return s;}
 private messages(t:string,c:string){return this.db.select<any[]>('inbox_messages',`select=id,direction,sender_type,body,created_at&tenant_id=eq.${t}&conversation_id=eq.${c}&direction=in.(inbound,outbound)&deleted_at=is.null&order=created_at.asc`);}
 private async respond(t:string,c:string){const result=await this.attendance.processPublicConversation(t,c);await this.db.insert('inbox_messages',{tenant_id:t,conversation_id:c,direction:'outbound',sender_type:'agent',body:result.answer,status:'sent'});await this.db.update('inbox_conversations',`tenant_id=eq.${t}&id=eq.${c}`,{last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()});}
 async start(slug:string,b:Record<string,unknown>){const tenant=await this.tenant(slug),name=this.text(b.name,'Nome',150),phone=this.normalizePhone(b.phone),message=this.text(b.message,'Mensagem',10000),now=new Date().toISOString();let contacts=await this.db.select<any[]>('contacts',`select=id,name,phone&tenant_id=eq.${tenant.id}&phone=eq.${phone}&deleted_at=is.null&limit=1`);if(!contacts[0])contacts=await this.db.insert<any[]>('contacts',{tenant_id:tenant.id,name,phone,contact_type:'unknown'});const contact=contacts[0],[conversation]=await this.db.insert<any[]>('inbox_conversations',{tenant_id:tenant.id,contact_id:contact.id,channel:'public_chat',status:'open',title:`Atendimento de ${name}`,last_message_at:now});await this.db.insert('inbox_messages',{tenant_id:tenant.id,conversation_id:conversation.id,direction:'inbound',sender_type:'contact',body:message,status:'received'});const token=randomBytes(32).toString('base64url'),[session]=await this.db.insert<any[]>('public_chat_sessions',{tenant_id:tenant.id,conversation_id:conversation.id,contact_id:contact.id,session_token_hash:this.hash(token),contact_name:name,contact_phone:phone,last_seen_at:now});await this.db.insert('inbox_events',{tenant_id:tenant.id,conversation_id:conversation.id,event_type:'public_chat_started',event_title:'Chat público iniciado'});await this.respond(tenant.id,conversation.id);return{session_id:session.id,session_token:token,conversation_id:conversation.id,messages:await this.messages(tenant.id,conversation.id)};}
 async message(slug:string,b:Record<string,unknown>){const tenant=await this.tenant(slug),session=await this.validateSession(tenant.id,this.text(b.session_id,'session_id',80),this.text(b.session_token,'session_token',200)),message=this.text(b.message,'Mensagem',10000),now=new Date().toISOString();await this.db.insert('inbox_messages',{tenant_id:tenant.id,conversation_id:session.conversation_id,direction:'inbound',sender_type:'contact',body:message,status:'received'});await Promise.all([this.db.update('inbox_conversations',`tenant_id=eq.${tenant.id}&id=eq.${session.conversation_id}`,{last_message_at:now,updated_at:now}),this.db.update('public_chat_sessions',`tenant_id=eq.${tenant.id}&id=eq.${session.id}`,{last_seen_at:now}),this.db.insert('inbox_events',{tenant_id:tenant.id,conversation_id:session.conversation_id,event_type:'public_chat_message_received',event_title:'Mensagem recebida pelo chat público'})]);await this.respond(tenant.id,session.conversation_id);return{session_id:session.id,conversation_id:session.conversation_id,messages:await this.messages(tenant.id,session.conversation_id)};}
 async session(slug:string,id:string,token:string){const tenant=await this.tenant(slug),session=await this.validateSession(tenant.id,id,token);await this.db.update('public_chat_sessions',`tenant_id=eq.${tenant.id}&id=eq.${id}`,{last_seen_at:new Date().toISOString()});return{session_id:id,conversation_id:session.conversation_id,messages:await this.messages(tenant.id,session.conversation_id)};}
}
