'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Card, StatusBadge } from '../ui';
import { getApiConfig, listApiFieldMappings, listApiRuns, saveApiConfig, saveApiFieldMappings, syncApiNow, testApi, useApiSample, type ApiConnectorConfig, type ApiSyncRun } from '../../lib/api-connector-api';
import type { DataContractField } from '../../lib/data-contracts-api';

type Phase = 'connection' | 'sample' | 'mapping' | 'sync' | 'done';
type Action = 'save' | 'test' | 'sample' | 'mapping' | 'sync' | null;
const phases: Array<{ key: Phase; label: string }> = [{ key: 'connection', label: 'Conexão' }, { key: 'sample', label: 'Amostra' }, { key: 'mapping', label: 'Pareamento' }, { key: 'sync', label: 'Sincronização' }, { key: 'done', label: 'Pronto' }];
const buttonText: Record<Exclude<Action, null>, [string, string]> = { save: ['Salvar e ir para amostra', 'Salvando...'], test: ['Testar conexão', 'Testando...'], sample: ['Usar amostra para pareamento', 'Preparando...'], mapping: ['Confirmar pareamento', 'Confirmando...'], sync: ['Sincronizar agora', 'Sincronizando...'] };
function valuePreview(value: unknown) { if (value == null) return 'Sem valor na amostra'; return typeof value === 'object' ? JSON.stringify(value).slice(0, 90) : String(value).slice(0, 90); }
function inferredType(value: unknown) { if (value == null) return 'desconhecido'; if (Array.isArray(value)) return 'lista'; if (typeof value === 'number') return Number.isInteger(value) ? 'inteiro' : 'decimal'; return typeof value; }
function ActionButton({ action, busy, disabled, onClick }: { action: Exclude<Action, null>; busy: Action; disabled?: boolean; onClick?: () => void }) { return <button type={action === 'save' ? 'submit' : 'button'} onClick={onClick} disabled={disabled || busy !== null} className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{buttonText[action][busy === action ? 1 : 0]}</button>; }

export function ApiConnectionPanel({ tenantId, sourceId, fields }: { tenantId: string; sourceId: string; fields: DataContractField[] }) {
  const [phase, setPhase] = useState<Phase>('connection');
  const [config, setConfig] = useState<ApiConnectorConfig | null>(null);
  const [runs, setRuns] = useState<ApiSyncRun[]>([]);
  const [result, setResult] = useState<{ http_status: number; record_count: number; fields: string[]; sample?: Record<string, unknown>[] } | null>(null);
  const [draft, setDraft] = useState<Record<string, string>>({});
  const [msg, setMsg] = useState('');
  const [messageTone, setMessageTone] = useState<'success' | 'error'>('success');
  const [busy, setBusy] = useState<Action>(null);
  async function load() { const [current, history, mappings] = await Promise.all([getApiConfig(tenantId, sourceId), listApiRuns(tenantId, sourceId), listApiFieldMappings(tenantId, sourceId)]); setConfig(current); setRuns(history); setDraft(Object.fromEntries(mappings.map((mapping) => [mapping.api_source_field_name, mapping.data_contract_field_id]))); }
  useEffect(() => { if (tenantId) load().catch((error: Error) => { setMessageTone('error'); setMsg(error.message); }); }, [tenantId, sourceId]);
  async function act(action: Exclude<Action, null>, operation: () => Promise<void>) { setBusy(action); setMsg(''); try { await operation(); setMessageTone('success'); } catch (error) { setMessageTone('error'); setMsg((error as Error).message); } finally { setBusy(null); } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act('save', async () => { await saveApiConfig(tenantId, sourceId, Object.fromEntries(form.entries())); await load(); setMsg('Conexão salva com sucesso e segredo protegido.'); setPhase('sample'); }); }
  const test = () => act('test', async () => { const response = await testApi(tenantId, sourceId); setResult(response); setMsg('Conexão realizada com sucesso. A amostra está pronta para revisão.'); });
  const sample = () => act('sample', async () => { const response = await useApiSample(tenantId, sourceId); setResult({ http_status: response.http_status, record_count: response.sample.length, fields: response.fields, sample: response.sample }); await load(); setMsg('Amostra preparada com sucesso, sem alterar o contrato nativo.'); setPhase('mapping'); });
  const detected = result?.fields ?? config?.detected_fields ?? [];
  const sampleRows = result?.sample ?? config?.sample_preview ?? [];
  const duplicates = useMemo(() => { const counts = Object.values(draft).filter(Boolean).reduce<Record<string, number>>((all, id) => ({ ...all, [id]: (all[id] ?? 0) + 1 }), {}); return new Set(Object.keys(counts).filter((id) => counts[id] > 1)); }, [draft]);
  const mappedCount = detected.filter((source) => Boolean(draft[source])).length;
  const unmappedCount = detected.length - mappedCount;
  const missingRequired = fields.filter((field) => field.is_required && !Object.values(draft).includes(field.id));
  const confirmMappings = () => act('mapping', async () => { await saveApiFieldMappings(tenantId, sourceId, Object.entries(draft).filter(([, target]) => target).map(([source_field_name, data_contract_field_id]) => ({ source_field_name, data_contract_field_id }))); await load(); setMsg('Pareamento parcial confirmado. Campos não pareados serão ignorados operacionalmente.'); setPhase('sync'); });
  const sync = () => act('sync', async () => { const response = await syncApiNow(tenantId, sourceId); await load(); setMsg(`Sincronização concluída: ${response.accepted_count} aceitos, ${response.rejected_count} rejeitados e ${response.unchanged_count} sem alteração.`); setPhase('done'); });
  const sampleValue = (source: string) => sampleRows.find((row) => Object.hasOwn(row, source))?.[source];
  return <div className="space-y-4">
    <div className="grid gap-2 md:grid-cols-5">{phases.map((item, index) => <button key={item.key} type="button" onClick={() => setPhase(item.key)} className={`rounded-xl border p-3 text-left ${phase === item.key ? 'border-blue-500 bg-blue-50' : 'bg-white'}`}><span className="text-xs font-bold text-slate-500">{index + 1}</span><p className="font-bold">{item.label}</p></button>)}</div>
    {msg ? <p role={messageTone === 'error' ? 'alert' : 'status'} className={`rounded-xl border p-3 text-sm ${messageTone === 'error' ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{msg}</p> : null}
    {phase === 'connection' ? <Card><h2 className="text-xl font-bold">Conexão de leitura</h2><p className="mt-1 text-sm text-slate-600">Somente GET. O segredo nunca é devolvido ao navegador.</p><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-2">{[['base_url', 'URL base', 'https://legado.exemplo.com'], ['endpoint_path', 'Endpoint', '/api/entregas'], ['response_root_path', 'Raiz da resposta', 'data'], ['external_id_field', 'Identificador externo', 'id'], ['updated_at_field', 'Campo de atualização', 'updated_at'], ['updated_since_param', 'Parâmetro updated since', 'updated_since'], ['page_param', 'Parâmetro de página', 'page'], ['page_size_param', 'Parâmetro de limite', 'limit']].map(([name, label, placeholder]) => <label key={name} className="text-sm font-semibold">{label}<input name={name} required={name === 'base_url' || name === 'endpoint_path'} defaultValue={String(config?.[name as keyof ApiConnectorConfig] ?? '')} placeholder={placeholder} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>)}<label className="text-sm font-semibold">Autenticação<select name="auth_type" defaultValue={config?.auth_type ?? 'none'} className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="none">Nenhuma</option><option value="bearer_token">Bearer token</option><option value="api_key_header">API key em header</option><option value="basic">Basic</option></select></label><label className="text-sm font-semibold">Nome do header<input name="auth_header_name" defaultValue={config?.auth_header_name ?? ''} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">Token/segredo<input name="secret" type="password" placeholder={config?.credentials_configured ? 'Configurado — vazio mantém o segredo' : 'Obrigatório quando houver autenticação'} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">Limite por página<input name="page_size" type="number" min="1" max="500" defaultValue={config?.page_size ?? 100} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input name="auto_sync_enabled" type="checkbox" value="true" defaultChecked={config?.auto_sync_enabled} />Atualização automática</label><label className="text-sm font-semibold">Periodicidade<select name="sync_frequency_minutes" defaultValue={config?.sync_frequency_minutes ?? ''} className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="">Manual</option><option value="15">A cada 15 min</option><option value="60">A cada hora</option><option value="1440">Diária</option></select></label><ActionButton action="save" busy={busy} /></form></Card> : null}
    {phase === 'sample' ? <Card><h2 className="text-xl font-bold">Amostra</h2><div className="mt-4 flex flex-wrap gap-2"><ActionButton action="test" busy={busy} disabled={!config} onClick={test} /><ActionButton action="sample" busy={busy} disabled={!result} onClick={sample} /></div>{result ? <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><b>HTTP {result.http_status}</b> · {result.record_count} registros<p className="mt-2">Campos: {result.fields.join(', ') || 'nenhum'}</p></div> : null}</Card> : null}
    {phase === 'mapping' ? <div className="grid gap-4 xl:grid-cols-3">
      <Card><h2 className="text-lg font-bold">Campos da API</h2><p className="mt-1 text-sm text-slate-600">Campos detectados na amostra recebida.</p><div className="mt-4 space-y-3">{detected.map((source) => { const value = sampleValue(source); return <div key={source} className="rounded-2xl border p-3"><div className="flex justify-between gap-2"><StatusBadge>{draft[source] ? 'pareado' : 'não pareado'}</StatusBadge><span className="text-xs text-slate-500">{inferredType(value)}</span></div><p className="mt-2 break-all font-mono text-sm font-semibold">{source}</p><p className="mt-2 break-all text-xs text-slate-600">Exemplo: {valuePreview(value)}</p></div>; })}</div></Card>
      <Card><h2 className="text-lg font-bold">Pareamento</h2><p className="mt-1 text-sm text-slate-600">Você não precisa parear todos os campos recebidos da API. Campos não pareados serão ignorados operacionalmente. Quanto mais campos forem pareados, mais recursos ficarão disponíveis.</p><div className="mt-4 space-y-3">{detected.map((source) => { const duplicate = Boolean(draft[source] && duplicates.has(draft[source])); return <label key={source} className={`block rounded-2xl border p-3 ${duplicate ? 'border-rose-400 bg-rose-50' : ''}`}><div className="flex items-center justify-between gap-2"><span className="break-all font-mono text-sm">{source}</span><StatusBadge tone={duplicate ? 'warning' : draft[source] ? 'success' : 'neutral'}>{duplicate ? 'duplicado' : draft[source] ? 'pareado' : 'não pareado'}</StatusBadge></div><select value={draft[source] ?? ''} onChange={(event) => setDraft((current) => ({ ...current, [source]: event.target.value }))} className="mt-3 w-full rounded-xl border p-2"><option value="">Não parear</option>{fields.map((field) => <option key={field.id} value={field.id}>{field.field_key}{field.is_required ? ' *' : ''}</option>)}</select>{duplicate ? <p className="mt-2 text-xs font-semibold text-rose-700">Erro: este campo nativo já recebe outro campo da API.</p> : null}</label>; })}</div></Card>
      <Card><h2 className="text-lg font-bold">Preview / Sincronização</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center text-sm"><div className="rounded-xl bg-slate-50 p-3"><b className="block text-xl">{detected.length}</b>detectados</div><div className="rounded-xl bg-emerald-50 p-3"><b className="block text-xl">{mappedCount}</b>pareados</div><div className="rounded-xl bg-slate-50 p-3"><b className="block text-xl">{unmappedCount}</b>não pareados</div></div><div className="mt-4 rounded-2xl border p-3 text-sm"><p className="font-semibold">Resumo da amostra</p><p className="mt-1 text-slate-600">{sampleRows.length} registro(s) disponíveis para preview.</p></div><div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><p className="font-semibold">Pendências de qualidade</p><p className="mt-1">{missingRequired.length ? `${missingRequired.length} campo(s) nativo(s) obrigatório(s) ainda não pareado(s): ${missingRequired.map((field) => field.field_key).join(', ')}. Isso não bloqueia a sincronização.` : 'Nenhuma pendência de completude.'}</p></div>{duplicates.size ? <p className="mt-3 text-sm font-semibold text-rose-700">Corrija os pareamentos duplicados antes de confirmar.</p> : null}<div className="mt-4"><ActionButton action="mapping" busy={busy} disabled={!detected.length || duplicates.size > 0} onClick={confirmMappings} /></div></Card>
    </div> : null}
    {phase === 'sync' ? <Card><h2 className="text-xl font-bold">Sincronização</h2><p className="mt-2 text-sm text-slate-600">Somente campos pareados serão validados e gravados no payload normalizado. O payload bruto completo será preservado para auditoria.</p><div className="mt-4"><ActionButton action="sync" busy={busy} disabled={!config || mappedCount === 0} onClick={sync} /></div><p className="mt-3 text-sm">Automática: {config?.auto_sync_enabled ? 'ativa' : 'inativa'} · Próxima: {config?.next_sync_at ?? '—'}</p></Card> : null}
    {phase === 'done' ? <Card><h2 className="text-xl font-bold">Resultado da sincronização</h2><p className="mt-2 text-sm">Última sync: {config?.last_sync_at ?? '—'} · Próxima: {config?.next_sync_at ?? '—'}</p><div className="mt-3 space-y-2">{runs.slice(0, 8).map((run) => <div key={run.id} className="rounded-xl border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span>{run.sync_type} · {new Date(run.created_at).toLocaleString('pt-BR')}</span><StatusBadge tone={run.status === 'completed' ? 'success' : run.status === 'failed' ? 'neutral' : 'warning'}>{run.status}</StatusBadge></div><p className="mt-2">{run.received_count} recebidos · {run.accepted_count} aceitos · {run.rejected_count} rejeitados · {run.unchanged_count} sem alteração</p>{run.error_message_safe ? <p className="mt-2 text-rose-700">Erro: {run.error_message_safe}</p> : null}{run.rejected_count > 0 && run.errors.length ? <div className="mt-3 overflow-x-auto"><p className="font-semibold text-rose-800">Primeiros erros do lote</p><table className="mt-2 min-w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pr-3">Linha</th><th className="pr-3">Campo</th><th className="pr-3">Código</th><th>Mensagem</th></tr></thead><tbody>{run.errors.map((error) => <tr key={error.id} className="border-t"><td className="py-2 pr-3">{error.row_number ?? '—'}</td><td className="pr-3">{error.field ?? '—'}</td><td className="pr-3 font-mono">{error.error_code}</td><td>{error.message}</td></tr>)}</tbody></table></div> : null}</div>)}</div></Card> : null}
  </div>;
}
