'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Card, StatusBadge } from '../ui';
import { getApiConfig, listApiFieldMappings, listApiRuns, saveApiConfig, saveApiFieldMappings, syncApiNow, testApi, useApiSample, type ApiConnectorConfig, type ApiSyncRun } from '../../lib/api-connector-api';
import type { DataContractField } from '../../lib/data-contracts-api';

type Phase = 'connection' | 'sample' | 'mapping' | 'sync' | 'done';
const phases: Array<{ key: Phase; label: string }> = [{ key: 'connection', label: 'Conexão' }, { key: 'sample', label: 'Amostra' }, { key: 'mapping', label: 'Pareamento' }, { key: 'sync', label: 'Sincronização' }, { key: 'done', label: 'Pronto' }];
export function ApiConnectionPanel({ tenantId, sourceId, fields }: { tenantId: string; sourceId: string; fields: DataContractField[] }) {
  const [phase, setPhase] = useState<Phase>('connection'); const [config, setConfig] = useState<ApiConnectorConfig | null>(null); const [runs, setRuns] = useState<ApiSyncRun[]>([]); const [result, setResult] = useState<{ http_status: number; record_count: number; fields: string[] } | null>(null); const [draft, setDraft] = useState<Record<string, string>>({}); const [msg, setMsg] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { const [current, history, mappings] = await Promise.all([getApiConfig(tenantId, sourceId), listApiRuns(tenantId, sourceId), listApiFieldMappings(tenantId, sourceId)]); setConfig(current); setRuns(history); setDraft(Object.fromEntries(mappings.map((mapping) => [mapping.api_source_field_name, mapping.data_contract_field_id]))); }
  useEffect(() => { if (tenantId) load().catch((error: Error) => setMsg(error.message)); }, [tenantId, sourceId]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await saveApiConfig(tenantId, sourceId, Object.fromEntries(form.entries())); await load(); setMsg('Conexão salva com segredo protegido.'); setPhase('sample'); } catch (error) { setMsg((error as Error).message); } finally { setBusy(false); } }
  async function test() { setBusy(true); try { const response = await testApi(tenantId, sourceId); setResult(response); setMsg('Conexão realizada com sucesso.'); } catch (error) { setMsg((error as Error).message); } finally { setBusy(false); } }
  async function sample() { setBusy(true); try { const response = await useApiSample(tenantId, sourceId); setResult({ http_status: response.http_status, record_count: response.sample.length, fields: response.fields }); await load(); setMsg('Amostra salva sem alterar o contrato nativo.'); setPhase('mapping'); } catch (error) { setMsg((error as Error).message); } finally { setBusy(false); } }
  async function mappings() { setBusy(true); try { await saveApiFieldMappings(tenantId, sourceId, Object.entries(draft).filter(([, target]) => target).map(([source_field_name, data_contract_field_id]) => ({ source_field_name, data_contract_field_id }))); await load(); setMsg('Pareamento confirmado.'); setPhase('sync'); } catch (error) { setMsg((error as Error).message); } finally { setBusy(false); } }
  async function sync() { setBusy(true); try { const response = await syncApiNow(tenantId, sourceId); await load(); setMsg(`Lote criado: ${response.accepted_count} aceitos, ${response.rejected_count} rejeitados e ${response.unchanged_count} sem alteração.`); setPhase('done'); } catch (error) { setMsg((error as Error).message); } finally { setBusy(false); } }
  const detected = result?.fields ?? config?.detected_fields ?? [];
  return <div className="space-y-4"><div className="grid gap-2 md:grid-cols-5">{phases.map((item, index) => <button key={item.key} type="button" onClick={() => setPhase(item.key)} className={`rounded-xl border p-3 text-left ${phase === item.key ? 'border-blue-500 bg-blue-50' : 'bg-white'}`}><span className="text-xs font-bold text-slate-500">{index + 1}</span><p className="font-bold">{item.label}</p></button>)}</div>{msg ? <p className="rounded-xl bg-slate-50 p-3 text-sm">{msg}</p> : null}
  {phase === 'connection' ? <Card><h2 className="text-xl font-bold">Conexão de leitura</h2><p className="mt-1 text-sm text-slate-600">Somente GET. O segredo nunca é devolvido ao navegador.</p><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-2">{[['base_url', 'URL base', 'https://legado.exemplo.com'], ['endpoint_path', 'Endpoint', '/api/entregas'], ['response_root_path', 'Raiz da resposta', 'data'], ['external_id_field', 'Identificador externo', 'id'], ['updated_at_field', 'Campo de atualização', 'updated_at'], ['updated_since_param', 'Parâmetro updated since', 'updated_since'], ['page_param', 'Parâmetro de página', 'page'], ['page_size_param', 'Parâmetro de limite', 'limit']].map(([name, label, placeholder]) => <label key={name} className="text-sm font-semibold">{label}<input name={name} required={name === 'base_url' || name === 'endpoint_path'} defaultValue={String(config?.[name as keyof ApiConnectorConfig] ?? '')} placeholder={placeholder} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>)}<label className="text-sm font-semibold">Autenticação<select name="auth_type" defaultValue={config?.auth_type ?? 'none'} className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="none">Nenhuma</option><option value="bearer_token">Bearer token</option><option value="api_key_header">API key em header</option><option value="basic">Basic</option></select></label><label className="text-sm font-semibold">Nome do header<input name="auth_header_name" defaultValue={config?.auth_header_name ?? ''} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">Token/segredo<input name="secret" type="password" placeholder={config?.credentials_configured ? 'Configurado — vazio mantém o segredo' : 'Obrigatório quando houver autenticação'} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">Limite por página<input name="page_size" type="number" min="1" max="500" defaultValue={config?.page_size ?? 100} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input name="auto_sync_enabled" type="checkbox" value="true" defaultChecked={config?.auto_sync_enabled} />Atualização automática</label><label className="text-sm font-semibold">Periodicidade<select name="sync_frequency_minutes" defaultValue={config?.sync_frequency_minutes ?? ''} className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="">Manual</option><option value="15">A cada 15 min</option><option value="60">A cada hora</option><option value="1440">Diária</option></select></label><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:bg-slate-300">Salvar e ir para amostra</button></form></Card> : null}
  {phase === 'sample' ? <Card><h2 className="text-xl font-bold">Amostra</h2><div className="mt-4 flex gap-2"><button onClick={test} disabled={!config || busy} className="rounded-xl border px-4 py-2 font-bold">Testar conexão</button><button onClick={sample} disabled={!result || busy} className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">Usar amostra para pareamento</button></div>{result ? <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><b>HTTP {result.http_status}</b> · {result.record_count} registros<p className="mt-2">Campos: {result.fields.join(', ') || 'nenhum'}</p></div> : null}</Card> : null}
  {phase === 'mapping' ? <Card><h2 className="text-xl font-bold">Pareamento API → contrato nativo</h2><div className="mt-4 space-y-2">{detected.map((source) => <label key={source} className="grid items-center gap-2 rounded-xl border p-3 md:grid-cols-2"><span className="font-mono text-sm">{source}</span><select value={draft[source] ?? ''} onChange={(event) => setDraft((current) => ({ ...current, [source]: event.target.value }))} className="rounded-xl border p-2"><option value="">Não parear</option>{fields.map((field) => <option key={field.id} value={field.id}>{field.field_key}{field.is_required ? ' *' : ''}</option>)}</select></label>)}</div><button onClick={mappings} disabled={!detected.length || busy} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">Confirmar pareamento</button></Card> : null}
  {phase === 'sync' ? <Card><h2 className="text-xl font-bold">Sincronização</h2><button onClick={sync} disabled={!config || busy} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">Sincronizar agora</button><p className="mt-3 text-sm">Automática: {config?.auto_sync_enabled ? 'ativa' : 'inativa'} · Próxima: {config?.next_sync_at ?? '—'}</p></Card> : null}
  {phase === 'done' ? <Card><h2 className="text-xl font-bold">Integração pronta</h2><p className="mt-2 text-sm">Última sync: {config?.last_sync_at ?? '—'} · Próxima: {config?.next_sync_at ?? '—'} · Cursor: {config?.last_cursor ?? '—'}</p><div className="mt-3 space-y-2">{runs.slice(0, 8).map((run) => <div key={run.id} className="flex flex-wrap items-center justify-between rounded-xl border p-3 text-sm"><span>{run.sync_type} · {new Date(run.created_at).toLocaleString('pt-BR')}</span><span>{run.received_count} recebidos · {run.accepted_count} aceitos · {run.rejected_count} rejeitados</span><StatusBadge tone={run.status === 'completed' ? 'success' : run.status === 'failed' ? 'neutral' : 'warning'}>{run.status}</StatusBadge></div>)}</div></Card> : null}</div>;
}
