import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { NativeIndicatorsService } from '../native-indicators/native-indicators.service';
import { CustomIndicatorsService } from '../custom-indicators/custom-indicators.service';
const filterTypes: Record<string, 'date_range'|'multi_select'>={issued_at:'date_range',expected_date:'date_range',completed_at:'date_range',updated_at:'date_range',customer_name:'multi_select',shipper_name:'multi_select',recipient_name:'multi_select',origin_city:'multi_select',origin_state:'multi_select',destination_city:'multi_select',destination_state:'multi_select',status:'multi_select',document_type:'multi_select',driver_name:'multi_select',vehicle_plate:'multi_select'};
const labels:Record<string,string>={issued_at:'Data de emissão',expected_date:'Data prevista',completed_at:'Data de entrega',updated_at:'Data de atualização',customer_name:'Cliente',shipper_name:'Embarcador',recipient_name:'Destinatário',origin_city:'Cidade origem',origin_state:'UF origem',destination_city:'Cidade destino',destination_state:'UF destino',status:'Status',document_type:'Tipo de documento',driver_name:'Motorista',vehicle_plate:'Veículo'};
const moduleMap:Record<string,string>={transporte:'transport',transport:'transport',financeiro:'finance',finance:'finance',atendimento:'attendance',attendance:'attendance',armazem:'warehouse',warehouse:'warehouse',equipes:'team',team:'team'};
const moduleLabels:Record<string,string>={transport:'Transporte',finance:'Financeiro',attendance:'Atendimento',warehouse:'Armazém',team:'Equipes'}; const visuals=new Set(['kpi','table','matrix','bar','pie','line']);
@Injectable() export class ReportsService { constructor(private s:SupabaseService,private native:NativeIndicatorsService,private custom:CustomIndicatorsService){}
 async list(t:string,configure=false){const reports=await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}${configure?'':'&status=eq.active'}&order=updated_at.desc`);const ids=reports.map(x=>x.id);if(!ids.length)return {data:reports,limit:await this.limit(t)};const [sections,blocks]=await Promise.all([this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=in.(${ids.join(',')})`),this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=in.(${ids.join(',')})`)]);return {data:reports.map(report=>({...report,sections:sections.filter(s=>s.report_definition_id===report.id),blocks:blocks.filter(b=>b.report_definition_id===report.id)})),limit:await this.limit(t)}}
 async modules(t:string){const rows=await this.s.select<any[]>('tenant_modules',`select=module:modules(id,key,name)&tenant_id=eq.${t}&is_active=eq.true`);return {data:rows.map(x=>x.module).filter((x:any)=>x&&moduleMap[x.key]).map((x:any)=>({key:moduleMap[x.key],label:moduleLabels[moduleMap[x.key]]??x.name}))}}
 async create(t:string,u:string,b:any){const limit=await this.limit(t);const count=(await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&status=neq.archived&select=id`)).length;if(limit!==null&&count>=limit)throw new BadRequestException('Limite de relatórios do plano atingido.');const key=await this.module(t,b.module_key);if(!String(b.name||'').trim())throw new BadRequestException('Nome é obrigatório.');return (await this.s.insert<any[]>('report_definitions',{tenant_id:t,name:b.name.trim(),description:b.description??null,module_key:key,created_by:u}))[0]}
 async detail(t:string,id:string,u?:string){const report=await this.report(t,id);const [sections,fs,settings]=await Promise.all([this.sections(t,id),this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position.asc`),u?this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`):[]]);return {...report,sections:sections.data,blocks:sections.data.flatMap((x:any)=>x.blocks),filters:fs,settings:settings[0]??null}}
 async update(t:string,id:string,b:any){await this.report(t,id);const p:any={updated_at:new Date().toISOString()};for(const k of ['name','description','ai_enabled'])if(k in b)p[k]=b[k];if('module_key'in b)p.module_key=await this.module(t,b.module_key);if('status'in b){if(!['draft','active','archived'].includes(b.status))throw new BadRequestException('Status inválido.');if(b.status==='active'){const [sections,blocks]=await Promise.all([this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&select=id`),this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&select=report_section_id`)]);if(!sections.length||!blocks.some(block=>sections.some(section=>section.id===block.report_section_id)))throw new BadRequestException('Adicione ao menos um indicador antes de ativar o relatório.')}p.status=b.status}return(await this.s.update<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}`,p))[0]}
 async archive(t:string,id:string){await this.report(t,id);const now=new Date().toISOString();return (await this.s.update<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}`,{status:'archived',deleted_at:now,updated_at:now}))[0]}
 async sections(t:string,id:string){await this.report(t,id);const data=await this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position_order.asc`);const blocks=await this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position_order.asc`);return {data:data.map(x=>({...x,blocks:blocks.filter(b=>b.report_section_id===x.id)}))}}
 async addSection(t:string,id:string,b:any){await this.report(t,id);if(!String(b.title||'').trim())throw new BadRequestException('Nome do bloco é obrigatório.');return(await this.s.insert<any[]>('report_sections',{tenant_id:t,report_definition_id:id,title:b.title.trim(),description:b.description??null,position_order:Number(b.position_order??0),ai_enabled:b.ai_enabled??true}))[0]}
 async updateSection(t:string,id:string,sid:string,b:any){await this.section(t,id,sid);const p:any={updated_at:new Date().toISOString()};for(const k of ['title','description','position_order','ai_enabled'])if(k in b)p[k]=b[k];return(await this.s.update<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${sid}`,p))[0]}
 async deleteSection(t:string,id:string,sid:string){const section=await this.section(t,id,sid);const blocks=await this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&report_section_id=eq.${sid}`);if(blocks.length)throw new BadRequestException('Remova os indicadores da seção antes de excluir o bloco.');return(await this.s.delete<any[]>('report_sections',`id=eq.${section.id}&tenant_id=eq.${t}`))[0]}
 async addBlock(t:string,id:string,b:any){const report=await this.report(t,id);if(!b.report_section_id)throw new BadRequestException('Bloco do relatório é obrigatório.');await this.section(t,id,b.report_section_id);const indicator=await this.validIndicator(t,b.source_type,b.source_id,report.module_key);const visual=b.visual_type;this.validBlock(b.block_type??visual,visual,indicator);if(!String(b.title||'').trim())throw new BadRequestException('Título é obrigatório.');return(await this.s.insert<any[]>('report_blocks',{tenant_id:t,report_definition_id:id,report_section_id:b.report_section_id,block_key:String(b.block_key||Date.now()),block_type:visual,title:b.title.trim(),source_type:b.source_type,source_id:b.source_id,visual_type:visual,position_order:Number(b.position_order??0),position:b.position??{},config:b.config??{}}))[0]}
 async updateBlock(t:string,id:string,bid:string,b:any){const cur=await this.item('report_blocks',t,id,bid),report=await this.report(t,id);if(b.report_section_id)await this.section(t,id,b.report_section_id);const visual=b.visual_type??cur.visual_type,indicator=await this.validIndicator(t,b.source_type??cur.source_type,b.source_id??cur.source_id,report.module_key);this.validBlock(b.block_type??visual,visual,indicator);const p:any={updated_at:new Date().toISOString()};for(const k of ['title','source_type','source_id','visual_type','report_section_id','position_order','position','config'])if(k in b)p[k]=b[k];if('visual_type'in b)p.block_type=visual;return(await this.s.update<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`,p))[0]}
 async deleteBlock(t:string,id:string,bid:string){await this.item('report_blocks',t,id,bid);return(await this.s.delete<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`))[0]}
 async addFilter(t:string,id:string,b:any){await this.report(t,id);this.validFilter(b);return(await this.s.insert<any[]>('report_filters',{tenant_id:t,report_definition_id:id,...b,label:labels[b.filter_key],default_value:this.filterValue(b.filter_type,b.default_value??{}),position:Number(b.position??0)}))[0]}
 async deleteFilter(t:string,id:string,fid:string){await this.item('report_filters',t,id,fid);return(await this.s.delete<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${fid}`))[0]}
 async updateFilter(t:string,id:string,fid:string,b:any){const c=await this.item('report_filters',t,id,fid);const final={...c,...b};this.validFilter(final);const p:any={filter_key:final.filter_key,filter_type:final.filter_type,label:labels[final.filter_key],default_value:this.filterValue(final.filter_type,final.default_value),updated_at:new Date().toISOString()};for(const key of ['locked','user_can_override','required','position'])if(key in b)p[key]=b[key];return(await this.s.update<any[]>('report_filters',`id=eq.${fid}&tenant_id=eq.${t}&report_definition_id=eq.${id}`,p))[0]}
 async settings(t:string,id:string,u:string){await this.report(t,id);return (await this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0]??null}
 async saveSettings(t:string,id:string,u:string,b:any){const fs=await this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}`);const o=this.validOverrides(fs,b.filters_override??{});const old=await this.settings(t,id,u);const p={tenant_id:t,report_definition_id:id,user_id:u,filters_override:o,preferred_format:'preview',send_enabled:false,updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_user_settings',`id=eq.${old.id}&tenant_id=eq.${t}`,p))[0]:(await this.s.insert<any[]>('report_user_settings',p))[0]}
 async recipients(t:string,id:string,u:string){return {data:await this.s.select<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`)}}
 async recipient(t:string,id:string,u:string,b:any,rid?:string){if(!/^\S+@\S+\.\S+$/.test(String(b.recipient_email??'')))throw new BadRequestException('E-mail inválido.');const p={recipient_name:b.recipient_name??null,recipient_email:b.recipient_email,is_active:b.is_active??true,updated_at:new Date().toISOString()};return rid?(await this.s.update<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`,p))[0]:(await this.s.insert<any[]>('report_recipients',{...p,tenant_id:t,report_definition_id:id,user_id:u}))[0]}
 async deleteRecipient(t:string,id:string,u:string,rid:string){return (await this.s.delete<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`))[0]}
 async schedule(t:string,id:string,u:string,b?:any){const old=(await this.s.select<any[]>('report_schedules',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0];if(!b)return old??null;if(!['daily','weekly','monthly'].includes(b.frequency??'daily'))throw new BadRequestException('Periodicidade inválida.');const p={tenant_id:t,report_definition_id:id,user_id:u,enabled:!!b.enabled,frequency:b.frequency??'daily',day_of_week:b.day_of_week??null,day_of_month:b.day_of_month??null,time_of_day:b.time_of_day??null,timezone:b.timezone??'America/Sao_Paulo',updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_schedules',`id=eq.${old.id}&tenant_id=eq.${t}`,p))[0]:(await this.s.insert<any[]>('report_schedules',p))[0]}
 async preview(t:string,id:string,u:string,b:any){const report=await this.report(t,id),d=await this.detail(t,id,u);if(!d.sections.length)throw new BadRequestException('Adicione ao menos um bloco ao relatório antes de gerar o preview.');if(!d.blocks.length)throw new BadRequestException('Adicione ao menos um indicador antes de gerar o preview.');const overrides=this.validOverrides(d.filters,b.filters_override??{});const effective=d.filters.map((f:any)=>({key:f.filter_key,type:f.filter_type,value:(f.locked||!f.user_can_override)?this.filterValue(f.filter_type,f.default_value):(Object.hasOwn(overrides,f.filter_key)?overrides[f.filter_key]:this.filterValue(f.filter_type,f.default_value))}));const global_filters=this.toGlobalFilters(effective),results:any={};for(const x of d.blocks){try{results[x.id]=x.source_type==='native_indicator'?await this.native.preview(t,x.source_id,u,false,{global_filters}):await this.custom.previewSaved(t,x.source_id,u,{global_filters})}catch(e:any){const sec=d.sections.find((s:any)=>s.id===x.report_section_id);throw new BadRequestException(`Não foi possível gerar o bloco ${sec?.title??x.title}: ${e.message}`)}}const render_snapshot={report:{id:report.id,name:report.name,description:report.description,module_key:report.module_key,generated_at:new Date().toISOString()},filters:effective,sections:d.sections.map((s:any)=>({...s,analysis_placeholder:'Análise deste bloco será gerada pela IA na próxima etapa.',blocks:s.blocks.map((x:any)=>({...x,data:results[x.id]}))})),ai:{enabled:false,opening_placeholder:'A análise automática será adicionada na próxima etapa com IA.',closing_placeholder:'A análise automática será adicionada na próxima etapa com IA.'}};const job=(await this.s.insert<any[]>('report_jobs',{tenant_id:t,report_definition_id:id,requested_by:u,trigger_type:'manual',status:'completed',filters_snapshot:effective,data_snapshot:results,render_snapshot,ai_snapshot:null,started_at:new Date().toISOString(),finished_at:new Date().toISOString()}))[0];return{job,render_snapshot}}
 async jobs(t:string,id:string){return{data:await this.s.select<any[]>('report_jobs',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=created_at.desc&limit=20`)}}
 async indicatorLibrary(t:string,moduleKey?:string){const key=moduleKey?moduleMap[moduleKey]:undefined;const [n,c]=await Promise.all([this.native.list(t),this.custom.list(t)]);const data=[...n.data.map((x:any)=>({id:x.indicator_key,source_type:'native_indicator',name:x.name,description:x.description,module_key:x.module_key,module_label:moduleLabels[x.module_key],result_shape:x.result_shape,allowed_visual_types:this.visuals(x),recommended_visual_type:this.visuals(x)[0],availability:x.availability?.status,reason:x.availability?.reason})),...(c.data as any[]).map(x=>({id:x.id,source_type:'custom_indicator',name:x.name,description:x.description,module_key:x.module_key,module_label:moduleLabels[x.module_key],allowed_visual_types:this.visuals(x),recommended_visual_type:this.visuals(x)[0],availability:x.status==='active'&&x.available_for_dashboard?'available':'unavailable',reason:x.status!=='active'?'Indicador inativo':undefined}))].filter((x:any)=>!key||x.module_key===key);return{data}}
 async nativeFilters(){return{data:Object.entries(filterTypes).map(([key,filter_type])=>({key,label:labels[key],filter_type}))}}
 private visuals(x:any){const v=String(x.visualization_type??x.calculation_type??x.operation_key??'').toLowerCase();if(/latest|table/.test(v))return['table'];if(/matrix|pivot/.test(v))return['matrix','table'];if(/ranking/.test(v))return['bar','table'];if(/distribution/.test(v))return['bar','pie','table'];if(/series|period|line/.test(v))return['line','bar','table'];return['kpi']}
 private validBlock(type:any,visual:any,i:any){if(!visuals.has(visual)||type!==visual||!i.allowed_visual_types.includes(visual))throw new BadRequestException('Tipo visual incompatível com o indicador.')}
 private async module(t:string,k:any){const normalized=moduleMap[String(k??'')];if(!normalized)throw new BadRequestException('Módulo inválido.');const active=await this.modules(t);if(!active.data.some((x:any)=>x.key===normalized))throw new BadRequestException('Módulo não está ativo para este tenant.');return normalized}
 private async report(t:string,id:string){const r=await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}&status=neq.archived`);if(!r[0])throw new NotFoundException('Relatório não encontrado.');return r[0]}
 private async section(t:string,id:string,sid:string){const r=await this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${sid}`);if(!r[0])throw new NotFoundException('Bloco não encontrado.');return r[0]}
 private async item(table:string,t:string,id:string,x:string){const r=await this.s.select<any[]>(table,`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${x}`);if(!r[0])throw new NotFoundException('Item não encontrado.');return r[0]}
 private async limit(t:string){const r=await this.s.select<any[]>('subscription_limits',`tenant_id=eq.${t}&key=eq.reports.max_definitions&select=limit_value&limit=1`);return r[0]?Number(r[0].limit_value):null}
 private validFilter(b:any){if(!filterTypes[b.filter_key]||filterTypes[b.filter_key]!==b.filter_type)throw new BadRequestException('Filtro nativo inválido.')}
 private filterValue(type:string,v:any){if(type==='date_range')return{from:v?.from??'',to:v?.to??''};const values=Array.isArray(v)?v:v?.values;if(!Array.isArray(values))throw new BadRequestException('Filtro de múltipla seleção inválido.');return{values}}
 private async validIndicator(t:string,type:any,id:any,module:string){if(!['native_indicator','custom_indicator'].includes(type)||!id)throw new BadRequestException('Indicador obrigatório e inválido.');const d:any=type==='native_indicator'?await this.native.detail(t,id):await this.custom.detail(t,id);if(d.module_key && d.module_key!==module)throw new BadRequestException('Indicador incompatível com o módulo do relatório.');if(type==='native_indicator'&&!['available','partial'].includes(d.availability?.status))throw new BadRequestException('Indicador nativo indisponível.');if(type==='custom_indicator'&&(d.status!=='active'||!d.available_for_dashboard))throw new BadRequestException('Indicador personalizado indisponível.');return{allowed_visual_types:this.visuals(d)}}
 private toGlobalFilters(items:any[]){return items.flatMap<any>(f=>{const v:any=f.value??{};if(f.type==='multi_select'){const values=v.values??[];return values.length?[{field_key:f.key,operator:values.length===1?'igual a':'em',value:values[0],values}]:[]}const from=v.from??'',to=v.to??'';return from||to?[{field_key:f.key,operator:from&&to?'entre':from?'maior que':'menor que',value:from||to,value_to:to||null}]:[]})}
 private validOverrides(fs:any[],overrides:any){if(!overrides||typeof overrides!=='object'||Array.isArray(overrides))throw new BadRequestException('Filtros inválidos.');const clean:any={};for(const key of Object.keys(overrides)){const f=fs.find(x=>x.filter_key===key);if(!f||!f.user_can_override||f.locked)throw new BadRequestException('Filtro não pode ser alterado pelo cliente.');clean[key]=this.filterValue(f.filter_type,overrides[key])}return clean}
}
