import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { NativeIndicatorsService } from '../native-indicators/native-indicators.service';
import { CustomIndicatorsService } from '../custom-indicators/custom-indicators.service';
import { visualCompatibility } from '../shared/visual-compatibility';
import { AiGatewayService } from '../agents/ai-gateway.service';
import { AgentsEntitlementService } from '../agents/agents-entitlement.service';
import { ReportSnapshotSummarizerService } from './report-snapshot-summarizer.service';
const filterTypes: Record<string, 'date_range'|'multi_select'>={issued_at:'date_range',expected_date:'date_range',completed_at:'date_range',updated_at:'date_range',customer_name:'multi_select',shipper_name:'multi_select',recipient_name:'multi_select',origin_city:'multi_select',origin_state:'multi_select',destination_city:'multi_select',destination_state:'multi_select',status:'multi_select',document_type:'multi_select',driver_name:'multi_select',vehicle_plate:'multi_select'};
const labels:Record<string,string>={issued_at:'Data de emissão',expected_date:'Data prevista',completed_at:'Data de entrega',updated_at:'Data de atualização',customer_name:'Cliente',shipper_name:'Embarcador',recipient_name:'Destinatário',origin_city:'Cidade origem',origin_state:'UF origem',destination_city:'Cidade destino',destination_state:'UF destino',status:'Status',document_type:'Tipo de documento',driver_name:'Motorista',vehicle_plate:'Veículo'};
const moduleMap:Record<string,string>={transporte:'transport',transport:'transport',financeiro:'finance',finance:'finance',atendimento:'attendance',attendance:'attendance',armazem:'warehouse',warehouse:'warehouse',equipes:'team',team:'team'};
const moduleLabels:Record<string,string>={transport:'Transporte',finance:'Financeiro',attendance:'Atendimento',warehouse:'Armazém',team:'Equipes'}; const visuals=new Set(['kpi','table','matrix','bar','pie','line']);
@Injectable() export class ReportsService { constructor(private s:SupabaseService,private native:NativeIndicatorsService,private custom:CustomIndicatorsService,private gateway:AiGatewayService,private summarizer:ReportSnapshotSummarizerService,private entitlement:AgentsEntitlementService){}
 async list(t:string,configure=false){const reports=await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}${configure?'':'&status=eq.active'}&order=updated_at.desc`);const ids=reports.map(x=>x.id);if(!ids.length)return {data:reports,limit:await this.limit(t)};const [sections,blocks]=await Promise.all([this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=in.(${ids.join(',')})`),this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=in.(${ids.join(',')})`)]);return {data:reports.map(report=>({...report,sections:sections.filter(s=>s.report_definition_id===report.id),blocks:blocks.filter(b=>b.report_definition_id===report.id)})),limit:await this.limit(t)}}
 async modules(t:string){const rows=await this.s.select<any[]>('tenant_modules',`select=module:modules(id,key,name)&tenant_id=eq.${t}&is_active=eq.true`);return {data:rows.map(x=>x.module).filter((x:any)=>x&&moduleMap[x.key]).map((x:any)=>({key:moduleMap[x.key],label:moduleLabels[moduleMap[x.key]]??x.name}))}}
 async create(t:string,u:string,b:any){const limit=await this.limit(t);const count=(await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&status=neq.archived&select=id`)).length;if(limit!==null&&count>=limit)throw new BadRequestException('Limite de relatórios do plano atingido.');const key=await this.module(t,b.module_key);if(!String(b.name||'').trim())throw new BadRequestException('Nome é obrigatório.');return (await this.s.insert<any[]>('report_definitions',{tenant_id:t,name:b.name.trim(),description:b.description??null,module_key:key,created_by:u}))[0]}
 async detail(t:string,id:string,u?:string){const report=await this.report(t,id);const [sections,fs,settings]=await Promise.all([this.sections(t,id),this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position.asc`),u?this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`):[]]);return {...report,sections:sections.data,blocks:sections.data.flatMap((x:any)=>x.blocks),filters:fs,settings:settings[0]??null}}
 async update(t:string,id:string,b:any){const report=await this.report(t,id);const p:any={updated_at:new Date().toISOString()};for(const k of ['name','description','ai_enabled'])if(k in b)p[k]=b[k];if('module_key'in b)p.module_key=await this.module(t,b.module_key);if('status'in b){if(!['draft','active','archived'].includes(b.status))throw new BadRequestException('Status inválido.');if(b.status==='active'){const [sections,blocks]=await Promise.all([this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&select=id`),this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}`)]);if(!sections.length||!blocks.some(block=>sections.some(section=>section.id===block.report_section_id)))throw new BadRequestException('Adicione ao menos um indicador antes de ativar o relatório.');for(const block of blocks){const indicator=await this.validIndicator(t,block.source_type,block.source_id,p.module_key??report.module_key);this.validBlock(block.block_type,block.visual_type,indicator);}}p.status=b.status}return(await this.s.update<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}`,p))[0]}
 async archive(t:string,id:string){await this.report(t,id);const now=new Date().toISOString();return (await this.s.update<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}`,{status:'archived',deleted_at:now,updated_at:now}))[0]}
 async sections(t:string,id:string){await this.report(t,id);const data=await this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position_order.asc`);const blocks=await this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position_order.asc`);return {data:data.map(x=>({...x,blocks:blocks.filter(b=>b.report_section_id===x.id)}))}}
 async addSection(t:string,id:string,b:any){await this.report(t,id);if(!String(b.title||'').trim())throw new BadRequestException('Nome do bloco é obrigatório.');return(await this.s.insert<any[]>('report_sections',{tenant_id:t,report_definition_id:id,title:b.title.trim(),description:b.description??null,position_order:Number(b.position_order??0),ai_enabled:b.ai_enabled??true}))[0]}
 async updateSection(t:string,id:string,sid:string,b:any){await this.section(t,id,sid);const p:any={updated_at:new Date().toISOString()};for(const k of ['title','description','position_order','ai_enabled'])if(k in b)p[k]=b[k];return(await this.s.update<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${sid}`,p))[0]}
 async deleteSection(t:string,id:string,sid:string){const section=await this.section(t,id,sid);const blocks=await this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&report_section_id=eq.${sid}`);if(blocks.length)throw new BadRequestException('Remova os indicadores da seção antes de excluir o bloco.');return(await this.s.delete<any[]>('report_sections',`id=eq.${section.id}&tenant_id=eq.${t}`))[0]}
 async addBlock(t:string,id:string,b:any){const report=await this.report(t,id);if(!b.report_section_id)throw new BadRequestException('Bloco do relatório é obrigatório.');await this.section(t,id,b.report_section_id);const indicator=await this.validIndicator(t,b.source_type,b.source_id,report.module_key);const visual=b.visual_type;this.validBlock(b.block_type??visual,visual,indicator);if(!String(b.title||'').trim())throw new BadRequestException('Título é obrigatório.');return(await this.s.insert<any[]>('report_blocks',{tenant_id:t,report_definition_id:id,report_section_id:b.report_section_id,block_key:String(b.block_key||Date.now()),block_type:visual,title:b.title.trim(),source_type:b.source_type,source_id:b.source_id,visual_type:visual,position_order:Number(b.position_order??0),position:b.position??{},config:b.config??{}}))[0]}
 async updateBlock(t:string,id:string,bid:string,b:any){const cur=await this.item('report_blocks',t,id,bid),report=await this.report(t,id);if(b.report_section_id)await this.section(t,id,b.report_section_id);const visual=b.visual_type??cur.visual_type,indicator=await this.validIndicator(t,b.source_type??cur.source_type,b.source_id??cur.source_id,report.module_key);this.validBlock(b.block_type??visual,visual,indicator);const p:any={updated_at:new Date().toISOString()};for(const k of ['title','source_type','source_id','visual_type','report_section_id','position_order','position','config'])if(k in b)p[k]=b[k];if('visual_type'in b)p.block_type=visual;return(await this.s.update<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`,p))[0]}
 async deleteBlock(t:string,id:string,bid:string){await this.item('report_blocks',t,id,bid);return(await this.s.delete<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`))[0]}
 async addFilter(t:string,id:string,b:any){await this.report(t,id);this.validFilter(b);return(await this.s.insert<any[]>('report_filters',{tenant_id:t,report_definition_id:id,...b,label:labels[b.filter_key],default_value:this.filterValue(b.filter_type,b.default_value??{}),position:Number(b.position??0)}))[0]}
 async deleteFilter(t:string,id:string,fid:string){await this.item('report_filters',t,id,fid);return(await this.s.delete<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${fid}`))[0]}
 async updateFilter(t:string,id:string,fid:string,b:any){const c=await this.item('report_filters',t,id,fid);const final={...c,...b};this.validFilter(final);const p:any={filter_key:final.filter_key,filter_type:final.filter_type,label:labels[final.filter_key],default_value:this.filterValue(final.filter_type,final.default_value),updated_at:new Date().toISOString()};for(const key of ['locked','user_can_override','required','position'])if(key in b)p[key]=b[key];return(await this.s.update<any[]>('report_filters',`id=eq.${fid}&tenant_id=eq.${t}&report_definition_id=eq.${id}`,p))[0]}
 async settings(t:string,id:string,u:string){await this.report(t,id);return (await this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0]??null}
 async saveSettings(t:string,id:string,u:string,b:any){const fs=await this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}`);const o=this.validOverrides(fs,b.filters_override??{});const old=await this.settings(t,id,u);const p={tenant_id:t,report_definition_id:id,user_id:u,filters_override:o,preferred_format:'preview',send_enabled:false,updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_user_settings',`id=eq.${old.id}&tenant_id=eq.${t}`,p))[0]:(await this.s.insert<any[]>('report_user_settings',p))[0]}
 async recipients(t:string,id:string,u:string){return {data:await this.s.select<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`)}}
 async recipient(t:string,id:string,u:string,b:any,rid?:string){if(!/^\S+@\S+\.\S+$/.test(String(b.recipient_email??'')))throw new BadRequestException('E-mail inválido.');const p={recipient_name:b.recipient_name??null,recipient_email:b.recipient_email,is_active:b.is_active??true,updated_at:new Date().toISOString()};return rid?(await this.s.update<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`,p))[0]:(await this.s.insert<any[]>('report_recipients',{...p,tenant_id:t,report_definition_id:id,user_id:u}))[0]}
 async deleteRecipient(t:string,id:string,u:string,rid:string){return (await this.s.delete<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`))[0]}
 async schedule(t:string,id:string,u:string,b?:any){await this.report(t,id);const old=(await this.s.select<any[]>('report_schedules',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0];if(!b)return old??null;const frequency=b.frequency??'daily';if(!['daily','weekly','monthly'].includes(frequency))throw new BadRequestException('Periodicidade inválida.');const dayOfWeek=frequency==='weekly'?(b.day_of_week??'monday'):null, dayOfMonth=frequency==='monthly'?Number(b.day_of_month):null;if(frequency==='weekly'&&!['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].includes(dayOfWeek))throw new BadRequestException('Dia da semana inválido.');if(frequency==='monthly'&&(!Number.isInteger(dayOfMonth)||(dayOfMonth??0)<1||(dayOfMonth??0)>31))throw new BadRequestException('Dia do mês deve estar entre 1 e 31.');if(b.time_of_day&& !/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time_of_day))throw new BadRequestException('Horário deve estar no formato HH:mm.');const p={tenant_id:t,report_definition_id:id,user_id:u,enabled:!!b.enabled,frequency,day_of_week:dayOfWeek,day_of_month:dayOfMonth,time_of_day:b.time_of_day??null,timezone:b.timezone??'America/Sao_Paulo',updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_schedules',`id=eq.${old.id}&tenant_id=eq.${t}`,p))[0]:(await this.s.insert<any[]>('report_schedules',p))[0]}
 async preview(t:string,id:string,u:string,b:any){const report=await this.report(t,id),d=await this.detail(t,id,u);if(!d.sections.length)throw new BadRequestException('Adicione ao menos um bloco ao relatório antes de gerar o preview.');if(!d.blocks.length)throw new BadRequestException('Adicione ao menos um indicador antes de gerar o preview.');const overrides=this.validOverrides(d.filters,b.filters_override??{});const effective=d.filters.map((f:any)=>({key:f.filter_key,type:f.filter_type,value:(f.locked||!f.user_can_override)?this.filterValue(f.filter_type,f.default_value):(Object.hasOwn(overrides,f.filter_key)?overrides[f.filter_key]:this.filterValue(f.filter_type,f.default_value))}));const global_filters=this.toGlobalFilters(effective),results:any={};for(const x of d.blocks){try{results[x.id]=x.source_type==='native_indicator'?await this.native.preview(t,x.source_id,u,false,{global_filters}):await this.custom.previewSaved(t,x.source_id,u,{global_filters})}catch(e:any){const sec=d.sections.find((s:any)=>s.id===x.report_section_id);throw new BadRequestException(`Não foi possível gerar o bloco ${sec?.title??x.title}: ${e.message}`)}}const generated_at=new Date().toISOString();const render_snapshot={report:{id:report.id,name:report.name,description:report.description,module_key:report.module_key,generated_at},filters:effective,sections:d.sections.map((s:any)=>({...s,blocks:s.blocks.map((x:any)=>({...x,data:results[x.id]}))})),ai:{enabled:false}};const input=this.reportSnapshot(render_snapshot,results);const [job]=await this.s.insert<any[]>('report_jobs',{tenant_id:t,report_definition_id:id,requested_by:u,trigger_type:'manual',status:'completed',filters_snapshot:effective,data_snapshot:results,render_snapshot,ai_snapshot:null,started_at:generated_at,finished_at:generated_at});let ai_snapshot:any={enabled:false,reason:'Narrativa por IA não está habilitada neste relatório.'};if(report.ai_enabled){const agent=await this.activeAgent(t);if(!agent)ai_snapshot={enabled:false,reason:'Nenhum agente de relatório ativo foi configurado.'};else ai_snapshot=await this.narrative(t,id,u,agent,input,job.id);}await this.s.update('report_jobs',`tenant_id=eq.${t}&id=eq.${job.id}`,{ai_snapshot});return{job:{...job,ai_snapshot},render_snapshot:{...render_snapshot,ai:ai_snapshot}}}
 async jobs(t:string,id:string){return{data:await this.s.select<any[]>('report_jobs',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=created_at.desc&limit=20`)}}
 async indicatorLibrary(t:string,moduleKey?:string){const key=moduleKey?moduleMap[moduleKey]:undefined;const [n,c]=await Promise.all([this.native.list(t),this.custom.list(t)]);const item=(x:any,source_type:'native_indicator'|'custom_indicator')=>{const v=this.compatibility(x);return{id:source_type==='native_indicator'?x.indicator_key:x.id,source_type,name:x.name,description:x.description,module_key:x.module_key,module_label:moduleLabels[x.module_key],result_shape:v.result_shape,allowed_visual_types:v.allowed_visual_types,recommended_visual_type:v.recommended_visual_type,availability:source_type==='native_indicator'?x.availability?.status:(x.status==='active'&&x.available_for_dashboard?'available':'unavailable'),reason:source_type==='native_indicator'?x.availability?.reason:(x.status!=='active'?'Indicador inativo':undefined)}};return{data:[...n.data.map((x:any)=>item(x,'native_indicator')),...(c.data as any[]).map(x=>item(x,'custom_indicator'))].filter((x:any)=>!key||x.module_key===key)}}
 async nativeFilters(){return{data:Object.entries(filterTypes).map(([key,filter_type])=>({key,label:labels[key],filter_type}))}}
 async aiQuestion(t:string,id:string,u:string,b:any){await this.report(t,id);const question=typeof b.question==='string'?b.question.trim().slice(0,1000):'';if(!question)throw new BadRequestException('Pergunta obrigatória.');const job=await this.job(t,id,String(b.job_id||''));const agent=await this.activeAgent(t);if(!agent)return {answer:'Nenhum agente de relatório ativo foi configurado.',related_sections:[],limitations:['O relatório permanece disponível sem narrativa por IA.'],dry_run:true};const snapshot=this.reportSnapshot(job.render_snapshot,job.data_snapshot);try{const result=await this.gateway.runAgent({tenantId:t,agent,runType:'report_narrative',triggerType:'manual',context:'report',inputSnapshot:{...snapshot,question},messages:[{role:'user',content:question}],responseSchema:this.questionSchema()});if(!this.validQuestion(result.output_json,snapshot))throw new Error('Resposta de pergunta inválida.');const [run]=await this.s.insert<any[]>('ai_runs',{tenant_id:t,agent_id:agent.id,run_type:'report_narrative',trigger_type:'manual',status:'completed',input_snapshot:snapshot,output_json:result.output_json,model_provider:result.model_provider,model_name:result.model_name,...result.usage,requested_by:u,started_at:new Date().toISOString(),finished_at:new Date().toISOString()});await this.s.insert('ai_usage_logs',{tenant_id:t,agent_id:agent.id,ai_run_id:run.id,provider:result.model_provider,model_name:result.model_name,...result.usage});return {...(result.output_json as Record<string,unknown>),ai_run_id:run.id,dry_run:result.dry_run};}catch{throw new BadRequestException('Não foi possível responder sem afetar o relatório.');}}
 async aiSpeech(t:string,id:string,u:string,b:any){await this.job(t,id,String(b.job_id||''));const text=typeof b.text==='string'?b.text.replace(/<[^>]*>/g,'').trim().slice(0,4000):'';if(!text)throw new BadRequestException('Texto obrigatório para resposta por voz.');const result=await this.gateway.speech(text);if(!result.dry_run){const agent=await this.activeAgent(t);await this.s.insert('ai_usage_logs',{tenant_id:t,agent_id:agent?.id??null,ai_run_id:typeof b.ai_run_id==='string'?b.ai_run_id:null,provider:'openai',model_name:result.model_name,input_tokens:0,output_tokens:0,total_tokens:0,estimated_cost_cents:null});}return result;}
 async aiRealtimeSession(t:string,id:string,u:string,b:any){if(!this.entitlement.dashboardRealtimeVoice().enabled)return {enabled:false,reason:'Voz ao vivo não está habilitada neste ambiente.'};const job=await this.job(t,id,String(b.job_id||'')),agent=await this.activeAgent(t);if(!agent)throw new BadRequestException('Nenhum agente de relatório ativo foi configurado.');if(!process.env.OPENAI_API_KEY)throw new BadRequestException('Voz ao vivo indisponível neste ambiente.');const snapshot=this.reportSnapshot(job.render_snapshot,job.data_snapshot),model=process.env.OPENAI_REALTIME_MODEL||'gpt-realtime';const instructions='Responda em português do Brasil somente sobre este relatório e snapshot tratado. Não invente dados, não acesse banco, não use SQL, não consulte fontes externas, não recalcule indicadores e não altere dados. Se estiver fora do relatório, informe isso amigavelmente. Snapshot: '+JSON.stringify(snapshot);try{const response=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({session:{type:'realtime',model,instructions}})});if(!response.ok)throw new Error();const data:any=await response.json(),secret=data?.value??data?.client_secret?.value??data?.client_secret;if(typeof secret!=='string')throw new Error();const [run]=await this.s.insert<any[]>('ai_runs',{tenant_id:t,agent_id:agent.id,run_type:'report_narrative',trigger_type:'manual',status:'completed',input_snapshot:snapshot,output_json:{realtime_session_started:true},model_provider:'openai',model_name:model,requested_by:u,started_at:new Date().toISOString(),finished_at:new Date().toISOString()});return{enabled:true,session:{client_secret:secret,expires_at:data?.expires_at??data?.client_secret?.expires_at??null,model},ai_run_id:run.id};}catch{throw new BadRequestException('Não foi possível iniciar a voz ao vivo. Tente novamente.')}}
 private async activeAgent(t:string){return (await this.s.select<any[]>('ai_agents',`tenant_id=eq.${t}&agent_type=eq.report_writer&status=eq.active&deleted_at=is.null&order=updated_at.desc&limit=1`))[0]}
 private async job(t:string,id:string,jid:string){if(!jid)throw new BadRequestException('job_id obrigatório.');const row=(await this.s.select<any[]>('report_jobs',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${jid}`))[0];if(!row)throw new NotFoundException('Geração do relatório não encontrada.');return row}
 private reportSnapshot(render:any,data:any){return {report:render.report,filters:render.filters,sections:(render.sections??[]).map((s:any)=>({id:s.id,title:s.title,description:s.description,ai_enabled:s.ai_enabled!==false,blocks:(s.blocks??[]).map((x:any)=>({id:x.id,title:x.title,visual_type:x.visual_type,result_shape:this.resultShape(data?.[x.id],x.visual_type),data_summary:{result_available:data?.[x.id]!==undefined},deterministic_summary:this.summarizer.summarize(data?.[x.id],this.resultShape(data?.[x.id],x.visual_type))}))})),rules:{language:'pt-BR',use_only_provided_data:true,do_not_access_database:true,do_not_use_sql:true,do_not_invent_data:true,do_not_calculate_official_indicators:true}}}
 private resultShape(result:any,visual:string){const shape=result?.result_shape??result?.shape;return ['scalar','table','matrix','distribution','ranking','timeseries'].includes(shape)?shape:visual==='kpi'?'scalar':visual==='matrix'?'matrix':visual==='line'?'timeseries':visual==='pie'?'distribution':visual==='bar'?'ranking':'table'}
 private async narrative(t:string,id:string,u:string,agent:any,snapshot:any,jobId:string){const started_at=new Date().toISOString();try{const result=await this.gateway.runAgent({tenantId:t,agent,runType:'report_narrative',triggerType:'report_generate',context:'report',inputSnapshot:snapshot,responseSchema:this.narrativeSchema()});if(!this.validNarrative(result.output_json,snapshot))throw new Error('Narrativa inválida.');const [run]=await this.s.insert<any[]>('ai_runs',{tenant_id:t,agent_id:agent.id,run_type:'report_narrative',trigger_type:'report_generate',status:'completed',input_snapshot:snapshot,output_json:result.output_json,model_provider:result.model_provider,model_name:result.model_name,...result.usage,requested_by:u,started_at,finished_at:new Date().toISOString()});await this.s.insert('ai_usage_logs',{tenant_id:t,agent_id:agent.id,ai_run_id:run.id,provider:result.model_provider,model_name:result.model_name,...result.usage});return {enabled:true,dry_run:result.dry_run,ai_run_id:run.id,...(result.output_json as Record<string,unknown>)};}catch(error){const [run]=await this.s.insert<any[]>('ai_runs',{tenant_id:t,agent_id:agent.id,run_type:'report_narrative',trigger_type:'report_generate',status:'failed',input_snapshot:snapshot,error_message:error instanceof Error?error.message:'Falha na narrativa.',requested_by:u,started_at,finished_at:new Date().toISOString()});return {enabled:true,fallback:true,ai_run_id:run.id,error:'Não foi possível gerar a narrativa por IA.'}}}
 private validNarrative(x:any,s:any){const keys=['opening','executive_summary','sections','closing','next_steps','data_quality_notes'];const ids=new Set((s.sections??[]).map((v:any)=>v.id));return !!x&&keys.every(k=>x[k]!==undefined)&&typeof x.opening==='string'&&typeof x.executive_summary==='string'&&typeof x.closing==='string'&&Array.isArray(x.next_steps)&&Array.isArray(x.data_quality_notes)&&Array.isArray(x.sections)&&x.sections.every((v:any)=>ids.has(v.section_id)&&typeof v.section_title==='string'&&typeof v.analysis==='string'&&Array.isArray(v.highlights)&&Array.isArray(v.attention_points))}
 private validQuestion(x:any,s:any){const ids=new Set((s.sections??[]).map((v:any)=>v.id));return !!x&&typeof x.answer==='string'&&Array.isArray(x.related_sections)&&x.related_sections.every((id:string)=>ids.has(id))&&Array.isArray(x.limitations)}
 private narrativeSchema(){return {type:'object',additionalProperties:false,required:['opening','executive_summary','sections','closing','next_steps','data_quality_notes'],properties:{opening:{type:'string'},executive_summary:{type:'string'},sections:{type:'array',items:{type:'object',additionalProperties:false,required:['section_id','section_title','analysis','highlights','attention_points'],properties:{section_id:{type:'string'},section_title:{type:'string'},analysis:{type:'string'},highlights:{type:'array',items:{type:'string'}},attention_points:{type:'array',items:{type:'string'}}}}},closing:{type:'string'},next_steps:{type:'array',items:{type:'string'}},data_quality_notes:{type:'array',items:{type:'string'}}}}}
 private questionSchema(){return {type:'object',additionalProperties:false,required:['answer','related_sections','limitations'],properties:{answer:{type:'string'},related_sections:{type:'array',items:{type:'string'}},limitations:{type:'array',items:{type:'string'}}}}}

 private compatibility(x:Record<string,unknown>){return visualCompatibility(x)}
 private validBlock(type:any,visual:any,i:any){if(!visuals.has(visual)||type!==visual||!i.allowed_visual_types.includes(visual))throw new BadRequestException('Tipo visual incompatível com o indicador.')}
 private async module(t:string,k:any){const normalized=moduleMap[String(k??'')];if(!normalized)throw new BadRequestException('Módulo inválido.');const active=await this.modules(t);if(!active.data.some((x:any)=>x.key===normalized))throw new BadRequestException('Módulo não está ativo para este tenant.');return normalized}
 private async report(t:string,id:string){const r=await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}&status=neq.archived`);if(!r[0])throw new NotFoundException('Relatório não encontrado.');return r[0]}
 private async section(t:string,id:string,sid:string){const r=await this.s.select<any[]>('report_sections',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${sid}`);if(!r[0])throw new NotFoundException('Bloco não encontrado.');return r[0]}
 private async item(table:string,t:string,id:string,x:string){const r=await this.s.select<any[]>(table,`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${x}`);if(!r[0])throw new NotFoundException('Item não encontrado.');return r[0]}
 private async limit(t:string){const r=await this.s.select<any[]>('subscription_limits',`tenant_id=eq.${t}&key=eq.reports.max_definitions&select=limit_value&limit=1`);return r[0]?Number(r[0].limit_value):null}
 private validFilter(b:any){if(!filterTypes[b.filter_key]||filterTypes[b.filter_key]!==b.filter_type)throw new BadRequestException('Filtro nativo inválido.')}
 private filterValue(type:string,v:any){if(type==='date_range')return{from:v?.from??'',to:v?.to??''};const values=Array.isArray(v)?v:v?.values;if(!Array.isArray(values))throw new BadRequestException('Filtro de múltipla seleção inválido.');return{values}}
 private async validIndicator(t:string,type:any,id:any,module:string){if(!['native_indicator','custom_indicator'].includes(type)||!id)throw new BadRequestException('Indicador obrigatório e inválido.');const d:any=type==='native_indicator'?await this.native.detail(t,id):await this.custom.detail(t,id);if(d.module_key && d.module_key!==module)throw new BadRequestException('Indicador incompatível com o módulo do relatório.');if(type==='native_indicator'&&!['available','partial'].includes(d.availability?.status))throw new BadRequestException('Indicador nativo indisponível.');if(type==='custom_indicator'&&(d.status!=='active'||!d.available_for_dashboard))throw new BadRequestException('Indicador personalizado indisponível.');return this.compatibility(d)}
 private toGlobalFilters(items:any[]){return items.flatMap<any>(f=>{const v:any=f.value??{};if(f.type==='multi_select'){const values=v.values??[];return values.length?[{field_key:f.key,operator:values.length===1?'igual a':'em',value:values[0],values}]:[]}const from=v.from??'',to=v.to??'';return from||to?[{field_key:f.key,operator:from&&to?'entre':from?'maior que':'menor que',value:from||to,value_to:to||null}]:[]})}
 private validOverrides(fs:any[],overrides:any){if(!overrides||typeof overrides!=='object'||Array.isArray(overrides))throw new BadRequestException('Filtros inválidos.');const clean:any={};for(const key of Object.keys(overrides)){const f=fs.find(x=>x.filter_key===key);if(!f||!f.user_can_override||f.locked)throw new BadRequestException('Filtro não pode ser alterado pelo cliente.');clean[key]=this.filterValue(f.filter_type,overrides[key])}return clean}
}
