import {Body,Controller,Delete,Get,Param,Patch,Post,Req,UseGuards} from '@nestjs/common';import {AuthGuard,AuthenticatedRequest} from '../auth/auth.guard';import {PermissionsGuard} from '../rbac/permissions.guard';import {RequirePermission} from '../rbac/require-permission.decorator';import {ReportsService} from './reports.service';
@Controller('tenants/:tenantId/reports') @UseGuards(AuthGuard,PermissionsGuard) export class ReportsController{constructor(private s:ReportsService){}
@Get() @RequirePermission('reports.view') list(@Param('tenantId')t:string){return this.s.list(t)} @Get('setup') @RequirePermission('reports.configure') setup(@Param('tenantId')t:string){return this.s.list(t,true)} @Get('indicator-library') @RequirePermission(['reports.view','reports.configure']) library(@Param('tenantId')t:string){return this.s.indicatorLibrary(t)} @Get('native-filters') @RequirePermission(['reports.view','reports.configure']) nativeFilters(){return this.s.nativeFilters()} @Post() @RequirePermission('reports.configure') create(@Param('tenantId')t:string,@Req()r:AuthenticatedRequest,@Body()b:any){return this.s.create(t,r.user.id,b)}
@Get(':id') @RequirePermission(['reports.view','reports.configure']) detail(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest){return this.s.detail(t,id,r.user.id)} @Patch(':id') @RequirePermission('reports.configure') update(@Param('tenantId')t:string,@Param('id')id:string,@Body()b:any){return this.s.update(t,id,b)} @Delete(':id') @RequirePermission('reports.configure') archive(@Param('tenantId')t:string,@Param('id')id:string){return this.s.archive(t,id)}
@Get(':id/blocks') @RequirePermission('reports.view') blocks(@Param('tenantId')t:string,@Param('id')id:string){return this.s.blocks(t,id)} @Post(':id/blocks') @RequirePermission('reports.manage_structure') addBlock(@Param('tenantId')t:string,@Param('id')id:string,@Body()b:any){return this.s.addBlock(t,id,b)} @Patch(':id/blocks/:bid') @RequirePermission('reports.manage_structure') updateBlock(@Param('tenantId')t:string,@Param('id')id:string,@Param('bid')x:string,@Body()b:any){return this.s.updateBlock(t,id,x,b)} @Delete(':id/blocks/:bid') @RequirePermission('reports.manage_structure') deleteBlock(@Param('tenantId')t:string,@Param('id')id:string,@Param('bid')x:string){return this.s.deleteBlock(t,id,x)}
@Post(':id/filters') @RequirePermission('reports.manage_structure') addFilter(@Param('tenantId')t:string,@Param('id')id:string,@Body()b:any){return this.s.addFilter(t,id,b)} @Patch(':id/filters/:fid') @RequirePermission('reports.manage_structure') updateFilter(@Param('tenantId')t:string,@Param('id')id:string,@Param('fid')x:string,@Body()b:any){return this.s.updateFilter(t,id,x,b)} @Delete(':id/filters/:fid') @RequirePermission('reports.manage_structure') deleteFilter(@Param('tenantId')t:string,@Param('id')id:string,@Param('fid')x:string){return this.s.deleteFilter(t,id,x)}
@Get(':id/settings') @RequirePermission('reports.view') settings(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest){return this.s.settings(t,id,r.user.id)} @Patch(':id/settings') @RequirePermission('reports.view') saveSettings(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest,@Body()b:any){return this.s.saveSettings(t,id,r.user.id,b)}
@Get(':id/recipients') @RequirePermission('reports.manage_recipients') recipients(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest){return this.s.recipients(t,id,r.user.id)} @Post(':id/recipients') @RequirePermission('reports.manage_recipients') recipient(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest,@Body()b:any){return this.s.recipient(t,id,r.user.id,b)} @Patch(':id/recipients/:rid') @RequirePermission('reports.manage_recipients') recipientUpdate(@Param('tenantId')t:string,@Param('id')id:string,@Param('rid')x:string,@Req()r:AuthenticatedRequest,@Body()b:any){return this.s.recipient(t,id,r.user.id,b,x)} @Delete(':id/recipients/:rid') @RequirePermission('reports.manage_recipients') recipientDelete(@Param('tenantId')t:string,@Param('id')id:string,@Param('rid')x:string,@Req()r:AuthenticatedRequest){return this.s.deleteRecipient(t,id,r.user.id,x)}
@Get(':id/schedule') @RequirePermission('reports.manage_schedule') schedule(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest){return this.s.schedule(t,id,r.user.id)} @Patch(':id/schedule') @RequirePermission('reports.manage_schedule') saveSchedule(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest,@Body()b:any){return this.s.schedule(t,id,r.user.id,b)} @Get(':id/jobs') @RequirePermission('reports.view_jobs') jobs(@Param('tenantId')t:string,@Param('id')id:string){return this.s.jobs(t,id)} @Post(':id/generate-preview') @RequirePermission('reports.generate') preview(@Param('tenantId')t:string,@Param('id')id:string,@Req()r:AuthenticatedRequest,@Body()b:any={}){return this.s.preview(t,id,r.user.id,b)} }
