import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { NativeIndicatorsService } from '../native-indicators/native-indicators.service';
import { CustomIndicatorsService } from '../custom-indicators/custom-indicators.service';
const filters:Record<string,'date_range'|'multi_select'>={issued_at:'date_range',expected_date:'date_range',completed_at:'date_range',updated_at:'date_range',customer_name:'multi_select',shipper_name:'multi_select',recipient_name:'multi_select',origin_city:'multi_select',origin_state:'multi_select',destination_city:'multi_select',destination_state:'multi_select',status:'multi_select',document_type:'multi_select',driver_name:'multi_select',vehicle_plate:'multi_select'};
const visuals=new Set(['kpi','table','matrix','bar','pie','line']); const statuses=new Set(['draft','active','archived']);
@Injectable() export class ReportsService {
 constructor(private s:SupabaseService,private native:NativeIndicatorsService,private custom:CustomIndicatorsService){}
 async list(t:string,configure=false){const q=`tenant_id=eq.${t}&status=neq.archived${configure?'':'&status=eq.active'}&order=updated_at.desc`; const data=await this.s.select<any[]>('report_definitions',q); return {data,limit:await this.limit(t)};}
 async create(t:string,u:string,b:any){const limit=await this.limit(t); const count=(await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&status=neq.archived&select=id`)).length; if(limit!==null&&count>=limit) throw new BadRequestException('Limite de relatórios do plano atingido.'); if(!String(b.name||'').trim()||!String(b.module_key||'').trim()) throw new BadRequestException('Nome e módulo são obrigatórios.'); return (await this.s.insert<any[]>('report_definitions',{tenant_id:t,name:b.name.trim(),description:b.description??null,module_key:b.module_key,created_by:u}))[0];}
 async detail(t:string,id:string,u?:string){const report=await this.report(t,id); const [blocks,reportFilters,settings]=await Promise.all([this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=created_at.asc`),this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=position.asc`),u?this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`):[]]); return {...report,blocks,filters:reportFilters,settings:settings[0]??null};}
 async update(t:string,id:string,b:any){await this.report(t,id); const p:any={updated_at:new Date().toISOString()}; for(const k of ['name','description','module_key','ai_enabled'])if(k in b)p[k]=b[k]; if('status'in b){if(!statuses.has(b.status))throw new BadRequestException('Status inválido.');p.status=b.status;} return (await this.s.update<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}`,p))[0];}
 async archive(t:string,id:string){await this.report(t,id);return (await this.s.update<any[]>('report_definitions',`tenant_id=eq.&id=eq.`,{status:'archived',deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}))[0];}
 async blocks(t:string,id:string){await this.report(t,id);return {data:await this.s.select<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=created_at.asc`)};}
 async addBlock(t:string,id:string,b:any){const report=await this.report(t,id);await this.validIndicator(t,b.source_type,b.source_id,report.module_key); if(!visuals.has(b.visual_type)||!visuals.has(b.block_type))throw new BadRequestException('Tipo de bloco ou visual inválido.'); return (await this.s.insert<any[]>('report_blocks',{tenant_id:t,report_definition_id:id,block_key:String(b.block_key||Date.now().toString()),block_type:b.block_type,title:String(b.title||'Bloco'),source_type:b.source_type,source_id:b.source_id,visual_type:b.visual_type,position:b.position??{},config:b.config??{}}))[0];}
 async updateBlock(t:string,id:string,bid:string,b:any){const current=await this.item('report_blocks',t,id,bid); const report=await this.report(t,id); if(b.source_type||b.source_id)await this.validIndicator(t,b.source_type??current.source_type,b.source_id??current.source_id,report.module_key); if(b.visual_type&&!visuals.has(b.visual_type))throw new BadRequestException('Tipo visual inválido.'); const p:any={updated_at:new Date().toISOString()}; for(const k of ['title','block_key','block_type','source_type','source_id','visual_type','position','config'])if(k in b)p[k]=b[k]; return (await this.s.update<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`,p))[0];}
 async deleteBlock(t:string,id:string,bid:string){await this.item('report_blocks',t,id,bid);return (await this.s.delete<any[]>('report_blocks',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${bid}`))[0];}
 async addFilter(t:string,id:string,b:any){await this.report(t,id);this.validFilter(b);return (await this.s.insert<any[]>('report_filters',{tenant_id:t,report_definition_id:id,...b,default_value:b.default_value??{},position:Number(b.position??0)}))[0];}
 async updateFilter(t:string,id:string,fid:string,b:any){await this.item('report_filters',t,id,fid);this.validFilter(b,false); const p:any={updated_at:new Date().toISOString()}; for(const k of ['filter_key','label','filter_type','default_value','locked','user_can_override','required','position'])if(k in b)p[k]=b[k];return(await this.s.update<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${fid}`,p))[0];}
 async deleteFilter(t:string,id:string,fid:string){await this.item('report_filters',t,id,fid);return(await this.s.delete<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${fid}`))[0];}
 async settings(t:string,id:string,u:string){await this.report(t,id);return (await this.s.select<any[]>('report_user_settings',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0]??null;}
 async saveSettings(t:string,id:string,u:string,b:any){const fs=await this.s.select<any[]>('report_filters',`tenant_id=eq.${t}&report_definition_id=eq.${id}`);const o=b.filters_override??{};for(const key of Object.keys(o)){const f=fs.find(x=>x.filter_key===key);if(!f||!f.user_can_override||f.locked)throw new BadRequestException('Filtro não pode ser alterado pelo cliente.');}const old=await this.settings(t,id,u);const p={tenant_id:t,report_definition_id:id,user_id:u,filters_override:o,preferred_format:'preview',send_enabled:false,updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_user_settings',`id=eq.${old.id}`,p))[0]:(await this.s.insert<any[]>('report_user_settings',p))[0];}
 async recipients(t:string,id:string,u:string){return {data:await this.s.select<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`)}}
 async recipient(t:string,id:string,u:string,b:any,rid?:string){if(!/^\S+@\S+\.\S+$/.test(String(b.recipient_email??'')))throw new BadRequestException('E-mail inválido.');const p={recipient_name:b.recipient_name??null,recipient_email:b.recipient_email,is_active:b.is_active??true,updated_at:new Date().toISOString()};return rid?(await this.s.update<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`,p))[0]:(await this.s.insert<any[]>('report_recipients',{...p,tenant_id:t,report_definition_id:id,user_id:u}))[0]}
 async deleteRecipient(t:string,id:string,u:string,rid:string){return(await this.s.delete<any[]>('report_recipients',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}&id=eq.${rid}`))[0]}
 async schedule(t:string,id:string,u:string,b?:any){const old=(await this.s.select<any[]>('report_schedules',`tenant_id=eq.${t}&report_definition_id=eq.${id}&user_id=eq.${u}`))[0];if(!b)return old??null;if(!['daily','weekly','monthly'].includes(b.frequency??'daily'))throw new BadRequestException('Periodicidade inválida.');const p={tenant_id:t,report_definition_id:id,user_id:u,enabled:!!b.enabled,frequency:b.frequency??'daily',day_of_week:b.day_of_week??null,day_of_month:b.day_of_month??null,time_of_day:b.time_of_day??null,timezone:b.timezone??'America/Sao_Paulo',updated_at:new Date().toISOString()};return old?(await this.s.update<any[]>('report_schedules',`id=eq.${old.id}`,p))[0]:(await this.s.insert<any[]>('report_schedules',p))[0]}
 async preview(t:string,id:string,u:string,b:any){const report=await this.report(t,id);if(report.status!=='active')throw new BadRequestException('Apenas relatórios ativos podem ser gerados.');const d=await this.detail(t,id,u);const overrides=b.filters_override??{};const effective=d.filters.map((f:any)=>({key:f.filter_key,value:(f.locked||!f.user_can_override)?f.default_value:(Object.hasOwn(overrides,f.filter_key)?overrides[f.filter_key]:f.default_value),type:f.filter_type}));const global_filters=this.toGlobalFilters(effective);const results=await Promise.all(d.blocks.map(async(x:any)=>({block_id:x.id,result:x.source_type==='native_indicator'?await this.native.preview(t,x.source_id,u,false,{global_filters}):await this.custom.previewSaved(t,x.source_id,u,{global_filters})})));const render_snapshot={title:report.name,blocks:d.blocks.map((x:any,i:number)=>({...x,data:results[i].result,placeholder:['ai_summary','ai_section_note'].includes(x.block_type)?'Análise automática será adicionada na próxima etapa.':undefined}))};const job=(await this.s.insert<any[]>('report_jobs',{tenant_id:t,report_definition_id:id,requested_by:u,trigger_type:'manual',status:'completed',filters_snapshot:effective,data_snapshot:results,ai_snapshot:null,render_snapshot,started_at:new Date().toISOString(),finished_at:new Date().toISOString()}))[0];return {job,render_snapshot};}
 async jobs(t:string,id:string){await this.report(t,id);return {data:await this.s.select<any[]>('report_jobs',`tenant_id=eq.${t}&report_definition_id=eq.${id}&order=created_at.desc&limit=20`)};}
 async indicatorLibrary(t:string){const [n,c]=await Promise.all([this.native.list(t),this.custom.list(t)]);const customs=c.data as any[];return {data:[...n.data.filter((x:any)=>['available','partial'].includes(x.availability?.status)).map((x:any)=>({id:x.indicator_key,source_type:'native_indicator',name:x.name,module_key:x.module_key,allowed_visual_types:this.visuals(x)})),...customs.filter(x=>x.status==='active'&&x.available_for_dashboard).map(x=>({id:x.id,source_type:'custom_indicator',name:x.name,module_key:x.module_key,allowed_visual_types:this.visuals(x)}))]};}
 async nativeFilters(){return {data:Object.entries(filters).map(([key,filter_type])=>({key,label:key.replaceAll('_',' '),filter_type}))};}
 private visuals(x:any){const v=String(x.visualization_type??x.calculation_type??x.operation_key??'').toLowerCase();if(/latest|table/.test(v))return ['table'];if(/matrix|pivot/.test(v))return ['matrix','table'];if(/ranking/.test(v))return ['bar','table'];if(/distribution/.test(v))return ['bar','pie','table'];if(/series|period|line/.test(v))return ['line','bar','table'];return ['kpi'];}
 private toGlobalFilters(items:any[]):any[]{return items.flatMap<any>(f=>{const v=f.value??{};if(f.type==='multi_select'){const values=Array.isArray(v)?v:(v.values??[]);return values.length?[{field_key:f.key,operator:values.length===1?'igual a':'em',value:values[0],values}]:[]} ;const from=v.from??v.start??'',to=v.to??v.end??'';return from||to?[{field_key:f.key,operator:from&&to?'entre':from?'maior que':'menor que',value:from||to,value_to:to||null}]:[]})}
 private async report(t:string,id:string){const r=await this.s.select<any[]>('report_definitions',`tenant_id=eq.${t}&id=eq.${id}&status=neq.archived`);if(!r[0])throw new NotFoundException('Relatório não encontrado.');return r[0]}
 private async item(table:string,t:string,id:string,item:string){const r=await this.s.select<any[]>(table,`tenant_id=eq.${t}&report_definition_id=eq.${id}&id=eq.${item}`);if(!r[0])throw new NotFoundException('Item não encontrado.');return r[0]}
 private async limit(t:string){const r=await this.s.select<any[]>('subscription_limits',`tenant_id=eq.${t}&key=eq.reports.max_definitions&select=limit_value&limit=1`);return r[0]?Number(r[0].limit_value):null}
 private validFilter(b:any,required=true){const key=b.filter_key;if((required||key!==undefined)&&(!filters[key]||filters[key]!==b.filter_type))throw new BadRequestException('Filtro nativo inválido.');if(b.default_value!==undefined&&typeof b.default_value!=='object')throw new BadRequestException('Valor padrão inválido.')}
 private async validIndicator(t:string,type:any,id:any,moduleKey?:string){if(!['native_indicator','custom_indicator'].includes(type)||!id)throw new BadRequestException('Indicador obrigatório e inválido.');if(type==='native_indicator'){const d:any=await this.native.detail(t,id);if(!['available','partial'].includes(d.availability?.status))throw new BadRequestException('Indicador nativo indisponível.')}else{const d:any=await this.custom.detail(t,id);if(d.status!=='active'||!d.available_for_dashboard)throw new BadRequestException('Indicador personalizado indisponível.');if(moduleKey&&d.module_key&&d.module_key!==moduleKey)throw new BadRequestException('Indicador incompatível com o módulo do relatório.')}}
}
