import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { NativeIndicatorsService } from '../native-indicators/native-indicators.service';
import { visualCompatibility } from '../shared/visual-compatibility';
import { CustomIndicatorsService } from '../custom-indicators/custom-indicators.service';

type IndicatorSource = 'native' | 'custom';
type VisualType = 'kpi' | 'table' | 'matrix' | 'bar' | 'pie' | 'line';
type ResultShape = 'scalar' | 'table' | 'matrix' | 'distribution' | 'ranking' | 'timeseries' | 'empty';
type Compatibility = { result_shape: ResultShape; allowed_visual_types: VisualType[]; recommended_visual_type: VisualType; reason: string };
type Widget = { id:string; tenant_id:string; dashboard_id:string; indicator_source:IndicatorSource; indicator_id:string; title:string; visual_type:VisualType; position:{x?:number;y?:number;w?:number;h?:number}; properties:Record<string,unknown> };
type DashboardSnapshot = { widgets?: Widget[]; layout_config?: Record<string, unknown> };
type NativeFilter = { key:string; label:string; group:'Período'|'Entidades'|'Localidade'|'Operação'; type:'date_range'|'multi_select'; field_key:string; placeholder:string };
const nativeFilters: NativeFilter[] = [
  {key:'issued_at',label:'Data de emissão',group:'Período',type:'date_range',field_key:'issued_at',placeholder:'Selecione o período'},
  {key:'expected_date',label:'Data prevista',group:'Período',type:'date_range',field_key:'expected_date',placeholder:'Selecione o período'},
  {key:'completed_at',label:'Data de entrega',group:'Período',type:'date_range',field_key:'completed_at',placeholder:'Selecione o período'},
  {key:'updated_at',label:'Data de atualização',group:'Período',type:'date_range',field_key:'updated_at',placeholder:'Selecione o período'},
  {key:'customer_name',label:'Cliente',group:'Entidades',type:'multi_select',field_key:'customer_name',placeholder:'Selecione clientes'},
  {key:'shipper_name',label:'Embarcador',group:'Entidades',type:'multi_select',field_key:'shipper_name',placeholder:'Selecione embarcadores'},
  {key:'recipient_name',label:'Destinatário',group:'Entidades',type:'multi_select',field_key:'recipient_name',placeholder:'Selecione destinatários'},
  {key:'origin_city',label:'Cidade origem',group:'Localidade',type:'multi_select',field_key:'origin_city',placeholder:'Selecione cidades'},
  {key:'origin_state',label:'UF origem',group:'Localidade',type:'multi_select',field_key:'origin_state',placeholder:'Selecione UFs'},
  {key:'destination_city',label:'Cidade destino',group:'Localidade',type:'multi_select',field_key:'destination_city',placeholder:'Selecione cidades'},
  {key:'destination_state',label:'UF destino',group:'Localidade',type:'multi_select',field_key:'destination_state',placeholder:'Selecione UFs'},
  {key:'status',label:'Status',group:'Operação',type:'multi_select',field_key:'status',placeholder:'Selecione status'},
  {key:'document_type',label:'Tipo de documento',group:'Operação',type:'multi_select',field_key:'document_type',placeholder:'Selecione tipos'},
  {key:'driver_name',label:'Motorista',group:'Operação',type:'multi_select',field_key:'driver_name',placeholder:'Selecione motoristas'},
  {key:'vehicle_plate',label:'Veículo',group:'Operação',type:'multi_select',field_key:'vehicle_plate',placeholder:'Selecione veículos'},
];
const visualTypes = new Set<VisualType>(['kpi','table','matrix','bar','pie','line']);

@Injectable()
export class DashboardsService{
 constructor(private readonly supabase:SupabaseService,private readonly nativeIndicators:NativeIndicatorsService,private readonly customIndicators:CustomIndicatorsService){}
 async list(tenantId:string){return {data:await this.supabase.select('dashboard_definitions',`tenant_id=eq.${tenantId}&status=neq.archived&order=updated_at.desc`)}}
 async nativeFilters(tenantId:string){ return {data:await Promise.all(nativeFilters.map(async filter=>{ const rows=await this.supabase.select<Record<string,unknown>[]>('operation_records',`select=${filter.field_key}&tenant_id=eq.${tenantId}&deleted_at=is.null&${filter.field_key}=not.is.null&limit=100`); const values=[...new Set(rows.map(row=>String(row[filter.field_key]??'').trim()).filter(Boolean))].slice(0,100); return {...filter,available:values.length>0,reason:values.length?'': 'Filtro não disponível para a base atual.',options:filter.type==='multi_select'?values.map(value=>({label:value,value})):[]}; }))};}
 async indicatorLibrary(tenantId:string){const [natives,customs]=await Promise.all([this.nativeIndicators.list(tenantId),this.customIndicators.list(tenantId)]); return {data:[
   ...natives.data.filter((i:{availability:{status:string}})=>['available','partial'].includes(i.availability.status)).map((i:Record<string,unknown>)=>this.libraryItem('native',i,String(i.indicator_key))),
   ...(customs.data as Record<string,unknown>[]).filter((i)=>i.status==='active'&&i.available_for_dashboard===true).map((i)=>this.libraryItem('custom',i,String(i.id))),
 ]};}
 async create(tenantId:string,userId:string,body:Record<string,unknown>){const title=String(body.title||'Novo dashboard'); const [row]=await this.supabase.insert<unknown[]>('dashboard_definitions',{tenant_id:tenantId,title,description:body.description??null,created_by:userId,layout_config:this.normalizedLayout(body.layout_config)}); return row;}
 async detail(tenantId:string,id:string){const dash=await this.getDashboard(tenantId,id); return {...dash,widgets:(await this.widgets(tenantId,id)).data,filters:(await this.filters(tenantId,id)).data};}
 async update(tenantId:string,id:string,body:Record<string,unknown>){await this.getDashboard(tenantId,id); const payload:Record<string,unknown>={updated_at:new Date().toISOString()}; if(typeof body.title==='string')payload.title=body.title; if(typeof body.description==='string'||body.description===null)payload.description=body.description; if(body.layout_config&&typeof body.layout_config==='object')payload.layout_config=this.normalizedLayout(body.layout_config); const [row]=await this.supabase.update<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,payload); return row;}
 async remove(tenantId:string,id:string){await this.getDashboard(tenantId,id); const [row]=await this.supabase.update<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,{status:'archived',updated_at:new Date().toISOString()}); return row;}
 async widgets(tenantId:string,id:string){await this.getDashboard(tenantId,id); const data=await this.supabase.select<Widget[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&order=created_at.asc`); return {data:data.sort((a,b)=>(a.position?.y??0)-(b.position?.y??0)||(a.position?.x??0)-(b.position?.x??0))};}
 async addWidget(tenantId:string,id:string,userId:string,body:Record<string,unknown>){await this.getDashboard(tenantId,id); const source:IndicatorSource=body.indicator_source==='custom'?'custom':'native'; const visual=String(body.visual_type||'kpi') as VisualType; if(!visualTypes.has(visual)) throw new BadRequestException('Tipo visual inválido.'); const indicatorId=String(body.indicator_id||''); if(!indicatorId) throw new BadRequestException('Indicador obrigatório.'); await this.validateIndicatorAndVisual(tenantId,source,indicatorId,visual); const [row]=await this.supabase.insert<unknown[]>('dashboard_widgets',{tenant_id:tenantId,dashboard_id:id,indicator_source:source,indicator_id:indicatorId,title:String(body.title||'Widget'),visual_type:visual,position:this.normalizedPosition(body.position),properties:body.properties??{},created_by:userId}); return row;}
 async updateWidget(tenantId:string,id:string,widgetId:string,body:Record<string,unknown>){const current=await this.getWidget(tenantId,id,widgetId); const payload:Record<string,unknown>={updated_at:new Date().toISOString()}; if(typeof body.title==='string')payload.title=body.title; if(typeof body.visual_type==='string'){const visual=body.visual_type as VisualType; if(!visualTypes.has(visual)) throw new BadRequestException('Tipo visual inválido.'); if(visual!==current.visual_type) await this.validateIndicatorAndVisual(tenantId,current.indicator_source,current.indicator_id,visual); payload.visual_type=visual;} if(body.position&&typeof body.position==='object')payload.position=this.normalizedPosition(body.position); if(body.properties&&typeof body.properties==='object')payload.properties=body.properties; const [row]=await this.supabase.update<unknown[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`,payload); return row;}
 async deleteWidget(tenantId:string,id:string,widgetId:string){await this.getWidget(tenantId,id,widgetId); const [row]=await this.supabase.delete<unknown[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`); return row;}
 async preview(tenantId:string,id:string,userId:string,body:Record<string,unknown>){const widgets=body.published===true?await this.publishedWidgets(tenantId,id):(await this.widgets(tenantId,id)).data; const filters={global_filters:this.normalizedFilters(body.filters)}; const previews=await Promise.all(widgets.map(async w=>({widget_id:w.id,result:w.indicator_source==='native'?await this.nativeIndicators.preview(tenantId,w.indicator_id,userId,false,filters):await this.customIndicators.previewSaved(tenantId,w.indicator_id,userId,filters)}))); return {data:previews};}
 async publish(tenantId:string,id:string,userId:string){const dash=await this.detail(tenantId,id); const versions=await this.supabase.select<Array<{version_number:number}>>('dashboard_versions',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&select=version_number&order=version_number.desc&limit=1`); const version_number=(versions[0]?.version_number??0)+1; const [version]=await this.supabase.insert<Array<{id:string}>>('dashboard_versions',{tenant_id:tenantId,dashboard_id:id,version_number,snapshot:dash,created_by:userId}); await this.supabase.update('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,{status:'published',published_version_id:version.id,updated_at:new Date().toISOString()}); return version;}
 async published(tenantId:string,id:string){const dash=await this.getDashboard(tenantId,id) as {published_version_id?:string}; if(!dash.published_version_id) throw new NotFoundException('Dashboard sem versão publicada.'); const rows=await this.supabase.select<unknown[]>('dashboard_versions',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${dash.published_version_id}`); if(!rows[0]) throw new NotFoundException('Versão publicada não encontrada.'); return rows[0];}
 private async publishedWidgets(tenantId:string,id:string){const version=await this.published(tenantId,id) as {snapshot?:DashboardSnapshot}; return (version.snapshot?.widgets??[]).sort((a,b)=>(a.position?.y??0)-(b.position?.y??0)||(a.position?.x??0)-(b.position?.x??0));}
 private async validateIndicatorAndVisual(tenantId:string,source:IndicatorSource,indicatorId:string,visual:VisualType){let metadata:Record<string,unknown>={}; if(source==='native'){const detail=await this.nativeIndicators.detail(tenantId,indicatorId) as {availability?:{status?:string}}; const status=detail.availability?.status; if(status!=='available'&&status!=='partial') throw new BadRequestException('Indicador nativo indisponível para dashboard.'); metadata=detail as Record<string,unknown>;} else {const detail=await this.customIndicators.detail(tenantId,indicatorId) as {status?:string;available_for_dashboard?:boolean}; if(detail.status!=='active'||detail.available_for_dashboard!==true) throw new BadRequestException('Indicador personalizado inativo ou indisponível para dashboard.'); metadata=detail as Record<string,unknown>;} const compatibility=this.compatibility(source,metadata); if(!compatibility.allowed_visual_types.includes(visual)) throw new BadRequestException(`Tipo visual incompatível com o indicador. ${compatibility.reason}`);}
 private libraryItem(source:IndicatorSource,metadata:Record<string,unknown>,id:string){const compatibility=this.compatibility(source,metadata); return {id,source,name:String(metadata.name??'Indicador'),result_shape:compatibility.result_shape,allowed_visual_types:compatibility.allowed_visual_types,recommended_visual_type:compatibility.recommended_visual_type,compatibility_reason:compatibility.reason};}
 private compatibility(_source:IndicatorSource,metadata:Record<string,unknown>):Compatibility{return visualCompatibility(metadata);}
 private normalizedPosition(input:unknown){const p=(input&&typeof input==='object'?input:{}) as Record<string,unknown>; return {x:Math.max(0,Number(p.x??0)),y:Math.max(0,Number(p.y??0)),w:Math.min(12,Math.max(1,Number(p.w??3))),h:Math.max(1,Number(p.h??2))};}
 private normalizedLayout(input:unknown){const layout=(input&&typeof input==='object'?input:{}) as Record<string,unknown>; const {global_filters:_legacy,...safe}=layout; return safe;}
 private normalizedFilters(input:unknown){if(!Array.isArray(input)) return []; return input.flatMap<Record<string,unknown>>(item=>{const f=(item&&typeof item==='object'?item:{}) as Record<string,unknown>; const spec=nativeFilters.find(filter=>filter.key===String(f.key??'')); if(!spec) throw new BadRequestException('Filtro nativo desconhecido.'); if(f.type!==spec.type) throw new BadRequestException('Tipo de filtro nativo incompatível.'); if(spec.type==='multi_select'){if(!Array.isArray(f.values)||f.values.some(value=>typeof value!=='string')) throw new BadRequestException('Valores do filtro devem ser uma lista.'); const values=[...new Set(f.values.map(value=>value.trim()).filter(Boolean))]; if(!values.length) return []; return [{field_key:spec.field_key,operator:values.length===1?'igual a':'em',value:values[0]??null,values}];} const from=typeof f.from==='string'?f.from:''; const to=typeof f.to==='string'?f.to:''; if(!from&&!to) throw new BadRequestException('Informe ao menos uma data para o filtro.'); if((from&&!this.validDate(from))||(to&&!this.validDate(to))) throw new BadRequestException('Data de filtro inválida.'); if(from&&to&&from>to) throw new BadRequestException('Intervalo de datas inválido.'); return [{field_key:spec.field_key,operator:from&&to?'entre':from?'maior que':'menor que',value:from||to,value_to:to||null}]; });}
 private validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const date=new Date(value+'T00:00:00.000Z'); return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===value;}
 private async filters(tenantId:string,id:string){return {data:await this.supabase.select('dashboard_filters',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&order=created_at.asc`)}}
 private async getDashboard(tenantId:string,id:string){const rows=await this.supabase.select<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}&status=neq.archived`); if(!rows[0]) throw new NotFoundException('Dashboard não encontrado.'); return rows[0];}
 private async getWidget(tenantId:string,id:string,widgetId:string){const rows=await this.supabase.select<Widget[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`); if(!rows[0]) throw new NotFoundException('Widget não encontrado.'); return rows[0];}
}
