import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { NativeIndicatorsService } from '../native-indicators/native-indicators.service';
import { visualCompatibility } from '../shared/visual-compatibility';
import { CustomIndicatorsService } from '../custom-indicators/custom-indicators.service';
import { AiGatewayService } from '../agents/ai-gateway.service';
import { DashboardSnapshotSummarizerService } from './dashboard-snapshot-summarizer.service';
import { createHash } from 'crypto';

type IndicatorSource = 'native' | 'custom';
type VisualType = 'kpi' | 'table' | 'matrix' | 'bar' | 'pie' | 'line';
type ResultShape = 'scalar' | 'table' | 'matrix' | 'distribution' | 'ranking' | 'timeseries' | 'empty';
type Compatibility = { result_shape: ResultShape; allowed_visual_types: VisualType[]; recommended_visual_type: VisualType; reason: string };
type Widget = { id:string; tenant_id:string; dashboard_id:string; indicator_source:IndicatorSource; indicator_id:string; title:string; visual_type:VisualType; position:{x?:number;y?:number;w?:number;h?:number}; properties:Record<string,unknown> };
type DashboardSnapshot = { widgets?: Widget[]; layout_config?: Record<string, unknown> };
type NativeFilter = { key:string; label:string; group:'Período'|'Entidades'|'Localidade'|'Operação'; type:'date_range'|'multi_select'; field_key:string; placeholder:string };
const nativeFilters: NativeFilter[] = [
  {key:'issued_at',label:'Data de emissão',group:'Período',type:'date_range',field_key:'issued_at',placeholder:'Selecione o período'},
  {key:'expected_date',label:'Data prevista',group:'Período',type:'date_range',field_key:'expected_date',placeholder:'Selecione o período'},
  {key:'completed_at',label:'Data de entrega',group:'Período',type:'date_range',field_key:'completed_at',placeholder:'Selecione o período'},
  {key:'updated_at',label:'Data de atualização',group:'Período',type:'date_range',field_key:'updated_at',placeholder:'Selecione o período'},
  {key:'customer_name',label:'Cliente',group:'Entidades',type:'multi_select',field_key:'customer_name',placeholder:'Selecione clientes'},
  {key:'shipper_name',label:'Embarcador',group:'Entidades',type:'multi_select',field_key:'shipper_name',placeholder:'Selecione embarcadores'},
  {key:'recipient_name',label:'Destinatário',group:'Entidades',type:'multi_select',field_key:'recipient_name',placeholder:'Selecione destinatários'},
  {key:'origin_city',label:'Cidade origem',group:'Localidade',type:'multi_select',field_key:'origin_city',placeholder:'Selecione cidades'},
  {key:'origin_state',label:'UF origem',group:'Localidade',type:'multi_select',field_key:'origin_state',placeholder:'Selecione UFs'},
  {key:'destination_city',label:'Cidade destino',group:'Localidade',type:'multi_select',field_key:'destination_city',placeholder:'Selecione cidades'},
  {key:'destination_state',label:'UF destino',group:'Localidade',type:'multi_select',field_key:'destination_state',placeholder:'Selecione UFs'},
  {key:'status',label:'Status',group:'Operação',type:'multi_select',field_key:'status',placeholder:'Selecione status'},
  {key:'document_type',label:'Tipo de documento',group:'Operação',type:'multi_select',field_key:'document_type',placeholder:'Selecione tipos'},
  {key:'driver_name',label:'Motorista',group:'Operação',type:'multi_select',field_key:'driver_name',placeholder:'Selecione motoristas'},
  {key:'vehicle_plate',label:'Veículo',group:'Operação',type:'multi_select',field_key:'vehicle_plate',placeholder:'Selecione veículos'},
];
const visualTypes = new Set<VisualType>(['kpi','table','matrix','bar','pie','line']);

@Injectable()
export class DashboardsService{
 constructor(private readonly supabase:SupabaseService,private readonly nativeIndicators:NativeIndicatorsService,private readonly customIndicators:CustomIndicatorsService,private readonly gateway:AiGatewayService,private readonly summarizer:DashboardSnapshotSummarizerService){}
 async list(tenantId:string){return {data:await this.supabase.select('dashboard_definitions',`tenant_id=eq.${tenantId}&status=neq.archived&order=updated_at.desc`)}}
 async nativeFilters(tenantId:string){ return {data:await Promise.all(nativeFilters.map(async filter=>{ const rows=await this.supabase.select<Record<string,unknown>[]>('operation_records',`select=${filter.field_key}&tenant_id=eq.${tenantId}&deleted_at=is.null&${filter.field_key}=not.is.null&limit=100`); const values=[...new Set(rows.map(row=>String(row[filter.field_key]??'').trim()).filter(Boolean))].slice(0,100); return {...filter,available:values.length>0,reason:values.length?'': 'Filtro não disponível para a base atual.',options:filter.type==='multi_select'?values.map(value=>({label:value,value})):[]}; }))};}
 async indicatorLibrary(tenantId:string){const [natives,customs]=await Promise.all([this.nativeIndicators.list(tenantId),this.customIndicators.list(tenantId)]); return {data:[
   ...natives.data.filter((i:{availability:{status:string}})=>['available','partial'].includes(i.availability.status)).map((i:Record<string,unknown>)=>this.libraryItem('native',i,String(i.indicator_key))),
   ...(customs.data as Record<string,unknown>[]).filter((i)=>i.status==='active'&&i.available_for_dashboard===true).map((i)=>this.libraryItem('custom',i,String(i.id))),
 ]};}
 async create(tenantId:string,userId:string,body:Record<string,unknown>){const title=String(body.title||'Novo dashboard'); const [row]=await this.supabase.insert<unknown[]>('dashboard_definitions',{tenant_id:tenantId,title,description:body.description??null,created_by:userId,layout_config:this.normalizedLayout(body.layout_config)}); return row;}
 async detail(tenantId:string,id:string){const dash=await this.getDashboard(tenantId,id); return {...dash,widgets:(await this.widgets(tenantId,id)).data,filters:(await this.filters(tenantId,id)).data};}
 async update(tenantId:string,id:string,body:Record<string,unknown>){await this.getDashboard(tenantId,id); const payload:Record<string,unknown>={updated_at:new Date().toISOString()}; if(typeof body.title==='string')payload.title=body.title; if(typeof body.description==='string'||body.description===null)payload.description=body.description; if(body.layout_config&&typeof body.layout_config==='object')payload.layout_config=this.normalizedLayout(body.layout_config); const [row]=await this.supabase.update<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,payload); return row;}
 async remove(tenantId:string,id:string){await this.getDashboard(tenantId,id); const [row]=await this.supabase.update<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,{status:'archived',updated_at:new Date().toISOString()}); return row;}
 async widgets(tenantId:string,id:string){await this.getDashboard(tenantId,id); const data=await this.supabase.select<Widget[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&order=created_at.asc`); return {data:data.sort((a,b)=>(a.position?.y??0)-(b.position?.y??0)||(a.position?.x??0)-(b.position?.x??0))};}
 async addWidget(tenantId:string,id:string,userId:string,body:Record<string,unknown>){await this.getDashboard(tenantId,id); const source:IndicatorSource=body.indicator_source==='custom'?'custom':'native'; const visual=String(body.visual_type||'kpi') as VisualType; if(!visualTypes.has(visual)) throw new BadRequestException('Tipo visual inválido.'); const indicatorId=String(body.indicator_id||''); if(!indicatorId) throw new BadRequestException('Indicador obrigatório.'); await this.validateIndicatorAndVisual(tenantId,source,indicatorId,visual); const [row]=await this.supabase.insert<unknown[]>('dashboard_widgets',{tenant_id:tenantId,dashboard_id:id,indicator_source:source,indicator_id:indicatorId,title:String(body.title||'Widget'),visual_type:visual,position:this.normalizedPosition(body.position),properties:body.properties??{},created_by:userId}); return row;}
 async updateWidget(tenantId:string,id:string,widgetId:string,body:Record<string,unknown>){const current=await this.getWidget(tenantId,id,widgetId); const payload:Record<string,unknown>={updated_at:new Date().toISOString()}; if(typeof body.title==='string')payload.title=body.title; if(typeof body.visual_type==='string'){const visual=body.visual_type as VisualType; if(!visualTypes.has(visual)) throw new BadRequestException('Tipo visual inválido.'); if(visual!==current.visual_type) await this.validateIndicatorAndVisual(tenantId,current.indicator_source,current.indicator_id,visual); payload.visual_type=visual;} if(body.position&&typeof body.position==='object')payload.position=this.normalizedPosition(body.position); if(body.properties&&typeof body.properties==='object')payload.properties=body.properties; const [row]=await this.supabase.update<unknown[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`,payload); return row;}
 async deleteWidget(tenantId:string,id:string,widgetId:string){await this.getWidget(tenantId,id,widgetId); const [row]=await this.supabase.delete<unknown[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`); return row;}
 async preview(tenantId:string,id:string,userId:string,body:Record<string,unknown>){const widgets=body.published===true?await this.publishedWidgets(tenantId,id):(await this.widgets(tenantId,id)).data; const filters={global_filters:this.normalizedFilters(body.filters)}; const previews=await Promise.all(widgets.map(async w=>({widget_id:w.id,result:w.indicator_source==='native'?await this.nativeIndicators.preview(tenantId,w.indicator_id,userId,false,filters):await this.customIndicators.previewSaved(tenantId,w.indicator_id,userId,filters)}))); return {data:previews};}
 async publish(tenantId:string,id:string,userId:string){const dash=await this.detail(tenantId,id); const versions=await this.supabase.select<Array<{version_number:number}>>('dashboard_versions',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&select=version_number&order=version_number.desc&limit=1`); const version_number=(versions[0]?.version_number??0)+1; const [version]=await this.supabase.insert<Array<{id:string}>>('dashboard_versions',{tenant_id:tenantId,dashboard_id:id,version_number,snapshot:dash,created_by:userId}); await this.supabase.update('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}`,{status:'published',published_version_id:version.id,updated_at:new Date().toISOString()}); return version;}
 async published(tenantId:string,id:string){const dash=await this.getDashboard(tenantId,id) as {published_version_id?:string}; if(!dash.published_version_id) throw new NotFoundException('Dashboard sem versão publicada.'); const rows=await this.supabase.select<unknown[]>('dashboard_versions',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${dash.published_version_id}`); if(!rows[0]) throw new NotFoundException('Versão publicada não encontrada.'); return rows[0];}
 async aiAnalysis(tenantId:string,id:string,userId:string,body:Record<string,unknown>){const agent=await this.activeAgent(tenantId);if(!agent)return {analysis:null,message:'Nenhum agente de dashboard ativo foi configurado.',dry_run:true,generated_at:new Date().toISOString()};const snapshot=await this.aiSnapshot(tenantId,id,userId,body.filters);return this.executeDashboardRun(tenantId,id,userId,agent,snapshot,false);}
 async aiQuestion(tenantId:string,id:string,userId:string,body:Record<string,unknown>){const question=typeof body.question==='string'?body.question.trim().slice(0,1000):'';if(!question)throw new BadRequestException('Pergunta obrigatória.');const agent=await this.activeAgent(tenantId);if(!agent)return {answer:'Nenhum agente de dashboard ativo foi configurado.',dry_run:true,generated_at:new Date().toISOString()};const snapshot={...(await this.aiSnapshot(tenantId,id,userId,body.filters)),question};const result=await this.executeDashboardRun(tenantId,id,userId,agent,snapshot,true,question);const answer=(result.analysis as any)?.answer??'Essa pergunta está fora do contexto deste dashboard.';return {answer,dry_run:result.dry_run,ai_run_id:result.ai_run_id,generated_at:result.generated_at};}
 async aiSpeech(tenantId:string,id:string,userId:string,body:Record<string,unknown>){await this.getDashboard(tenantId,id);const text=typeof body.text==='string'?body.text.replace(/<[^>]*>/g,'').trim().slice(0,4000):'';if(!text)throw new BadRequestException('Texto obrigatório para resposta por voz.');const result=await this.gateway.speech(text);if(!result.dry_run){const agent=await this.activeAgent(tenantId);await this.supabase.insert('ai_usage_logs',{tenant_id:tenantId,agent_id:agent?.id??null,ai_run_id:typeof body.ai_run_id==='string'?body.ai_run_id:null,provider:'openai',model_name:result.model_name,input_tokens:0,output_tokens:0,total_tokens:0,estimated_cost_cents:null});}return result;}
 async latestInsight(tenantId:string,id:string){const rows=await this.supabase.select<any[]>('dashboard_ai_insights',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&order=created_at.desc&limit=1`);return {data:rows[0]??null};}
 private async activeAgent(tenantId:string){const rows=await this.supabase.select<any[]>('ai_agents',`tenant_id=eq.${tenantId}&agent_type=eq.dashboard_analyst&status=eq.active&deleted_at=is.null&order=updated_at.desc&limit=1`);return rows[0];}
 private async aiSnapshot(tenantId:string,id:string,userId:string,filters:unknown){const version=await this.published(tenantId,id) as any;const dash=version.snapshot as DashboardSnapshot&{id:string;title?:string};const normalized=this.normalizedFilters(filters);const previews=await this.preview(tenantId,id,userId,{filters,published:true});const byId=new Map((previews.data as any[]).map(item=>[item.widget_id,item.result]));const widgets=(dash.widgets??[]).map(w=>{const result=byId.get(w.id);const result_shape=this.resultShape(result,w.visual_type);return {id:w.id,title:w.title,visual_type:w.visual_type,result_shape,data_summary:{result_available:result!==undefined},deterministic_summary:this.summarizer.summarize(result,result_shape)};});return {dashboard:{id,name:dash.title??'Dashboard',generated_at:new Date().toISOString()},filters:normalized,widgets,rules:{language:'pt-BR',use_only_provided_data:true,do_not_access_database:true,do_not_use_sql:true,do_not_invent_data:true,do_not_calculate_official_indicators:true}};}
 private resultShape(result:any,visual:VisualType):ResultShape {const shape=result?.result_shape??result?.shape;if(['scalar','table','matrix','distribution','ranking','timeseries','empty'].includes(shape))return shape;return visual==='kpi'?'scalar':visual==='matrix'?'matrix':visual==='line'?'timeseries':visual==='pie'?'distribution':visual==='bar'?'ranking':'table';}
 private truncate(value:unknown){const text=JSON.stringify(value??{});if(text.length<=6000)return value;return {truncated:true,note:'Resultado truncado para análise controlada.',preview:text.slice(0,6000)};}
 private async executeDashboardRun(tenantId:string,id:string,userId:string,agent:any,snapshot:Record<string,unknown>,question:boolean,prompt?:string){const started_at=new Date().toISOString();try{const result=await this.gateway.runAgent({tenantId,agent,runType:'dashboard_analysis',triggerType:'manual',inputSnapshot:snapshot,messages:prompt?[{role:'user',content:prompt}]:[],responseSchema:question?this.questionSchema():this.analysisSchema()});const output=result.output_json as any;if(!question&&!this.validAnalysis(output,snapshot))throw new Error('Resposta de análise inválida.');if(question&&!this.validQuestion(output,snapshot))throw new Error('Resposta de pergunta inválida.');const [run]=await this.supabase.insert<any[]>('ai_runs',{tenant_id:tenantId,agent_id:agent.id,run_type:'dashboard_analysis',trigger_type:'manual',status:'completed',input_snapshot:snapshot,output_json:output,model_provider:result.model_provider,model_name:result.model_name,...result.usage,requested_by:userId,started_at,finished_at:new Date().toISOString()});await this.supabase.insert('ai_usage_logs',{tenant_id:tenantId,agent_id:agent.id,ai_run_id:run.id,provider:result.model_provider,model_name:result.model_name,...result.usage});let insight_id:string|undefined;if(!question){const [insight]=await this.supabase.insert<any[]>('dashboard_ai_insights',{tenant_id:tenantId,dashboard_id:id,agent_id:agent.id,ai_run_id:run.id,input_snapshot:snapshot,output_json:output,dry_run:result.dry_run,filters_hash:this.hash((snapshot as any).filters),snapshot_hash:this.hash(snapshot),created_by:userId});insight_id=insight.id;}return {analysis:output,dry_run:result.dry_run,ai_run_id:run.id,insight_id,generated_at:run.finished_at};}catch(error){const error_message=error instanceof Error?error.message:'Falha na análise.';await this.supabase.insert('ai_runs',{tenant_id:tenantId,agent_id:agent.id,run_type:'dashboard_analysis',trigger_type:'manual',status:'failed',input_snapshot:snapshot,error_message,requested_by:userId,started_at,finished_at:new Date().toISOString()});throw new BadRequestException('A análise falhou sem afetar o dashboard.');}}
 private validAnalysis(output:any,snapshot:Record<string,unknown>){const keys=['opening','executive_summary','highlights','attention_points','risks','recommendations','widget_insights','data_quality_notes'];if(!output||keys.some(key=>output[key]===undefined)||typeof output.opening!=='string'||typeof output.executive_summary!=='string'||!Array.isArray(output.widget_insights))return false;const ids=new Set(((snapshot.widgets as any[])??[]).map(w=>w.id));output.widget_insights=output.widget_insights.filter((item:any)=>item&&ids.has(item.widget_id)&&typeof item.analysis==='string');return keys.filter(key=>key!=='opening'&&key!=='executive_summary'&&key!=='widget_insights').every(key=>Array.isArray(output[key]));}
 private validQuestion(output:any,snapshot:Record<string,unknown>){if(!output||typeof output.answer!=='string'||!Array.isArray(output.related_widgets)||!Array.isArray(output.limitations))return false;const ids=new Set(((snapshot.widgets as any[])??[]).map(w=>w.id));output.related_widgets=output.related_widgets.filter((widgetId:string)=>ids.has(widgetId));return true;}
 private analysisSchema(){return {type:'object',additionalProperties:false,required:['opening','executive_summary','highlights','attention_points','risks','recommendations','widget_insights','data_quality_notes'],properties:{opening:{type:'string'},executive_summary:{type:'string'},highlights:{type:'array',items:{type:'string'}},attention_points:{type:'array',items:{type:'string'}},risks:{type:'array',items:{type:'string'}},recommendations:{type:'array',items:{type:'string'}},widget_insights:{type:'array',items:{type:'object',additionalProperties:false,required:['widget_id','widget_title','analysis'],properties:{widget_id:{type:'string'},widget_title:{type:'string'},analysis:{type:'string'}}}},data_quality_notes:{type:'array',items:{type:'string'}}}};}
 private questionSchema(){return {type:'object',additionalProperties:false,required:['answer','related_widgets','limitations'],properties:{answer:{type:'string'},related_widgets:{type:'array',items:{type:'string'}},limitations:{type:'array',items:{type:'string'}}}};}
 private hash(value:unknown){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
 private async publishedWidgets(tenantId:string,id:string){const version=await this.published(tenantId,id) as {snapshot?:DashboardSnapshot}; return (version.snapshot?.widgets??[]).sort((a,b)=>(a.position?.y??0)-(b.position?.y??0)||(a.position?.x??0)-(b.position?.x??0));}
 private async validateIndicatorAndVisual(tenantId:string,source:IndicatorSource,indicatorId:string,visual:VisualType){let metadata:Record<string,unknown>={}; if(source==='native'){const detail=await this.nativeIndicators.detail(tenantId,indicatorId) as {availability?:{status?:string}}; const status=detail.availability?.status; if(status!=='available'&&status!=='partial') throw new BadRequestException('Indicador nativo indisponível para dashboard.'); metadata=detail as Record<string,unknown>;} else {const detail=await this.customIndicators.detail(tenantId,indicatorId) as {status?:string;available_for_dashboard?:boolean}; if(detail.status!=='active'||detail.available_for_dashboard!==true) throw new BadRequestException('Indicador personalizado inativo ou indisponível para dashboard.'); metadata=detail as Record<string,unknown>;} const compatibility=this.compatibility(source,metadata); if(!compatibility.allowed_visual_types.includes(visual)) throw new BadRequestException(`Tipo visual incompatível com o indicador. ${compatibility.reason}`);}
 private libraryItem(source:IndicatorSource,metadata:Record<string,unknown>,id:string){const compatibility=this.compatibility(source,metadata); return {id,source,name:String(metadata.name??'Indicador'),result_shape:compatibility.result_shape,allowed_visual_types:compatibility.allowed_visual_types,recommended_visual_type:compatibility.recommended_visual_type,compatibility_reason:compatibility.reason};}
 private compatibility(_source:IndicatorSource,metadata:Record<string,unknown>):Compatibility{return visualCompatibility(metadata);}
 private normalizedPosition(input:unknown){const p=(input&&typeof input==='object'?input:{}) as Record<string,unknown>; return {x:Math.max(0,Number(p.x??0)),y:Math.max(0,Number(p.y??0)),w:Math.min(12,Math.max(1,Number(p.w??3))),h:Math.max(1,Number(p.h??2))};}
 private normalizedLayout(input:unknown){const layout=(input&&typeof input==='object'?input:{}) as Record<string,unknown>; const {global_filters:_legacy,...safe}=layout; return safe;}
 private normalizedFilters(input:unknown){if(!Array.isArray(input)) return []; return input.flatMap<Record<string,unknown>>(item=>{const f=(item&&typeof item==='object'?item:{}) as Record<string,unknown>; const spec=nativeFilters.find(filter=>filter.key===String(f.key??'')); if(!spec) throw new BadRequestException('Filtro nativo desconhecido.'); if(f.type!==spec.type) throw new BadRequestException('Tipo de filtro nativo incompatível.'); if(spec.type==='multi_select'){if(!Array.isArray(f.values)||f.values.some(value=>typeof value!=='string')) throw new BadRequestException('Valores do filtro devem ser uma lista.'); const values=[...new Set(f.values.map(value=>value.trim()).filter(Boolean))]; if(!values.length) return []; return [{field_key:spec.field_key,operator:values.length===1?'igual a':'em',value:values[0]??null,values}];} const from=typeof f.from==='string'?f.from:''; const to=typeof f.to==='string'?f.to:''; if(!from&&!to) throw new BadRequestException('Informe ao menos uma data para o filtro.'); if((from&&!this.validDate(from))||(to&&!this.validDate(to))) throw new BadRequestException('Data de filtro inválida.'); if(from&&to&&from>to) throw new BadRequestException('Intervalo de datas inválido.'); return [{field_key:spec.field_key,operator:from&&to?'entre':from?'maior que':'menor que',value:from||to,value_to:to||null}]; });}
 private validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const date=new Date(value+'T00:00:00.000Z'); return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===value;}
 private async filters(tenantId:string,id:string){return {data:await this.supabase.select('dashboard_filters',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&order=created_at.asc`)}}
 private async getDashboard(tenantId:string,id:string){const rows=await this.supabase.select<unknown[]>('dashboard_definitions',`tenant_id=eq.${tenantId}&id=eq.${id}&status=neq.archived`); if(!rows[0]) throw new NotFoundException('Dashboard não encontrado.'); return rows[0];}
 private async getWidget(tenantId:string,id:string,widgetId:string){const rows=await this.supabase.select<Widget[]>('dashboard_widgets',`tenant_id=eq.${tenantId}&dashboard_id=eq.${id}&id=eq.${widgetId}`); if(!rows[0]) throw new NotFoundException('Widget não encontrado.'); return rows[0];}
}
