import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { AiGatewayService } from './ai-gateway.service';
import { AgentToolExecutorService } from './agent-tool-executor.service';
import { parseChatIntent } from './chat-intent-parser';

const FALLBACK='Olá! Sou o Agente Geral do Sistema Logístico Integrado. Posso ajudar com dúvidas sobre o sistema, processos internos publicados na Base de Conhecimento e consultas à base tratada da operação.';
const INDICATOR_FALLBACK='Não encontrei um indicador homologado para responder essa análise com segurança. Crie um indicador personalizado para essa métrica e depois me pergunte novamente.';
const RECORD_FALLBACK='Não encontrei esse item na base tratada disponível.';
const DASHBOARD_FALLBACK='Não encontrei dashboard publicado ou análise disponível para esse tema.';
const REPORT_FALLBACK='Não encontrei relatório gerado com análise disponível para esse tema.';
const KNOWLEDGE_FALLBACK='Não encontrei conteúdo publicado na Base de Conhecimento sobre esse tema.';

@Injectable()
export class ChatService {
  constructor(private db:SupabaseService,private gateway:AiGatewayService,private tools:AgentToolExecutorService){}
  async conversations(t:string,u:string){return {data:await this.db.select('ai_chat_conversations',`tenant_id=eq.${t}&user_id=eq.${u}&deleted_at=is.null&status=eq.active&order=updated_at.desc&limit=50`)}}
  async create(t:string,u:string,b:Record<string,unknown>){const a=await this.agent(t);const [x]=await this.db.insert<any[]>('ai_chat_conversations',{tenant_id:t,user_id:u,agent_id:a?.id??null,title:typeof b.title==='string'?this.cleanUserMessage(b.title,120):null});return x}
  async messages(t:string,u:string,id:string){await this.conversation(t,u,id);return {data:await this.db.select('ai_chat_messages',`tenant_id=eq.${t}&conversation_id=eq.${id}&order=created_at.asc&limit=100`)}}
  async archive(t:string,u:string,id:string){await this.conversation(t,u,id);await this.db.update('ai_chat_conversations',`tenant_id=eq.${t}&id=eq.${id}`,{status:'archived',deleted_at:new Date().toISOString()});return {archived:true}}
  async send(t:string,u:string,id:string,b:Record<string,unknown>){
    const message=this.cleanUserMessage(b.message,2000),conversation=await this.conversation(t,u,id),agent=await this.agent(t);
    if(!agent)return {enabled:false,message:await this.save(t,id,'assistant','Nenhum agente de chat geral ativo foi configurado.')};
    await this.save(t,id,'user',message);
    const [run]=await this.db.insert<any[]>('ai_runs',{tenant_id:t,agent_id:agent.id,run_type:'general_chat',trigger_type:'chat_message',status:'processing',input_snapshot:{conversation_id:id,message:message.slice(0,500)},requested_by:u,started_at:new Date().toISOString()});
    const intent=parseChatIntent(message);let toolKey:string|undefined,source:string|undefined,result:any,fallback:string|undefined,summary:unknown;
    try {
      if(intent.route==='knowledge_search'){toolKey='knowledge_base.search';source='knowledge_documents';result=await this.controlled(t,run.id,agent,toolKey,{query:message,limit:8},()=>this.tools.execute(t,toolKey!,{query:message,limit:8}));if(result.blocked)fallback=result.message;else if(!result.value.results?.length)fallback=KNOWLEDGE_FALLBACK;else result=result.value;}
      if(intent.route==='operational_search'){
        toolKey='treated_data.search_records';source='operation_records';
        if(!intent.identifier)fallback=RECORD_FALLBACK;else {const search=await this.controlled(t,run.id,agent,toolKey,{identifier:intent.identifier},()=>this.tools.execute(t,toolKey!,{identifier:intent.identifier}));if(search.blocked)fallback=search.message;else if(!search.value.matches?.length)fallback=RECORD_FALLBACK;else {result=search.value;if(result.matches.length===1){const detail=await this.controlled(t,run.id,agent,'treated_data.get_record_detail',{id:result.matches[0].id},()=>this.tools.execute(t,'treated_data.get_record_detail',{id:result.matches[0].id}));if(detail.blocked)fallback=detail.message;else {toolKey='treated_data.search_records,treated_data.get_record_detail';result={...result,detail:detail.value};}}}}
      }
      if(intent.route==='indicator_query'){
        source='indicators';const list=await this.controlled(t,run.id,agent,'indicators.list_available',{},()=>this.tools.execute(t,'indicators.list_available',{}));
        if(list.blocked)fallback=list.message;else {const hit=this.indicatorMatch(message,list.value.indicators||[]);if(!hit)fallback=INDICATOR_FALLBACK;else {const indicator=await this.controlled(t,run.id,agent,'indicators.get_result',{id:hit.id},()=>this.tools.execute(t,'indicators.get_result',{id:hit.id}));if(indicator.blocked)fallback=indicator.message;else {toolKey='indicators.list_available,indicators.get_result';result=indicator.value;}}}
      }
      if(intent.route==='dashboard_context'){toolKey='dashboard.get_snapshot';source='dashboards publicados, versões e insights';const context=await this.controlled(t,run.id,agent,toolKey,{query:message},()=>this.dashboardContext(t,message));if(context.blocked)fallback=context.message;else if(!context.value)fallback=DASHBOARD_FALLBACK;else {result=this.sanitizeDashboardContext(context.value);summary=this.contextSummary(result);}}
      if(intent.route==='report_context'){toolKey='reports.get_job_snapshot';source='relatórios gerados';const context=await this.controlled(t,run.id,agent,toolKey,{query:message},()=>this.reportContext(t,message));if(context.blocked)fallback=context.message;else if(!context.value)fallback=REPORT_FALLBACK;else {result=this.sanitizeReportContext(context.value);summary=this.contextSummary(result);}}
      if(intent.route==='fallback')fallback=FALLBACK;
      if(fallback)return this.complete(t,id,conversation,run,agent,fallback,toolKey,undefined,true,{route:intent.route,source,fallback_used:true,sanitized_context_summary:summary});
      const history=await this.recentHistory(t,id),response=await this.gateway.generalChat({agent,message,history,toolResult:result,toolResults:[{tool_key:toolKey||intent.route,result}],plan:{route:intent.route,source}});
      return this.complete(t,id,conversation,run,agent,this.cleanAssistantAnswer(response.answer,4000)||FALLBACK,toolKey,response,!response.answer,{route:intent.route,source,tool_key:toolKey,sanitized_context_summary:summary});
    }catch{await this.db.update('ai_runs',`tenant_id=eq.${t}&id=eq.${run.id}`,{status:'failed',error_message:'Falha ao responder no Chat Geral.',output_json:{route:intent.route,safe_error:'Não foi possível concluir a resposta com segurança.'},finished_at:new Date().toISOString()});throw new BadRequestException('Não foi possível responder agora. Tente novamente.')}
  }
  private async controlled(t:string,run:string,agent:any,key:string,input:Record<string,unknown>,action:()=>Promise<any>):Promise<{blocked:true;message:string}|{blocked:false;value:any}>{
    if(!(await this.enabled(t,agent.id,key))){const message=`Essa consulta exige a ferramenta ${key}, mas ela não está habilitada para este agente.`;await this.toolCall(t,run,key,input,{message},'blocked','Ferramenta não habilitada para o agente.');return {blocked:true,message};}
    const started=Date.now();try{const value=await action();await this.toolCall(t,run,key,input,value,'completed',undefined,started);return {blocked:false,value};}catch(error){await this.toolCall(t,run,key,input,{message:'Falha controlada ao consultar a fonte.'},'failed','Falha na ferramenta controlada.',started);throw error;}
  }
  private async toolCall(t:string,run:string,key:string,input:Record<string,unknown>,output:unknown,status:'completed'|'failed'|'blocked',error?:string,started=Date.now()){const tools=await this.db.select<any[]>('ai_tools',`tool_key=eq.${key}&limit=1`);await this.db.insert('ai_tool_calls',{tenant_id:t,ai_run_id:run,tool_id:tools[0]?.id??null,tool_key:key,input_json:input,output_json:output,status,error_message:error??null,duration_ms:Date.now()-started,finished_at:new Date().toISOString()})}
  private indicatorMatch(message:string,items:any[]){const words=message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().split(/[^a-z0-9]+/).filter(word=>word.length>2&&!['qual','com','para','por','mais','menos'].includes(word));return items.map(item=>({item,score:words.filter(word=>`${item.name||''} ${item.title||''} ${item.description||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(word)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)[0]?.item}
  private async dashboardContext(t:string,message:string){const rows=await this.db.select<any[]>('dashboard_definitions',`select=id,title,updated_at,published_version_id&tenant_id=eq.${t}&status=eq.published&order=updated_at.desc&limit=10`),term=message.replace(/dashboard|painel|an[aá]lise|atual|[uú]ltimo|o que|mostrou|plano de a[cç][aã]o/gi,'').trim().toLowerCase(),dashboard=rows.find(row=>!term||String(row.title||'').toLowerCase().includes(term))||rows[0];if(!dashboard)return null;const [version,insight]=await Promise.all([dashboard.published_version_id?this.db.select<any[]>('dashboard_versions',`select=version_number,snapshot,created_at&tenant_id=eq.${t}&id=eq.${dashboard.published_version_id}&limit=1`):Promise.resolve([]),this.db.select<any[]>('dashboard_ai_insights',`select=output_json,created_at&tenant_id=eq.${t}&dashboard_id=eq.${dashboard.id}&order=created_at.desc&limit=1`)]);return version[0]||insight[0]?{dashboard,version:version[0]||null,insight:insight[0]||null}:null}
  private async reportContext(t:string,message:string){const defs=await this.db.select<any[]>('report_definitions',`select=id,name,description,updated_at&tenant_id=eq.${t}&status=eq.active&deleted_at=is.null&order=updated_at.desc&limit=10`),term=message.replace(/relat[oó]rio|conclus[aã]o|pontos de aten[cç][aã]o|[uú]ltimo|plano de a[cç][aã]o/gi,'').trim().toLowerCase(),report=defs.find(row=>!term||`${row.name||''} ${row.description||''}`.toLowerCase().includes(term))||defs[0];if(!report)return null;const job=(await this.db.select<any[]>('report_jobs',`select=id,created_at,finished_at,ai_snapshot,render_snapshot,data_snapshot&tenant_id=eq.${t}&report_definition_id=eq.${report.id}&status=eq.completed&order=created_at.desc&limit=1`))[0];return job?{report,job}:null}
  private sanitizeDashboardContext(value:any){const snapshot=value.version?.snapshot||{};return {dashboard:{title:value.dashboard.title,updated_at:value.dashboard.updated_at,version:value.version?.version_number??null},widgets:Array.isArray(snapshot.widgets)?snapshot.widgets.slice(0,10).map((widget:any)=>this.sanitize(widget)):[],ai_insight:this.sanitize(value.insight?.output_json??null)} }
  private sanitizeReportContext(value:any){const render=value.job.render_snapshot||{},sections=Array.isArray(render.sections)?render.sections:[];let blocks=0;return {report:{name:value.report.name,description:value.report.description},generated_at:value.job.finished_at||value.job.created_at,ai_snapshot:this.sanitize(value.job.ai_snapshot),render_snapshot:{report:this.sanitize(render.report),filters:this.sanitize(render.filters),sections:sections.slice(0,10).map((section:any)=>({...this.sanitize({...section,blocks:undefined}),blocks:(Array.isArray(section.blocks)?section.blocks:[]).filter(()=>blocks++<10).map((block:any)=>this.sanitize(block))}))}}}
  private sanitize(value:any,depth=0):any{if(value===null||value===undefined||typeof value==='number'||typeof value==='boolean')return value;if(typeof value==='string')return value.slice(0,500);if(depth>5)return undefined;if(Array.isArray(value))return value.slice(0,20).map(item=>this.sanitize(item,depth+1)).filter(item=>item!==undefined);if(typeof value==='object')return Object.entries(value).filter(([key])=>!/raw|payload|hash|staging|source_|tenant_id|created_by|updated_by/i.test(key)).slice(0,30).reduce((out,[key,item])=>{const safe=this.sanitize(item,depth+1);if(safe!==undefined)(out as any)[key]=safe;return out},{} as Record<string,unknown>);return undefined}
  private contextSummary(value:any){return {top_level_keys:value&&typeof value==='object'?Object.keys(value).slice(0,10):[],widgets:Array.isArray(value?.widgets)?value.widgets.length:undefined,sections:Array.isArray(value?.render_snapshot?.sections)?value.render_snapshot.sections.length:undefined}}
  private async complete(t:string,id:string,c:any,run:any,agent:any,answer:string,toolKey?:string,result?:any,fallback=false,metadata:Record<string,unknown>={}){const usage={input_tokens:Number(result?.input_tokens)||0,output_tokens:Number(result?.output_tokens)||0,total_tokens:Number(result?.total_tokens)||0};await this.db.update('ai_runs',`tenant_id=eq.${t}&id=eq.${run.id}`,{status:'completed',output_json:{answer,tool_key:toolKey,...metadata,fallback_used:fallback},model_provider:result?.model_provider??'system',model_name:result?.model_name??null,...usage,finished_at:new Date().toISOString()});if(result)await this.db.insert('ai_usage_logs',{tenant_id:t,agent_id:agent.id,ai_run_id:run.id,provider:result.model_provider,model_name:result.model_name,...usage});const saved=await this.save(t,id,'assistant',answer,run.id,toolKey?{tool_key:toolKey}:{});await this.db.update('ai_chat_conversations',`tenant_id=eq.${t}&id=eq.${id}`,{updated_at:new Date().toISOString(),title:c.title||answer.slice(0,80)});return {message:saved,ai_run_id:run.id,tool_key:toolKey,dry_run:result?.dry_run??true}}
  async speech(_t:string,b:Record<string,unknown>){return this.gateway.speech(this.cleanAssistantAnswer(b.text,4000)||FALLBACK)}
  async voiceMessage(t:string,u:string,id:string,b:Record<string,unknown>){await this.conversation(t,u,id);const audio=String(b.audio_base64||'');if(audio.length>1_000_000)throw new BadRequestException('Áudio muito grande. Use a conversa por voz ao vivo.');const transcript=await this.gateway.transcribe(audio,String(b.audio_mime_type||'audio/webm'),String(b.language||'pt-BR'));const response=await this.send(t,u,id,{message:transcript});return {transcript,message:response.message,dry_run:true}}
  async realtime(t:string){const a=await this.agent(t);if(!a)throw new BadRequestException('Nenhum agente de chat geral ativo foi configurado.');return this.gateway.realtimeSession(a,'Responda em português do Brasil como Agente Geral. Você pode orientar sobre o sistema e o uso geral. Não execute ferramentas, não consulte dados operacionais ao vivo, não prometa ações e não altere dados. Para dados específicos, oriente a pessoa a usar o chat por texto.')}
  private async recentHistory(t:string,id:string){return (await this.db.select<any[]>('ai_chat_messages',`tenant_id=eq.${t}&conversation_id=eq.${id}&order=created_at.desc&limit=10`)).reverse().map(x=>({role:String(x.role),content:String(x.content)}))}
  private async save(t:string,id:string,role:string,content:string,ai_run_id?:string,metadata:Record<string,unknown>={}){const[x]=await this.db.insert<any[]>('ai_chat_messages',{tenant_id:t,conversation_id:id,ai_run_id,role,content,metadata});return x}
  private async conversation(t:string,u:string,id:string){const x=await this.db.select<any[]>('ai_chat_conversations',`tenant_id=eq.${t}&id=eq.${id}&user_id=eq.${u}&deleted_at=is.null&limit=1`);if(!x[0])throw new NotFoundException('Conversa não encontrada.');return x[0]}
  private async agent(t:string){return(await this.db.select<any[]>('ai_agents',`tenant_id=eq.${t}&agent_type=eq.general_chat&status=eq.active&deleted_at=is.null&order=updated_at.desc&limit=1`))[0]}
  private async enabled(t:string,a:string,k:string){return!!(await this.db.select<any[]>('ai_agent_tools',`tenant_id=eq.${t}&agent_id=eq.${a}&is_enabled=eq.true&select=ai_tools!inner(tool_key)&ai_tools.tool_key=eq.${k}&limit=1`))[0]}
  private cleanUserMessage(v:unknown,max:number){const s=this.stripHtml(v,max);if(!s)throw new BadRequestException('Mensagem obrigatória.');if(/\b(select|insert|update|delete|drop|alter|create|truncate)\b[\s\S]{0,160}\b(from|into|table|where|set|database)\b/i.test(s))throw new BadRequestException('Conteúdo não permitido.');return s}
  private cleanAssistantAnswer(v:unknown,max:number){return this.stripHtml(v,max)}
  private stripHtml(v:unknown,max:number){return typeof v==='string'?v.replace(/<[^>]*>/g,'').trim().slice(0,max):''}
}
