import { BadRequestException, Injectable } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { AgentToolExecutorService } from './agent-tool-executor.service';
import { AgentQueryPlan } from './agent-query-planner.service';
const FIELDS='id,external_id,external_code,document_number,document_type,cte_number,invoice_number,manifest_number,order_number,delivery_number,customer_name,shipper_name,recipient_name,payer_name,driver_name,vehicle_plate,status,occurrence_status,data_quality_status,issued_at,expected_date,completed_at,status_updated_at,last_event_at,gross_weight,cubed_weight,volume_count,total_value,freight_value,origin_state,destination_state';
@Injectable() export class ControlledAgentQueryExecutorService {
 constructor(private db:SupabaseService,private legacy:AgentToolExecutorService){}
 toolKeys(p:AgentQueryPlan){if(p.intent==='aggregate')return [p.aggregate?.use_indicator_if_compatible?'indicators.get_result':'treated_data.aggregate_records',...(p.include.includes('count_and_list')?['treated_data.list_records']:[])];const key:Record<string,string>={knowledge_search:'knowledge_base.search',record_search:'treated_data.search_records',record_detail:'treated_data.get_record_detail',indicator_lookup:'indicators.get_result',dashboard_context:'dashboards.search_context',report_context:'reports.search_context',list_records:'treated_data.list_records',entity_performance:'treated_data.get_entity_performance',operational_overview:'treated_data.get_operational_overview'};return key[p.intent]?[key[p.intent]]:[];}
 async execute(t:string,p:AgentQueryPlan):Promise<{tool_key:string;result:any}[]> {const keys=this.toolKeys(p);if(!keys.length)return[];if(p.intent==='aggregate'){const available=await this.legacy.execute(t,'indicators.list_available',{});const terms:Record<string,string[]>={freight_value:['frete','freight'],gross_weight:['peso','weight'],volume_count:['volume'],id:['entrega','delivery','registro']};const hit=(available as any).indicators?.find((x:any)=>terms[p.aggregate!.field].some(term=>String(x.name).toLowerCase().includes(term)));const actions:any[]=[];if(p.aggregate?.use_indicator_if_compatible&&hit){const indicator=await this.legacy.execute(t,'indicators.get_result',{id:hit.id}) as any;actions.push({tool_key:'indicators.get_result',result:{...indicator,metric:p.aggregate.operation,field:p.aggregate.field,group_by:p.aggregate.group_by,sort:p.aggregate.sort,filters_applied:p.filters}});}else actions.push({tool_key:'treated_data.aggregate_records',result:await this.aggregate(t,p)});if(p.include.includes('count_and_list'))actions.push({tool_key:'treated_data.list_records',result:await this.list(t,p.filters)});return actions;}return [{tool_key:keys[0],result:await this.run(t,p)}]; }
 private async run(t:string,p:AgentQueryPlan):Promise<any>{if(p.intent==='knowledge_search')return this.legacy.execute(t,'knowledge_base.search',{query:p.query,limit:8});if(p.intent==='indicator_lookup')return this.legacy.execute(t,'indicators.get_result',{name:p.query});if(p.intent==='record_search')return this.search(t,p.identifier||p.query);if(p.intent==='dashboard_context')return this.dashboards(t,p.query);if(p.intent==='report_context')return this.reports(t,p.query);if(p.intent==='entity_performance')return this.performance(t,p);if(p.intent==='operational_overview')return this.overview(t);return this.list(t,p.filters);}
 private filter(t:string,f:Record<string,any>){const q=[`select=${FIELDS}`,`tenant_id=eq.${t}`,'deleted_at=is.null'];for(const k of ['status','customer_name','driver_name','vehicle_plate','origin_state','destination_state'])if(typeof f[k]==='string')q.push(`${k}=ilike.${encodeURIComponent('*'+f[k].slice(0,100)+'*')}`);const d=f.date_range;if(d?.field&&['issued_at','expected_date','completed_at','updated_at','last_event_at'].includes(d.field)){if(d.start)q.push(`${d.field}=gte.${encodeURIComponent(d.start)}`);if(d.end)q.push(`${d.field}=lte.${encodeURIComponent(d.end)}`)}return q;}
 private async rows(t:string,f:Record<string,any>={}){return this.db.select<any[]>('operation_records',`${this.filter(t,f).join('&')}&limit=10000`)}
 private async search(t:string,q:string){const term=encodeURIComponent('*'+q.slice(0,160)+'*'), cols=['document_number','invoice_number','cte_number','manifest_number','order_number','delivery_number','external_id','external_code','customer_name','shipper_name','recipient_name','payer_name','driver_name','vehicle_plate'];const rows=await this.db.select<any[]>('operation_records',`select=${FIELDS}&tenant_id=eq.${t}&deleted_at=is.null&or=(${cols.map(c=>`${c}.ilike.${term}`).join(',')})&order=updated_at.desc&limit=20`);return{matches:rows.map(r=>({entity:'operation_record',id:r.id,title:r.delivery_number||r.invoice_number||r.cte_number||r.document_number||r.id,summary:r})),total:rows.length,truncated:false};}
 private async list(t:string,f:Record<string,any>){const all=await this.rows(t,f);all.sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||''))||String(b.last_event_at||'').localeCompare(String(a.last_event_at||''))||String(b.updated_at||'').localeCompare(String(a.updated_at||''))||String(b.created_at||'').localeCompare(String(a.created_at||'')));return{records:all.slice(0,20),total:all.length,truncated:all.length>20,filters_applied:f};}
 private async aggregate(t:string,p:AgentQueryPlan){const a=p.aggregate!, rows=await this.rows(t,p.filters), calc=(x:any[])=>a.operation==='count'?x.length:a.operation==='sum'?x.reduce((n,r)=>n+(Number(r[a.field])||0),0):a.operation==='avg'?(x.length?x.reduce((n,r)=>n+(Number(r[a.field])||0)/x.length,0):0):a.operation==='min'?(x.length?Math.min(...x.map(r=>Number(r[a.field])||0)):0):(x.length?Math.max(...x.map(r=>Number(r[a.field])||0)):0);const unit=a.field==='freight_value'||a.field==='total_value'?'BRL':a.field.includes('weight')?'kg':a.field==='volume_count'?'volumes':'registros';if(a.group_by==='none'){const total=calc(rows),comparable={...p.filters};delete comparable.status;delete comparable.customer_name;const denominator=(await this.rows(t,comparable)).length;return{metric:a.operation,field:a.field,group_by:'none',sort:a.sort,unit,filters_applied:p.filters,total,...(a.include_percentage?{numerator:rows.length,denominator,percentage:denominator?Number((rows.length/denominator*100).toFixed(2)):0}:{})};}const buckets=new Map<string,any[]>();rows.forEach(r=>{const k=String(r[a.group_by]||'Não informado');buckets.set(k,[...(buckets.get(k)||[]),r])});const direction=a.sort==='asc'?1:-1;return{metric:a.operation,field:a.field,group_by:a.group_by,sort:a.sort,unit,filters_applied:p.filters,rows:[...buckets].map(([label,x])=>({label,value:calc(x),numerator:x.length,percentage:rows.length?Number((x.length/rows.length*100).toFixed(2)):0})).sort((left,right)=>direction*(left.value-right.value)||left.label.localeCompare(right.label)).slice(0,a.limit)};}
 private async performance(t:string,p:AgentQueryPlan){const rows=await this.rows(t,p.filters), dist=this.distribution(rows,'status');return{entity:p.entity,identifier:Object.values(p.filters)[0]||p.query,total_records:rows.length,status_distribution:dist,percentages:dist.map(x=>({...x,percentage:rows.length?Number((x.value/rows.length*100).toFixed(2)):0})),freight_total:this.sum(rows,'freight_value'),gross_weight_total:this.sum(rows,'gross_weight'),volume_total:this.sum(rows,'volume_count'),top_customers:this.top(rows,'customer_name'),top_destinations:this.top(rows,'destination_state'),sample_records:rows.slice(0,20),data_quality_notes:[]};}
 private async overview(t:string){const rows=await this.rows(t);return{total_records:rows.length,status_distribution:this.distribution(rows,'status'),freight_total:this.sum(rows,'freight_value'),gross_weight_total:this.sum(rows,'gross_weight'),volume_total:this.sum(rows,'volume_count'),top_customers:this.top(rows,'customer_name'),top_drivers:this.top(rows,'driver_name'),top_vehicles:this.top(rows,'vehicle_plate'),top_origin_states:this.top(rows,'origin_state'),top_destination_states:this.top(rows,'destination_state'),data_quality_notes:[]};}
 private async dashboards(t:string,q:string){const latest=/atual|ultimo/.test(q.toLowerCase());const rows=await this.db.select<any[]>('dashboard_definitions',`select=id,title,status,updated_at&tenant_id=eq.${t}&status=eq.published${latest?'':`&title=ilike.${encodeURIComponent('*'+q.slice(0,100)+'*')}`}&order=updated_at.desc&limit=10`);const dashboards=await Promise.all(rows.map(async d=>({dashboard:d,widgets:await this.db.select<any[]>('dashboard_widgets',`select=title,indicator_source,indicator_id,visual_type&tenant_id=eq.${t}&dashboard_id=eq.${d.id}&limit=12`),insight:(await this.db.select<any[]>('dashboard_ai_insights',`select=output_json,created_at&tenant_id=eq.${t}&dashboard_id=eq.${d.id}&status=eq.completed&order=created_at.desc&limit=1`))[0]||null})));return{dashboards_found:dashboards};}
 private async reports(t:string,q:string){const latest=/ultimo/.test(q.toLowerCase());const rows=await this.db.select<any[]>('report_definitions',`select=id,name,description,status,updated_at&tenant_id=eq.${t}&status=eq.active&deleted_at=is.null${latest?'':`&name=ilike.${encodeURIComponent('*'+q.slice(0,100)+'*')}`}&order=updated_at.desc&limit=10`);const reports=await Promise.all(rows.map(async r=>({report:r,last_job:(await this.db.select<any[]>('report_jobs',`select=id,status,created_at,finished_at,ai_snapshot,render_snapshot&tenant_id=eq.${t}&report_definition_id=eq.${r.id}&status=eq.completed&order=created_at.desc&limit=1`))[0]||null})));return{reports_found:reports};}
 private sum(rows:any[],k:string){return rows.reduce((n,r)=>n+(Number(r[k])||0),0)} private distribution(rows:any[],k:string){return this.top(rows,k)} private top(rows:any[],k:string){const m=new Map<string,number>();rows.forEach(r=>{const v=String(r[k]||'Não informado');m.set(v,(m.get(v)||0)+1)});return[...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,10)}
}
