import { BadRequestException, Injectable } from '@nestjs/common';
import { AiGatewayService } from './ai-gateway.service';
import { AgentToolExecutorService } from './agent-tool-executor.service';
import { SupabaseService } from '../supabase/supabase.service';
import { normalizeAssistantOutput } from './assistant-output-normalizer';
import { GENERAL_CHAT_ALLOWED_ARGUMENTS, GENERAL_CHAT_FILTER_FIELDS, GENERAL_CHAT_FUNCTION_TO_KEY, GENERAL_CHAT_TOOL_KEYS, generalChatToolDefinitions, isOperationalMessage } from './general-chat-tool-contracts';

const keys=GENERAL_CHAT_TOOL_KEYS;
const forbidden=/sql|table|schema|staging|payload|raw|operation_records|dashboard_snapshot|render_snapshot|data_snapshot/i;

@Injectable()
export class GeneralChatOrchestratorService {
  constructor(private readonly gateway:AiGatewayService,private readonly tools:AgentToolExecutorService,private readonly db:SupabaseService) {}
  async execute(tenantId:string,agent:any,message:string,history:any[]=[],runId?:string,clientContext:Record<string,unknown>={}){
    const toolKeys:string[]=[];
    try {
      const contextual=this.contextualMessage(message,history),resolvedMessage=contextual.message,periodDetected=this.explicitPeriod(message),totalSystem=this.totalSystemPeriod(message);const contextBytes=Buffer.byteLength(JSON.stringify({message:resolvedMessage,history:history.slice(-8),clientContext}));let sanitizedArgs=false,periodSanitized=false,invalidArgsRecovered=false;
      let state:any=await this.gateway.generalChatToolCall({agent,message:resolvedMessage,history:history.slice(-8)}), results:any[]=[], rounds=0,executions=0, final:any;
      while(rounds++<3&&state.calls?.length){const outputs=[] as any[];for(const call of state.calls){const selected=this.internalName(call.name),name=this.contextTool(selected,resolvedMessage,clientContext);if(executions>=4){const entry={call_id:call.id,name,result:{tool_error:true,error_code:'TOOL_CALL_LIMIT_REACHED',message:'Consulta excedeu o limite de ferramentas nesta rodada. Refine a pergunta ou consulte por partes.'}};results.push(entry);outputs.push(entry);continue;}executions++;if(keys.includes(name as any))toolKeys.push(name);let args:Record<string,any>;const clean=this.sanitizeArguments(call.arguments),normalized=this.normalizeContextualArguments(name,name===selected?clean.value:{},message);sanitizedArgs=sanitizedArgs||clean.changed||normalized.changed;periodSanitized=periodSanitized||normalized.periodRemoved;try{args=this.withClientContext(name,this.validateCall(name,normalized.value),clientContext,resolvedMessage);}catch(error){if(keys.includes(name as any)){const result=this.invalidArgumentsResult(name);invalidArgsRecovered=true;await this.log(tenantId,name,normalized.value,result,'blocked',Date.now(),runId);const entry={call_id:call.id,name,result};results.push(entry);outputs.push(entry);continue;}throw error;}try{const result=await this.executeTool(tenantId,agent.id,name,args,runId),entry={call_id:call.id,name,result:this.compact(result)};results.push(entry);outputs.push(entry);}catch{const entry={call_id:call.id,name,result:{tool_error:true,error_code:'TOOL_EXECUTION_FAILED',message:'A consulta controlada falhou; as demais consultas foram mantidas.'}};results.push(entry);outputs.push(entry);}}state=await this.gateway.generalChatToolContinue({agent,toolResults:outputs,previousResponseId:state.response_id});if(state.done){final={answer:state.answer,model_provider:'openai',llm_final_called:true};break;}}
      if(!final&&state.calls?.length){const outputs=state.calls.map((call:any)=>({call_id:call.id,name:this.internalName(call.name),result:{tool_error:true,error_code:'TOOL_CALL_ROUND_LIMIT_REACHED',message:'Consulta excedeu o limite de rodadas de ferramentas. Refine a pergunta ou consulte por partes.'}}));results.push(...outputs);state=await this.gateway.generalChatToolContinue({agent,toolResults:outputs,previousResponseId:state.response_id});if(state.done)final={answer:state.answer,model_provider:'openai',llm_final_called:true};else if(state.calls?.length)final={answer:'Essa consulta excedeu o limite seguro de ferramentas. Refine a pergunta ou consulte por partes.',model_provider:'system',llm_final_called:false,error_code:'tool_call_round_limit_reached'};}
      let fallbackUsed=false,fallbackReason:string|null=null;
      if(!toolKeys.length&&this.operational(message)){
        const fallback=this.fallbackCall(resolvedMessage,clientContext),result=await this.executeTool(tenantId,agent.id,fallback.name,fallback.arguments,runId);
        toolKeys.push(fallback.name);results.push({call_id:'controlled-fallback',name:fallback.name,result:this.compact(result)});
        fallbackUsed=true;fallbackReason='operational_message_without_tool_call';
      }
      if(!final)final=await this.gateway.generalChatToolFinal({agent,message:resolvedMessage,history:history.slice(-8),toolResults:results,previousResponseId:state.response_id});
      const content=normalizeAssistantOutput(final.answer).content;
      return {content,response:final,output_json:{flow:'controlled_tool_calling',llm_tool_calling_used:true,schema_version:'sprint-17-v1',context_bytes:contextBytes,period_detected:periodDetected,period_source:totalSystem?'total_system':periodDetected?'explicit_user_message':periodSanitized?'removed_not_explicit':'none',period_sanitized:periodSanitized,context_subject_preserved:contextual.preserved,preserved_subject:contextual.subject,sanitized_args:sanitizedArgs,invalid_args_recovered:invalidArgsRecovered,stage_failed:null,error_code:null,error_message_safe:null,content,tool_calls_count:toolKeys.length,fallback_used:fallbackUsed,fallback_reason:fallbackReason,tool_keys_called:toolKeys,main_tool:toolKeys[0]||null,channel:clientContext.channel==='voice'?'voice':'text',client_context:clientContext},observability:{agent_flow:'openai_tool_calling',intent:final.intent||'general_chat',main_tool:toolKeys[0]||null,tool_keys:toolKeys,tool_calls_count:toolKeys.length,llm_called:true,llm_tool_choice:'auto',llm_final_called:final.llm_final_called,cache_hit:false,needs_clarification:false,stage_failed:final.error_code||null,error_code:final.error_code||null,fallback_used:fallbackUsed,fallback_reason:fallbackReason,channel:clientContext.channel==='voice'?'voice':'text',client_context:clientContext,tool_arguments_safe:toolKeys.map(tool_key=>({tool_key})),tool_results_summary:results.map(x=>({tool_key:x.name,keys:Object.keys(x.result||{})})),llm_direct_answer:toolKeys.length===0,no_tool_answer:toolKeys.length===0,analytic_map_used:toolKeys.includes('analytics.map.get'),guidance_used:toolKeys.includes('knowledge.guidance.search')}};
    } catch (error) {
      const gatewayFailure=(error as any)?.generalChatGatewayFailure;
      const failure=gatewayFailure?{agent_flow:'openai_tool_calling',...gatewayFailure,error_code:toolKeys.length===0?'openai_tool_schema_or_gateway_error':gatewayFailure.error_code,provider_error_code:gatewayFailure.error_code,tool_keys:toolKeys}:{agent_flow:'openai_tool_calling',stage_failed:this.stage(error),error_code:this.code(error),error_message_safe:'Não foi possível concluir a consulta controlada.',tool_keys:toolKeys};
      if(runId)await this.db.update('ai_runs',`tenant_id=eq.${tenantId}&id=eq.${runId}`,{output_json:failure});
      Object.assign(error as object,{generalChatFailure:failure});
      throw error;
    }
  }
  private operational(message:string){return isOperationalMessage(message);}
  private fallbackCall(message:string,context:Record<string,unknown>){const page=String(context.page||''),dashboard=String(context.dashboard_id||''),job=String(context.report_job_id||''),report=String(context.report_id||'');if(page==='dashboard'||/dashboard/i.test(message))return{name:'dashboard.get_snapshot',arguments:this.withClientContext('dashboard.get_snapshot',{...(dashboard?{dashboard_id:dashboard}:{})},context,message)};if(page==='report'||/relat[oó]rio/i.test(message))return{name:'reports.get_job_snapshot',arguments:this.withClientContext('reports.get_job_snapshot',{...(job?{report_job_id:job}:report?{report_id:report}:{report_name:this.reportName(message)})},context,message)};if(/dados tratados|resumo (?:dos |de )?(?:dados|registros)/i.test(message))return{name:'treated_data.summary.get',arguments:{client_context:context}};if(/transitime|transit\s*time|tempo\s+(?:m[eé]dio|de\s+tr[aâ]nsito)|prazo/i.test(message))return{name:'analytics.map.get',arguments:{search:'transitime'}};if(/frete|peso|volume|total|status/i.test(message)){const metric=/peso/i.test(message)?'peso_total':/volume/i.test(message)?'volume_total':/status/i.test(message)?'total_entregas':'frete_total';return{name:'analytics.result.get',arguments:{metric_key:metric}};}const identifier=message.match(/\b(?:cte|nf|nota|entrega|manifesto)\s*[#:.-]?\s*([\w.-]{3,})/i)?.[1];return identifier?{name:'operational.record.find',arguments:{identifier_value:identifier,filters:{delivery_number:identifier},limit:5,client_context:context}}:{name:'analytics.context.analyze',arguments:{context_type:'operation',client_context:context}};}
  private contextTool(name:string,message:string,context:Record<string,unknown>){return context.page==='report'&&/relat[oó]rio|geral|per[ií]odo\s+total|transitime|transit\s+time|tempo\s+(?:m[eé]dio\s+de\s+entrega|de\s+tr[aâ]nsito)|prazo/i.test(message)?'reports.get_job_snapshot':name;}
  private withClientContext(name:string,args:Record<string,any>,context:Record<string,unknown>,message:string){const value:Record<string,any>={...args,client_context:context};if(name==='dashboard.get_snapshot'&&context.dashboard_id)value.dashboard_id=context.dashboard_id;if(name==='reports.get_job_snapshot'){if(context.report_job_id)value.report_job_id=context.report_job_id;else if(context.report_id){delete value.report_job_id;value.report_id=context.report_id;}else if(!value.report_name)value.report_name=this.reportName(message);}if(name==='analytics.context.analyze'&&/geral\s+do\s+per[ií]odo\s+total|vis[aã]o\s+geral|opera[cç][aã]o\s+total|desde\s+o\s+in[ií]cio/i.test(message))delete value.period;return value;}
  private reportName(message:string){return message.match(/relat[oó]rio\s+['\"]?([^?'\"]+)/i)?.[1]?.trim().slice(0,120)||undefined;}
  /** Realtime function calls are transported by the browser, but always validated and executed here. */
  async executeRealtimeTool(tenantId:string,agentId:string,name:string,args:unknown,runId:string,clientContext:Record<string,unknown>={}){
    try {const key=this.internalName(name),clean=this.sanitizeArguments(args),normalized=this.normalizeContextualArguments(key,clean.value,'');const validated=this.withClientContext(key,this.validateCall(key,normalized.value),clientContext,'');return this.compact(await this.executeTool(tenantId,agentId,key,validated,runId));}
    catch(error){return error instanceof BadRequestException?{tool_error:true,error_code:'TOOL_NOT_ALLOWED',message:error.message}:this.invalidArgumentsResult();}
  }
  private internalName(name:string){return GENERAL_CHAT_FUNCTION_TO_KEY[name]||name;}
  private explicitPeriod(message:string){return /\b(?:hoje|ontem|esta\s+semana|semana\s+passada|m[eê]s\s+atual|m[eê]s\s+passado|janeiro|fevereiro|mar[cç]o|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro)\b|\b\d{2}\/\d{2}\/\d{4}\b|\b\d{4}-\d{2}-\d{2}\b|\bde\s+\S+(?:\s+\S+){0,2}\s+at[eé]\s+\S+|\bentre\s+\S+(?:\s+\S+){0,2}\s+e\s+\S+/i.test(message);}
  private totalSystemPeriod(message:string){return /\b(?:per[ií]odo\s+total(?:\s+do\s+sistema)?|toda\s+(?:a\s+)?base|base\s+toda|desde\s+o\s+in[ií]cio|todo\s+o\s+hist[oó]rico|agora\s+no\s+total)\b/i.test(message);}
  private normalizeContextualArguments(_name:string,args:Record<string,any>,message:string){const value={...args},hadPeriod=Object.prototype.hasOwnProperty.call(value,'period');if(hadPeriod&&(this.totalSystemPeriod(message)||!this.explicitPeriod(message)))delete value.period;return{value,changed:hadPeriod&&!Object.prototype.hasOwnProperty.call(value,'period'),periodRemoved:hadPeriod&&!Object.prototype.hasOwnProperty.call(value,'period')};}
  private contextualMessage(message:string,history:any[]){const continuation=/^(?:fa[cç]a\s+ent[aã]o|e\s+(?:dele|dela|o\s+transitime)|agora\s+no\s+total|qual\s+o\s+n[uú]mero\s+dessas\s+entregas|detalhe\s+essas\s+entregas)/i.test(message.trim());if(!continuation)return{message,preserved:false,subject:null};const previous=[...history].reverse().find(item=>(!item.role||item.role==='user')&&typeof item.content==='string'&&this.operational(item.content));if(!previous)return{message,preserved:false,subject:null};const subject=String(previous.content).trim().slice(0,500);return{message:`${message}\nAssunto operacional preservado da pergunta anterior: ${subject}`,preserved:true,subject};}
  private validateCall(name:string,args:unknown){
    if(!keys.includes(name as any)||!args||typeof args!=='object'||Array.isArray(args))throw new BadRequestException('Chamada de ferramenta inválida.');
    const value=args as Record<string,any>; this.safe(value);
    const allowed=GENERAL_CHAT_ALLOWED_ARGUMENTS;
    if(Object.keys(value).some(k=>!allowed[name as keyof typeof allowed].includes(k)))throw new BadRequestException('Parâmetro de ferramenta não permitido.');
    if(name==='analytics.result.get'){const metrics=['frete_total','frete_medio','peso_total','volume_total','total_entregas','entregas_atrasadas','entregas_canceladas'], breakdowns=['status','customer_name','shipper_name','driver_name','vehicle_plate','route','origin','destination'];if((typeof value.result_key!=='string'||!value.result_key)&&(typeof value.metric_key!=='string'||!metrics.includes(value.metric_key)))throw new BadRequestException('Resultado ou métrica obrigatória.');if(value.metric_key!==undefined&&(!metrics.includes(value.metric_key)))throw new BadRequestException('Métrica inválida.');if(value.breakdown_by!==undefined&&(!breakdowns.includes(value.breakdown_by)))throw new BadRequestException('Agrupamento inválido.');}
    if(name==='analytics.context.analyze'&&!['dashboard','report','customer','driver','vehicle_plate','shipper','operation'].includes(value.context_type))throw new BadRequestException('Contexto inválido.');
    if(name==='operational.record.find'){if(value.identifier_type&&!['delivery_number','cte_number','invoice_number','manifest_number','vehicle_plate'].includes(value.identifier_type))throw new BadRequestException('Identificador inválido.');if(!value.identifier_value&&!value.filters)throw new BadRequestException('Identificador ou filtro obrigatório.');if(value.limit!==undefined&&(!Number.isInteger(value.limit)||value.limit<1||value.limit>5))throw new BadRequestException('Limite inválido.');}
    if(name==='indicators.get_result'&&!this.oneString(value,['id','name']))throw new BadRequestException('Indicador obrigatório.');
    if(name==='treated_data.aggregate_records'){if(!['deliveries_count','occurrences_count','cte_count','sum_freight','sum_weight','volume_count','avg_freight_informed'].includes(value.metric))throw new BadRequestException('Métrica inválida.');if(value.group_by!==undefined&&!['driver_name','customer_name','shipper_name','status','origin_city','origin_state','destination_city','destination_state','origin','destination','route','none'].includes(value.group_by))throw new BadRequestException('Agrupamento inválido.');}
    if(name==='treated_data.search_records'){if(!this.oneString(value,['identifier'])&&!value.filters)throw new BadRequestException('Identificador ou filtro obrigatório.');if(value.limit!==undefined&&(!Number.isInteger(value.limit)||value.limit<1||value.limit>10))throw new BadRequestException('Limite inválido.');}
    if(name==='treated_data.get_record_detail'&&!this.oneString(value,['id']))throw new BadRequestException('Registro obrigatório.');
    for(const key of ['dashboard_id','report_job_id','id','name','identifier'])if(value[key]!==undefined&&(typeof value[key]!=='string'||!value[key].trim()||value[key].length>160))throw new BadRequestException('Identificador inválido.');
    if(value.filters)this.filters(name,value.filters);if(name==='knowledge.guidance.search'&&(typeof value.topic!=='string'||typeof value.user_question!=='string'))throw new BadRequestException('Orientação inválida.');if(value.period)this.period(value.period);return value;
  }
  private sanitizeArguments(args:unknown){const original=JSON.stringify(args);const clean=(value:any):any=>{if(typeof value==='string'){const trimmed=value.trim();return trimmed||undefined;}if(value===null||value===undefined)return undefined;if(Array.isArray(value)){const result=value.map(clean).filter(x=>x!==undefined);return result.length?result:undefined;}if(typeof value==='object'){const result=Object.entries(value).reduce((out,[key,item])=>{const next=clean(item);if(next!==undefined)(out as any)[key]=next;return out;},{} as Record<string,unknown>);return Object.keys(result).length?result:undefined;}return value;};const hadFilters=Boolean(args&&typeof args==='object'&&Object.prototype.hasOwnProperty.call(args,'filters'));const value=(clean(args)||{}) as Record<string,any>;if(hadFilters&&!value.filters)value.filters={};return {value,changed:JSON.stringify(value)!==original};}
  private oneString(value:Record<string,unknown>,keys:string[]){return keys.some(key=>typeof value[key]==='string'&&Boolean(String(value[key]).trim()));}
  private safe(value:any):void {if(typeof value==='string'){if(value.length>500||forbidden.test(value))throw new BadRequestException('Conteúdo não permitido.');return;}if(Array.isArray(value)){value.forEach(x=>this.safe(x));return;}if(value&&typeof value==='object')for(const [k,v] of Object.entries(value)){if(forbidden.test(k))throw new BadRequestException('Campo não permitido.');this.safe(v);}}
  private period(period:any){if(!period||typeof period!=='object'||Array.isArray(period))throw new BadRequestException('Período inválido.');if(period.preset&&!['today','current_week','current_month','previous_month','custom'].includes(period.preset))throw new BadRequestException('Período inválido.');if(period.preset==='custom'&&(!this.date(period.start)||!this.date(period.end)))throw new BadRequestException('Período personalizado inválido.');}
  private date(v:any){return typeof v==='string'&&!Number.isNaN(Date.parse(v));}
  private filters(name:string,filters:any){if(!filters||typeof filters!=='object'||Array.isArray(filters))throw new BadRequestException('Filtros inválidos.');const allowed:string[]=[...GENERAL_CHAT_FILTER_FIELDS.record,...GENERAL_CHAT_FILTER_FIELDS.analytics];if(Object.keys(filters).some(key=>!allowed.includes(key))||Object.values(filters).some(value=>typeof value!=='string'||value.length>160))throw new BadRequestException('Filtro não permitido.');}
  private invalidArgumentsResult(name?:string){const definition=generalChatToolDefinitions().find(tool=>GENERAL_CHAT_FUNCTION_TO_KEY[tool.name]===name);return {tool_error:true,error_code:'INVALID_TOOL_ARGUMENTS',message:'Parâmetros inválidos para esta ferramenta.',allowed_schema_summary:definition?.parameters??{filters:[...GENERAL_CHAT_FILTER_FIELDS.record,...GENERAL_CHAT_FILTER_FIELDS.analytics],metric_key:['frete_total','frete_medio','peso_total','volume_total','total_entregas','entregas_atrasadas','entregas_canceladas'],breakdown_by:['status','customer_name','shipper_name','driver_name','vehicle_plate','route','origin','destination']},retry_instruction:'Refaça a chamada usando apenas os nomes permitidos no schema.'};}
  private async executeTool(t:string,agentId:string,key:string,args:Record<string,any>,runId?:string){
    const started=Date.now();const [tool]=await this.db.select<any[]>('ai_tools',`select=id&tool_key=eq.${key}&is_active=eq.true&limit=1`);const [enabled]=tool?await this.db.select<any[]>('ai_agent_tools',`select=id&tenant_id=eq.${t}&agent_id=eq.${agentId}&tool_id=eq.${tool.id}&is_enabled=eq.true&limit=1`):[];
    if(!enabled){const message='Esta ferramenta não está liberada para este agente ou usuário.';await this.log(t,key,args,{message},'blocked',started,runId,tool?.id);throw new BadRequestException(message);}
    try {const result=await this.tools.execute(t,key,args);await this.log(t,key,args,result,'completed',started,runId,tool.id);return result;}catch(error){await this.log(t,key,args,{message:'Falha controlada ao consultar dados.'},'failed',started,runId,tool.id);throw error;}
  }
  private async log(t:string,key:string,input:any,output:any,status:'completed'|'failed'|'blocked',started:number,runId?:string,toolId?:string){if(!runId)return;await this.db.insert('ai_tool_calls',{tenant_id:t,ai_run_id:runId,tool_id:toolId??null,tool_key:key,input_json:this.compact(input),output_json:this.compact(output),status,duration_ms:Date.now()-started,finished_at:new Date().toISOString()});}
  private stage(error:unknown){return error instanceof BadRequestException?'tool_validation_or_permission':'tool_execution';}
  private code(error:unknown){return error instanceof BadRequestException?'general_chat_tool_blocked':'general_chat_tool_execution_failed';}
  private compact(value:any,depth=0):any {if(value===null||['string','number','boolean'].includes(typeof value))return typeof value==='string'?value.slice(0,1200):value;if(depth>5)return undefined;if(Array.isArray(value))return value.slice(0,20).map(v=>this.compact(v,depth+1));if(value&&typeof value==='object')return Object.entries(value).filter(([k])=>!forbidden.test(k)&&!/(tenant_id|id)$/i.test(k)).slice(0,40).reduce((out,[k,v])=>{const x=this.compact(v,depth+1);if(x!==undefined)(out as any)[k]=x;return out;},{} as any);}
}
