'use client';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { addReportBlock, addReportFilter, archiveReport, deleteReportBlock, deleteReportFilter, getReport, listReportIndicators, listReportNativeFilters, ReportDefinition, updateReport, updateReportBlock, updateReportFilter } from '../../../../../lib/reports-api';
import { createBrowserSupabaseClient } from '../../../../../lib/supabase';

type Indicator = { id: string; source_type: 'native_indicator' | 'custom_indicator'; name: string; module_key?: string; allowed_visual_types: string[] };
type NativeFilter = { key: string; label: string; filter_type: 'date_range' | 'multi_select' };
export default function EditReport() {
 const { id } = useParams<{ id: string }>(); const [t, setT] = useState(''); const [r, setR] = useState<ReportDefinition>(); const [indicators, setIndicators] = useState<Indicator[]>([]); const [catalog, setCatalog] = useState<NativeFilter[]>([]); const [source, setSource] = useState(''); const [visual, setVisual] = useState(''); const [title, setTitle] = useState(''); const [filterKey, setFilterKey] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [values, setValues] = useState(''); const [locked, setLocked] = useState(false); const [override, setOverride] = useState(true); const [required, setRequired] = useState(false); const [error, setError] = useState('');
 const load = async (tenant: string) => { const [report, library, nativeFilters] = await Promise.all([getReport(tenant, id), listReportIndicators(tenant), listReportNativeFilters(tenant)]); setR(report); setIndicators(library.data as Indicator[]); setCatalog(nativeFilters.data); };
 useEffect(() => { createBrowserSupabaseClient().from('users_profile').select('active_tenant_id').maybeSingle().then(({ data }) => { const tenant = (data as { active_tenant_id: string } | null)?.active_tenant_id; if (tenant) { setT(tenant); load(tenant).catch(e => setError(e.message)); } }); }, [id]);
 if (!r) return <p>Carregando...</p>;
 const selected = indicators.find(x => `${x.source_type}:${x.id}` === source); const selectedFilter = catalog.find(x => x.key === filterKey);
 const call = (action: Promise<unknown>) => action.then(() => load(t)).catch(e => setError(e.message));
 return <section className="space-y-5"><h1 className="text-2xl font-bold">Editar relatório</h1>{error && <p className="text-red-600">{error}</p>}
  <div className="rounded bg-white p-4 shadow space-y-3"><h2 className="font-semibold">Informações</h2><label className="block">Nome<input className="ml-2 rounded border p-2" value={r.name} onChange={e => setR({ ...r, name: e.target.value })} /></label><label className="block">Descrição<textarea className="ml-2 rounded border p-2" value={r.description ?? ''} onChange={e => setR({ ...r, description: e.target.value })} /></label><label className="block">Módulo<input className="ml-2 rounded border p-2" value={r.module_key} onChange={e => setR({ ...r, module_key: e.target.value })} /></label><p>Status: <b>{r.status}</b></p><button className="rounded bg-blue-600 px-3 py-2 text-white" onClick={() => call(updateReport(t, id, { name: r.name, description: r.description, module_key: r.module_key }))}>Salvar</button><button className="ml-2 rounded bg-emerald-600 px-3 py-2 text-white" onClick={() => call(updateReport(t, id, { status: 'active' }))}>Ativar</button><button className="ml-2 rounded bg-red-600 px-3 py-2 text-white" onClick={() => archiveReport(t, id).then(() => { window.location.href = '/app/setup/reports'; }).catch(e => setError(e.message))}>Arquivar</button></div>
  <div className="rounded bg-white p-4 shadow space-y-3"><h2 className="font-semibold">Blocos do relatório</h2><label>Indicador<select className="ml-2 border p-2" value={source} onChange={e => { setSource(e.target.value); setVisual(''); }}><option value="">Selecione</option>{indicators.map(x => <option key={`${x.source_type}-${x.id}`} value={`${x.source_type}:${x.id}`}>{x.name} ({x.source_type})</option>)}</select></label>{selected && <div className="text-sm">Indicador: <b>{selected.name}</b>{selected.module_key && <> — módulo: {selected.module_key}</>}<br />Tipos visuais permitidos: {selected.allowed_visual_types.join(', ')}</div>}<label className="block">Tipo visual<select className="ml-2 border p-2" value={visual || selected?.allowed_visual_types[0] || ''} onChange={e => setVisual(e.target.value)}>{(selected?.allowed_visual_types ?? []).map(v => <option key={v} value={v}>{v}</option>)}</select></label><label className="block">Título<input className="ml-2 border p-2" value={title} onChange={e => setTitle(e.target.value)} /></label><button className="rounded border px-3 py-2" disabled={!selected} onClick={() => { const selectedVisual = visual || selected?.allowed_visual_types[0]; if (selected && selectedVisual) call(addReportBlock(t, id, { block_type: selectedVisual, block_key: `bloco-${Date.now()}`, title: title || selected.name, source_type: selected.source_type, source_id: selected.id, visual_type: selectedVisual })); }}>Adicionar bloco</button><ul className="space-y-2">{r.blocks?.map(b => <li className="border-t pt-2" key={b.id}><input className="border p-1" defaultValue={b.title} onBlur={e => { if (e.target.value !== b.title) call(updateReportBlock(t, id, b.id, { title: e.target.value })); }} /> <span className="text-sm">{b.visual_type}</span><button className="ml-2 text-red-600" onClick={() => call(deleteReportBlock(t, id, b.id))}>Remover</button></li>)}</ul></div>
  <div className="rounded bg-white p-4 shadow space-y-3"><h2 className="font-semibold">Filtros do relatório</h2><label>Filtro do catálogo<select className="ml-2 border p-2" value={filterKey} onChange={e => setFilterKey(e.target.value)}><option value="">Selecione</option>{catalog.map(f => <option key={f.key} value={f.key}>{f.label} ({f.filter_type})</option>)}</select></label>{selectedFilter?.filter_type === 'date_range' && <div><label>De <input type="date" className="border p-1" value={from} onChange={e => setFrom(e.target.value)} /></label><label className="ml-2">Até <input type="date" className="border p-1" value={to} onChange={e => setTo(e.target.value)} /></label></div>}{selectedFilter?.filter_type === 'multi_select' && <label className="block">Valores separados por vírgula nesta sprint<input className="ml-2 border p-1" value={values} onChange={e => setValues(e.target.value)} /></label>}<label><input type="checkbox" checked={locked} onChange={e => setLocked(e.target.checked)} /> Travado</label><label className="ml-3"><input type="checkbox" checked={override} onChange={e => setOverride(e.target.checked)} /> Cliente pode alterar</label><label className="ml-3"><input type="checkbox" checked={required} onChange={e => setRequired(e.target.checked)} /> Obrigatório</label><br /><button className="rounded border px-3 py-2" disabled={!selectedFilter} onClick={() => { if (selectedFilter) call(addReportFilter(t, id, { filter_key: selectedFilter.key, label: selectedFilter.label, filter_type: selectedFilter.filter_type, default_value: selectedFilter.filter_type === 'date_range' ? { from, to } : { values: values.split(',').map(x => x.trim()).filter(Boolean) }, locked, user_can_override: override, required })); }}>Adicionar filtro</button><ul className="space-y-2">{r.filters?.map(f => <li className="border-t pt-2" key={f.id}><input className="border p-1" defaultValue={f.label} onBlur={e => { if (e.target.value !== f.label) call(updateReportFilter(t, id, f.id, { label: e.target.value })); }} /> ({f.filter_type}) — {f.locked ? 'travado' : f.user_can_override ? 'editável pelo cliente' : 'fixo'}<button className="ml-2 text-red-600" onClick={() => call(deleteReportFilter(t, id, f.id))}>Remover</button></li>)}</ul></div>
  <div className="rounded bg-white p-4 shadow"><h2 className="font-semibold">Publicação</h2><p>Status atual: {r.status}</p><button className="rounded bg-emerald-600 px-3 py-2 text-white" onClick={() => call(updateReport(t, id, { status: 'active' }))}>Ativar relatório</button><button className="ml-2 rounded bg-red-600 px-3 py-2 text-white" onClick={() => archiveReport(t, id).then(() => { window.location.href = '/app/setup/reports'; }).catch(e => setError(e.message))}>Arquivar relatório</button></div>
 </section>;
}
