import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';

type TableName = 'operation_records'|'transport_records'|'attendance_records'|'finance_records'|'warehouse_records'|'team_records';
type Operation = 'CONTAGEM'|'CONTAGEM_DISTINTA'|'SOMA'|'MÉDIA'|'MÍNIMO'|'MÁXIMO'|'PERCENTUAL'|'RAZÃO_DIVISÃO'|'DISTRIBUIÇÃO_POR_CATEGORIA'|'SÉRIE_TEMPORAL'|'RANKING'|'TEMPO_MÉDIO_ENTRE_DATAS'|'FÓRMULA_CONTROLADA';
type Field = { id:string; tenant_id:string|null; module_key:string; base_table:TableName; field_key:string; label:string; data_type:string; semantic_type:string; allowed_operations:string[]; allowed_filters:string[]; is_dimension:boolean; is_measure:boolean; is_active:boolean };
type MetricOperation = 'CONTAGEM'|'SOMA'|'MÉDIA'|'MÍNIMO'|'MÁXIMO';
type FormulaNode = { type:'number'; value:number }|{ type:'field'; field:string; label:string }|{ type:'function'; name:string; args:FormulaNode[] }|{ type:'binary'; operator:'+'|'-'|'*'|'/'; left:FormulaNode; right:FormulaNode }|{ type:'literal'; value:string };
type Config = { base_table: TableName; operation_key: Operation; primary_field?: string; secondary_field?: string; numerator_field?: string; denominator_field?: string; numerator_operation?: MetricOperation; denominator_operation?: MetricOperation; formula?: string; formula_ast?: FormulaNode; allow_dashboard_period_filter?: boolean; default_date_field?: string; filters?: Array<{ field:string; operator:string; value?: unknown; value_to?: unknown }>; period?: { field?: string; preset?: string; from?: string; to?: string }; grouping?: { dimension_field?: string; metric_field?: string; metric_operation?: MetricOperation; sort?: 'asc'|'desc'; limit?: number } };
const tables = ['operation_records','transport_records','attendance_records','finance_records','warehouse_records','team_records'] as const;
const ops = ['CONTAGEM','CONTAGEM_DISTINTA','SOMA','MÉDIA','MÍNIMO','MÁXIMO','PERCENTUAL','RAZÃO_DIVISÃO','DISTRIBUIÇÃO_POR_CATEGORIA','SÉRIE_TEMPORAL','RANKING','TEMPO_MÉDIO_ENTRE_DATAS','FÓRMULA_CONTROLADA'];
const statuses = ['draft','active','inactive'];
const formats = ['number','currency','percent','decimal','duration','kg','quantity'];
const types = ['KPI numérico','Valor monetário','Percentual','Tempo/duração','Distribuição por categoria','Série temporal','Ranking/tabela'];
const filterOps = ['igual a','diferente de','contém','maior que','menor que','entre','preenchido','não preenchido'];
const metricOps = ['CONTAGEM','SOMA','MÉDIA','MÍNIMO','MÁXIMO'];
const formulaFns = ['SOMA','CONTAGEM','CONTAGEM_SE','MÉDIA','MÍNIMO','MÁXIMO','CONTAGEM_DISTINTA'];
const numericSemantics = ['money','weight','quantity','decimal','number'];
const dimensionSemantics = ['text','enum','status','customer','state','location','person','identifier'];
const blockedFields = ['raw_payload','source_staging_record_id','source_payload_hash','tenant_id','id','created_at','updated_at','deleted_at','staging'];
const friendlyCatalog: Array<{field:string; label:string; aliases?:string[]}> = [
  {field:'freight_value',label:'Valor do frete'}, {field:'gross_weight',label:'Peso total'}, {field:'delivery_number',label:'Quantidade de entregas',aliases:['Entregas']},
  {field:'occurrence_status',label:'Ocorrências'}, {field:'customer_name',label:'Cliente'}, {field:'driver_name',label:'Motorista'}, {field:'destination_state',label:'UF destino'},
  {field:'issued_at',label:'Data de emissão'}, {field:'expected_date',label:'Data prevista'}, {field:'completed_at',label:'Data de entrega'}, {field:'status',label:'Status'},
];

@Injectable()
export class CustomIndicatorsService {
  constructor(private readonly supabase: SupabaseService) {}
  async fields(tenantId:string) { const allowed=new Set(friendlyCatalog.map(f=>f.field)); const data=(await this.catalog(tenantId)).filter(f=>f.base_table==='operation_records' && allowed.has(f.field_key) && !blockedFields.includes(f.field_key)).map(f=>({...f,label:friendlyCatalog.find(x=>x.field===f.field_key)?.label ?? f.label})); return { data }; }
  async list(tenantId:string) { return { data: await this.supabase.select('custom_indicator_definitions', `select=*&tenant_id=eq.${tenantId}&order=updated_at.desc`) }; }
  async detail(tenantId:string,id:string) { return this.get(tenantId,id); }
  async create(tenantId:string,userId:string,body:Record<string,unknown>) { const payload=this.payload(tenantId,userId,body,false); if(payload.status==='active') await this.validate(tenantId, payload.calculation_config as Config); else await this.validateDraft(tenantId, payload.calculation_config as Config); const rows=await this.supabase.insert<Record<string,unknown>[]>('custom_indicator_definitions', payload); return rows[0]; }
  async update(tenantId:string,id:string,userId:string,body:Record<string,unknown>) { await this.get(tenantId,id); const payload=this.payload(tenantId,userId,body,true); if(payload.status==='active') await this.validate(tenantId, payload.calculation_config as Config); else await this.validateDraft(tenantId, payload.calculation_config as Config); const rows=await this.supabase.update<Record<string,unknown>[]>('custom_indicator_definitions', `tenant_id=eq.${tenantId}&id=eq.${id}`, payload); return rows[0]; }
  async status(tenantId:string,id:string,userId:string,body:{status?:string}) { const row=await this.get(tenantId,id) as {calculation_config:Config}; if(!statuses.includes(String(body.status))) throw new BadRequestException('Status inválido.'); if(String(body.status)==='active') await this.validate(tenantId,row.calculation_config); const status=String(body.status); const rows=await this.supabase.update<Record<string,unknown>[]>('custom_indicator_definitions', `tenant_id=eq.${tenantId}&id=eq.${id}`, { status, available_for_dashboard: status==='active', available_for_reports: status==='active', updated_by:userId }); return rows[0]; }
  async library(tenantId:string) { const nativeRows=await this.supabase.select<Record<string,unknown>[]>('native_indicator_definitions','select=*&status=eq.active&order=sort_order.asc'); const custom=await this.supabase.select<Record<string,unknown>[]>('custom_indicator_definitions',`select=*&tenant_id=eq.${tenantId}&status=eq.active&available_for_dashboard=eq.true&order=updated_at.desc`); return { data: [...nativeRows.map((r)=>({...r, source:'native'})), ...custom.map((r)=>({...r, source:'custom'}))] }; }
  async previewUnsaved(tenantId:string,userId:string,body:Record<string,unknown>) { const normalized=this.payload(tenantId,userId,body,true); return this.previewConfig(tenantId, normalized.calculation_config as Config, undefined, userId); }
  async previewSaved(tenantId:string,id:string,userId:string) { const row=await this.get(tenantId,id) as { calculation_config: Config }; return this.previewConfig(tenantId,row.calculation_config,id,userId); }
  private async get(tenantId:string,id:string){ const rows=await this.supabase.select<Record<string,unknown>[]>('custom_indicator_definitions',`select=*&tenant_id=eq.${tenantId}&id=eq.${id}&limit=1`); if(!rows[0]) throw new NotFoundException('Indicador personalizado não encontrado.'); return rows[0]; }
  private payload(tenantId:string,userId:string,b:Record<string,unknown>,partial:boolean){ const status=String(b.status ?? 'draft'); if(!partial && !String(b.name ?? '').trim()) throw new BadRequestException('Nome obrigatório.'); if(!statuses.includes(status)) throw new BadRequestException('Status inválido.'); if(!formats.includes(String(b.value_format))) throw new BadRequestException('Formato inválido.'); if(!types.includes(String(b.indicator_type))) throw new BadRequestException('Tipo inválido.'); const cfg=this.config(b.calculation_config as Record<string,unknown> ?? b); const active=status==='active'; return { tenant_id:tenantId, name:String(b.name ?? '').trim(), description:b.description ? String(b.description) : null, module_key:String(b.module_key), family_key:String(b.family_key ?? 'Operacional'), indicator_type:String(b.indicator_type), value_format:String(b.value_format), base_table:cfg.base_table, operation_key:cfg.operation_key, calculation_config:cfg, formula_preview:this.formula(cfg), status, available_for_dashboard: active && b.available_for_dashboard !== false, available_for_reports: active && b.available_for_reports !== false, updated_by:userId, created_by:userId }; }
  private config(c:Record<string,unknown>):Config{ const table=String(c.base_table || 'operation_records'); const op=String(c.operation_key || 'FÓRMULA_CONTROLADA'); if(!tables.includes(table as TableName)) throw new BadRequestException('Base inválida.'); if(!ops.includes(op)) throw new BadRequestException('Operação inválida.'); return { base_table:table as TableName, operation_key:op as Operation, primary_field:c.primary_field as string, secondary_field:c.secondary_field as string, numerator_field:c.numerator_field as string, denominator_field:c.denominator_field as string, numerator_operation:this.metricOp(c.numerator_operation), denominator_operation:this.metricOp(c.denominator_operation), formula: typeof c.formula === 'string' ? c.formula : undefined, allow_dashboard_period_filter:c.allow_dashboard_period_filter === true, default_date_field:c.default_date_field as string, filters:Array.isArray(c.filters)?c.filters as Config['filters']:[], period:c.period as Config['period'], grouping:c.grouping as Config['grouping'] }; }
  private async validateDraft(tenantId:string,cfg:Config){ if(cfg.operation_key==='FÓRMULA_CONTROLADA' && !String(cfg.formula ?? '').trim()) return {cat:await this.catalog(tenantId),by:new Map<string,Field>()}; return this.validate(tenantId,cfg); }
  private async validate(tenantId:string,cfg:Config){ if(cfg.operation_key==='FÓRMULA_CONTROLADA') return this.validateFormulaConfig(tenantId,cfg); const cat=await this.catalog(tenantId); const by=new Map(cat.filter(f=>f.base_table===cfg.base_table).map(f=>[f.field_key,f])); const used=[cfg.primary_field,cfg.secondary_field,cfg.numerator_field,cfg.denominator_field,cfg.grouping?.dimension_field,cfg.grouping?.metric_field,cfg.period?.field,...(cfg.filters??[]).map(f=>f.field)].filter(Boolean) as string[]; if(used.some(f=>blockedFields.includes(f))) throw new BadRequestException('Campo não permitido para indicador.'); for(const f of used) if(!by.has(f)) throw new BadRequestException('Campo fora do catálogo controlado.'); const primary=cfg.primary_field ? by.get(cfg.primary_field) : undefined; const secondary=cfg.secondary_field ? by.get(cfg.secondary_field) : undefined; const metric=cfg.grouping?.metric_field ? by.get(cfg.grouping.metric_field) : undefined; const dimension=cfg.grouping?.dimension_field ? by.get(cfg.grouping.dimension_field) : undefined; if(['SOMA','MÉDIA','MÍNIMO','MÁXIMO'].includes(cfg.operation_key) && !this.numeric(primary)) throw new BadRequestException(primary ? `${primary.label} é um campo de texto e não pode ser usado em ${cfg.operation_key}.` : 'Escolha um campo numérico para esta operação.'); if(cfg.operation_key==='CONTAGEM' && !primary) throw new BadRequestException('Escolha um campo para contagem.'); if(cfg.operation_key==='CONTAGEM_DISTINTA' && !this.dimension(primary)) throw new BadRequestException('Escolha uma dimensão para contagem distinta.'); if(['RAZÃO_DIVISÃO','PERCENTUAL'].includes(cfg.operation_key) && (!this.metric(cfg.numerator_operation, by.get(cfg.numerator_field??'')) || !this.metric(cfg.denominator_operation, by.get(cfg.denominator_field??'')))) throw new BadRequestException('Para razão, configure numerador e denominador com métricas compatíveis.'); if(cfg.operation_key==='DISTRIBUIÇÃO_POR_CATEGORIA') { if(!this.metric(cfg.grouping?.metric_operation, metric)) throw new BadRequestException('Escolha uma métrica compatível para a distribuição.'); if(!this.dimension(dimension)) throw new BadRequestException('Para distribuição, escolha uma dimensão de agrupamento.'); } if(cfg.operation_key==='SÉRIE_TEMPORAL') { if(!this.date(primary)) throw new BadRequestException('Série temporal exige um campo de data.'); if(!this.metric(cfg.grouping?.metric_operation, metric)) throw new BadRequestException('Série temporal exige uma métrica compatível.'); } if(cfg.operation_key==='TEMPO_MÉDIO_ENTRE_DATAS' && (!this.date(primary)||!this.date(secondary))) throw new BadRequestException('Tempo médio entre datas exige campo inicial e final de data.'); for(const flt of cfg.filters??[]) { const field=by.get(flt.field); if(!field || !filterOps.includes(flt.operator) || !field.allowed_filters.includes(flt.operator)) throw new BadRequestException('Filtro incompatível com o catálogo.'); } return {cat,by}; }
  private async validateFormulaConfig(tenantId:string,cfg:Config){ if(cfg.base_table!=='operation_records') throw new BadRequestException('Indicadores personalizados usam somente campos operacionais tratados nesta sprint.'); if((cfg.filters??[]).length || cfg.period) throw new BadRequestException('Filtros complexos não fazem parte da criação do indicador.'); const cat=await this.catalog(tenantId); const by=this.formulaFieldMap(cat); if(cfg.default_date_field && !by.has(cfg.default_date_field)) throw new BadRequestException('Campo de data padrão fora do catálogo controlado.'); cfg.formula_ast=this.parseFormula(String(cfg.formula ?? ''),by); return {cat,by}; }
  private async previewConfig(tenantId:string,cfg:Config,indicatorId?:string,userId?:string){ try { const {by}=await this.validate(tenantId,cfg); const rows=await this.supabase.select<Record<string,unknown>[]>(cfg.base_table,`select=*&tenant_id=eq.${tenantId}&deleted_at=is.null&limit=10000`); if(!rows.length) return this.result('empty',null,[],[],0,cfg,by,'Dados ainda não disponíveis para este indicador.'); const r=this.calculate(rows,cfg); const res=this.result('success',r.value,r.series,r.table,rows.length,cfg,by,'Fórmula testada com segurança.'); await this.log(tenantId,indicatorId,userId,res); return res; } catch { return this.result('failed',null,[],[],0,cfg,new Map(),'Não foi possível calcular este indicador. Revise a fórmula.'); } }
  private calculate(rows:Record<string,unknown>[],c:Config){ if(c.operation_key==='FÓRMULA_CONTROLADA') return {value:this.evalNode(c.formula_ast as FormulaNode,rows),series:[],table:[]}; const f=c.primary_field??'id'; const nums=rows.map(r=>Number(r[f])).filter(Number.isFinite); if(c.operation_key==='CONTAGEM') return {value:rows.length,series:[],table:[]}; if(c.operation_key==='CONTAGEM_DISTINTA') return {value:new Set(rows.map(r=>r[f])).size,series:[],table:[]}; if(c.operation_key==='SOMA') return {value:nums.reduce((a,b)=>a+b,0),series:[],table:[]}; if(c.operation_key==='MÉDIA') return {value:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null,series:[],table:[]}; if(c.operation_key==='MÍNIMO') return {value:nums.length?Math.min(...nums):null,series:[],table:[]}; if(c.operation_key==='MÁXIMO') return {value:nums.length?Math.max(...nums):null,series:[],table:[]}; if(c.operation_key==='RAZÃO_DIVISÃO'||c.operation_key==='PERCENTUAL') { const n=this.aggregate(rows,c.numerator_operation,c.numerator_field); const d=this.aggregate(rows,c.denominator_operation,c.denominator_field); return {value:d?(n/d)*(c.operation_key==='PERCENTUAL'?100:1):null,series:[],table:[]}; } return {value:null,series:[],table:[]}; }
  private formulaFieldMap(cat:Field[]){ const allowed=new Map<string,Field>(); for(const item of friendlyCatalog){ const field=cat.find(f=>f.base_table==='operation_records'&&f.field_key===item.field&&!blockedFields.includes(f.field_key)); if(field) allowed.set(field.field_key,{...field,label:item.label}); } return allowed; }
  private parseFormula(input:string,by:Map<string,Field>):FormulaNode{ const text=input.trim(); if(!text) throw new BadRequestException('Fórmula obrigatória.'); if(/\b(SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|UNION|FROM|WHERE|eval|Function|javascript|raw_payload|staging|tenant_id)\b/i.test(text)) throw new BadRequestException('Fórmula contém termo bloqueado.'); const tokens=this.tokenize(text,by); let i=0; const peek=()=>tokens[i]; const take=()=>tokens[i++]; const expr=():FormulaNode=>{let node=term(); while(peek()==='+'||peek()==='-') node={type:'binary',operator:take() as '+'|'-',left:node,right:term()}; return node;}; const term=():FormulaNode=>{let node=factor(); while(peek()==='*'||peek()==='/') node={type:'binary',operator:take() as '*'|'/',left:node,right:factor()}; return node;}; const factor=():FormulaNode=>{const t=take(); if(!t) throw new BadRequestException('Fórmula incompleta.'); if(t==='('){const n=expr(); if(take()!==')') throw new BadRequestException('Parênteses inválidos.'); return n;} if(/^\d+(\.\d+)?$/.test(t)) return {type:'number',value:Number(t)}; const fn=String(t).toUpperCase(); if(formulaFns.includes(fn)){ if(take()!=='(') throw new BadRequestException('Função inválida.'); const args:FormulaNode[]=[]; if(peek()!==')'){ do { args.push(expr()); } while(peek()===',' && take()); } if(take()!==')') throw new BadRequestException('Função com parênteses inválidos.'); this.validateFunctionNode(fn,args,by); return {type:'function',name:fn,args}; } const field=[...by.values()].find(f=>f.label===t || f.field_key===t); if(field) return {type:'field',field:field.field_key,label:field.label}; if(t.toLowerCase()==='preenchido') return {type:'literal',value:'preenchido'}; throw new BadRequestException('Campo fora do catálogo controlado.');}; const parsed=expr(); if(i!==tokens.length) throw new BadRequestException('Fórmula inválida.'); return parsed; }
  private tokenize(text:string,by:Map<string,Field>){ const labels=[...by.values()].flatMap(f=>[f.label,f.field_key,...(friendlyCatalog.find(x=>x.field===f.field_key)?.aliases??[])]).sort((a,b)=>b.length-a.length); const tokens:string[]=[]; let i=0; while(i<text.length){ if(/\s/.test(text[i])){i++; continue;} const single='()+-*/,'; if(single.includes(text[i])){tokens.push(text[i++]); continue;} const label=labels.find(l=>text.slice(i).toLowerCase().startsWith(l.toLowerCase())); if(label){tokens.push(label); i+=label.length; continue;} const m=text.slice(i).match(/^\d+(?:[.,]\d+)?|^[A-ZÁÉÍÓÚÃÕÇ_]+/i); if(!m) throw new BadRequestException('Use apenas funções, campos, números e operadores permitidos.'); tokens.push(m[0].replace(',','.')); i+=m[0].length; } return tokens; }
  private validateFunctionNode(name:string,args:FormulaNode[],by:Map<string,Field>){ if(name==='CONTAGEM_SE'){ if(args.length!==2) throw new BadRequestException('CONTAGEM_SE exige campo e condição.'); return; } if(args.length!==1) throw new BadRequestException(`${name} exige um argumento.`); if(['SOMA','MÉDIA','MÍNIMO','MÁXIMO'].includes(name)){ const f=this.firstField(args[0]); if(!f || !this.numeric(by.get(f))) throw new BadRequestException(`${name} exige campo numérico.`); } }
  private firstField(node:FormulaNode):string|undefined{ if(node.type==='field') return node.field; if(node.type==='function') return node.args.map(a=>this.firstField(a)).find(Boolean); if(node.type==='binary') return this.firstField(node.left) ?? this.firstField(node.right); return undefined; }
  private evalNode(node:FormulaNode,rows:Record<string,unknown>[]):number|null{ if(node.type==='number') return node.value; if(node.type==='field') return this.aggregate(rows,'SOMA',node.field); if(node.type==='literal') return null; if(node.type==='binary'){ const l=this.evalNode(node.left,rows); const r=this.evalNode(node.right,rows); if(l===null||r===null) return null; if(node.operator==='+') return l+r; if(node.operator==='-') return l-r; if(node.operator==='*') return l*r; return r===0 ? null : l/r; } const field=this.firstField(node); if(node.name==='CONTAGEM') return rows.length; if(node.name==='CONTAGEM_DISTINTA') return new Set(rows.map(r=>String(r[field??'']))).size; if(node.name==='CONTAGEM_SE') return rows.filter(r=>{const v=r[field??'']; return v!==null&&v!==undefined&&v!=='';}).length; return this.aggregate(rows,node.name as MetricOperation,field); }
  private formula(c:Config){ return c.operation_key==='FÓRMULA_CONTROLADA' ? String(c.formula ?? '') : `${c.operation_key}(${c.primary_field ?? 'Registros'})`; }
  private metricOp(value:unknown):MetricOperation{ const op=String(value ?? 'SOMA'); return metricOps.includes(op) ? op as MetricOperation : 'SOMA'; }
  private numeric(field?:Field){ return !!field && (field.is_measure || field.data_type==='number' || numericSemantics.includes(field.semantic_type)); }
  private date(field?:Field){ return !!field && (field.data_type==='date' || field.data_type==='datetime' || field.semantic_type==='date'); }
  private dimension(field?:Field){ return !!field && field.is_dimension && (field.data_type==='text' || dimensionSemantics.includes(field.semantic_type)); }
  private metric(op:unknown,field?:Field){ return String(op)==='CONTAGEM' ? !!field : this.numeric(field); }
  private aggregate(rows:Record<string,unknown>[],op?:MetricOperation,field?:string){ if(op==='CONTAGEM') return rows.length; const nums=rows.map(r=>Number(r[field??''])).filter(Number.isFinite); if(op==='MÉDIA') return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0; if(op==='MÍNIMO') return nums.length?Math.min(...nums):0; if(op==='MÁXIMO') return nums.length?Math.max(...nums):0; return nums.reduce((a,b)=>a+b,0); }
  private result(status:string,value:unknown,series:Record<string,unknown>[],table:Record<string,unknown>[],records:number,cfg:Config,by:Map<string,Field>,message:string){ const used=this.usedFields(cfg.formula_ast).concat([cfg.primary_field,cfg.secondary_field,cfg.numerator_field,cfg.denominator_field,cfg.grouping?.dimension_field,cfg.grouping?.metric_field].filter(Boolean) as string[]); return { status, value, series, table, records_considered:records, formula_preview:this.formula(cfg), fields_used:[...new Set(used)].map(f=>({field:f,label:by.get(f)?.label??f})), filters_used:[], message }; }
  private usedFields(node?:FormulaNode):string[]{ if(!node) return []; if(node.type==='field') return [node.field]; if(node.type==='function') return node.args.flatMap(a=>this.usedFields(a)); if(node.type==='binary') return [...this.usedFields(node.left),...this.usedFields(node.right)]; return []; }
  private async catalog(tenantId:string){ return this.supabase.select<Field[]>('indicator_field_catalog',`select=*&is_active=eq.true&or=(tenant_id.is.null,tenant_id.eq.${tenantId})&order=base_table.asc,label.asc`); }
  private async log(tenantId:string,custom_indicator_id:string|undefined,user_id:string|undefined,result:Record<string,unknown>){ await this.supabase.insert('custom_indicator_calculation_logs',{tenant_id:tenantId,custom_indicator_id:custom_indicator_id??null,user_id:user_id??null,status:result.status,records_considered:result.records_considered,formula_preview:result.formula_preview,fields_used:result.fields_used,filters_used:[],result_preview:{value:result.value,series:result.series,table:result.table},message:result.message}); }
}
