import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';

type TableName = 'operation_records'|'transport_records'|'attendance_records'|'finance_records'|'warehouse_records'|'team_records';
type Operation = 'CONTAGEM'|'CONTAGEM_DISTINTA'|'SOMA'|'MÉDIA'|'MÍNIMO'|'MÁXIMO'|'PERCENTUAL'|'RAZÃO_DIVISÃO'|'DISTRIBUIÇÃO_POR_CATEGORIA'|'SÉRIE_TEMPORAL'|'RANKING'|'TEMPO_MÉDIO_ENTRE_DATAS';
type Field = { id:string; tenant_id:string|null; module_key:string; base_table:TableName; field_key:string; label:string; data_type:string; semantic_type:string; allowed_operations:string[]; allowed_filters:string[]; is_dimension:boolean; is_measure:boolean; is_active:boolean };
type Config = { base_table: TableName; operation_key: Operation; primary_field?: string; secondary_field?: string; numerator_field?: string; denominator_field?: string; filters?: Array<{ field:string; operator:string; value?: unknown; value_to?: unknown }>; period?: { field?: string; preset?: string; from?: string; to?: string }; grouping?: { dimension_field?: string; metric_field?: string; sort?: 'asc'|'desc'; limit?: number } };
const tables = ['operation_records','transport_records','attendance_records','finance_records','warehouse_records','team_records'] as const;
const ops = ['CONTAGEM','CONTAGEM_DISTINTA','SOMA','MÉDIA','MÍNIMO','MÁXIMO','PERCENTUAL','RAZÃO_DIVISÃO','DISTRIBUIÇÃO_POR_CATEGORIA','SÉRIE_TEMPORAL','RANKING','TEMPO_MÉDIO_ENTRE_DATAS'];
const statuses = ['draft','active','inactive'];
const formats = ['number','currency','percent','decimal','duration','kg','quantity'];
const types = ['KPI numérico','Valor monetário','Percentual','Tempo/duração','Distribuição por categoria','Série temporal','Ranking/tabela'];
const filterOps = ['igual a','diferente de','contém','maior que','menor que','entre','preenchido','não preenchido'];

@Injectable()
export class CustomIndicatorsService {
  constructor(private readonly supabase: SupabaseService) {}
  async fields(tenantId:string) { const data = await this.catalog(tenantId); return { data }; }
  async list(tenantId:string) { return { data: await this.supabase.select('custom_indicator_definitions', `select=*&tenant_id=eq.${tenantId}&order=updated_at.desc`) }; }
  async detail(tenantId:string,id:string) { const row = await this.get(tenantId,id); return row; }
  async create(tenantId:string,userId:string,body:Record<string,unknown>) { const payload=this.payload(tenantId,userId,body,false); await this.validate(tenantId, payload.calculation_config as Config); const rows=await this.supabase.insert<Record<string,unknown>[]>('custom_indicator_definitions', payload); return rows[0]; }
  async update(tenantId:string,id:string,userId:string,body:Record<string,unknown>) { await this.get(tenantId,id); const payload=this.payload(tenantId,userId,body,true); await this.validate(tenantId, payload.calculation_config as Config); const rows=await this.supabase.update<Record<string,unknown>[]>('custom_indicator_definitions', `tenant_id=eq.${tenantId}&id=eq.${id}`, payload); return rows[0]; }
  async status(tenantId:string,id:string,userId:string,body:{status?:string}) { await this.get(tenantId,id); if(!statuses.includes(String(body.status))) throw new BadRequestException('Status inválido.'); const status=String(body.status); const rows=await this.supabase.update<Record<string,unknown>[]>('custom_indicator_definitions', `tenant_id=eq.${tenantId}&id=eq.${id}`, { status, available_for_dashboard: status==='active', available_for_reports: status==='active', updated_by:userId }); return rows[0]; }
  async library(tenantId:string) { const nativeRows=await this.supabase.select<Record<string,unknown>[]>('native_indicator_definitions','select=*&status=eq.active&order=sort_order.asc'); const custom=await this.supabase.select<Record<string,unknown>[]>('custom_indicator_definitions',`select=*&tenant_id=eq.${tenantId}&status=eq.active&available_for_dashboard=eq.true&order=updated_at.desc`); return { data: [...nativeRows.map((r)=>({...r, source:'native'})), ...custom.map((r)=>({...r, source:'custom'}))] }; }
  async previewUnsaved(tenantId:string,userId:string,body:Record<string,unknown>) { const normalized=this.payload(tenantId,userId,body,true); return this.previewConfig(tenantId, normalized.calculation_config as Config, undefined, userId); }
  async previewSaved(tenantId:string,id:string,userId:string) { const row=await this.get(tenantId,id) as { calculation_config: Config }; return this.previewConfig(tenantId,row.calculation_config,id,userId); }
  private async get(tenantId:string,id:string){ const rows=await this.supabase.select<Record<string,unknown>[]>('custom_indicator_definitions',`select=*&tenant_id=eq.${tenantId}&id=eq.${id}&limit=1`); if(!rows[0]) throw new NotFoundException('Indicador personalizado não encontrado.'); return rows[0]; }
  private payload(tenantId:string,userId:string,b:Record<string,unknown>,partial:boolean){ const status=String(b.status ?? 'draft'); if(!partial && !String(b.name ?? '').trim()) throw new BadRequestException('Nome obrigatório.'); if(!statuses.includes(status)) throw new BadRequestException('Status inválido.'); if(!formats.includes(String(b.value_format))) throw new BadRequestException('Formato inválido.'); if(!types.includes(String(b.indicator_type))) throw new BadRequestException('Tipo inválido.'); const cfg=this.config(b.calculation_config as Record<string,unknown> ?? b); const active=status==='active'; return { tenant_id:tenantId, name:String(b.name ?? '').trim(), description:b.description ? String(b.description) : null, module_key:String(b.module_key), family_key:String(b.family_key ?? 'custom'), indicator_type:String(b.indicator_type), value_format:String(b.value_format), base_table:cfg.base_table, operation_key:cfg.operation_key, calculation_config:cfg, formula_preview:this.formula(cfg), status, available_for_dashboard: active && b.available_for_dashboard !== false, available_for_reports: active && b.available_for_reports !== false, updated_by:userId, created_by:userId }; }
  private config(c:Record<string,unknown>):Config{ const table=String(c.base_table); const op=String(c.operation_key); if(!tables.includes(table as TableName)) throw new BadRequestException('Base inválida.'); if(!ops.includes(op)) throw new BadRequestException('Operação inválida.'); return { base_table:table as TableName, operation_key:op as Operation, primary_field:c.primary_field as string, secondary_field:c.secondary_field as string, numerator_field:c.numerator_field as string, denominator_field:c.denominator_field as string, filters:Array.isArray(c.filters)?c.filters as Config['filters']:[], period:c.period as Config['period'], grouping:c.grouping as Config['grouping'] }; }
  private async validate(tenantId:string,cfg:Config){ const cat=await this.catalog(tenantId); const by=new Map(cat.filter(f=>f.base_table===cfg.base_table).map(f=>[f.field_key,f])); const used=[cfg.primary_field,cfg.secondary_field,cfg.numerator_field,cfg.denominator_field,cfg.grouping?.dimension_field,cfg.grouping?.metric_field,cfg.period?.field,...(cfg.filters??[]).map(f=>f.field)].filter(Boolean) as string[]; if(used.some(f=>['raw_payload','source_staging_record_id','source_payload_hash','tenant_id','id','created_at','updated_at'].includes(f))) throw new BadRequestException('Campo não permitido para indicador.'); for(const f of used) if(!by.has(f)) throw new BadRequestException('Campo fora do catálogo controlado.'); const primary=cfg.primary_field ? by.get(cfg.primary_field) : undefined; if(primary && !primary.allowed_operations.includes(cfg.operation_key)) throw new BadRequestException('Operação incompatível com o campo.'); for(const flt of cfg.filters??[]) { const field=by.get(flt.field); if(!field || !filterOps.includes(flt.operator) || !field.allowed_filters.includes(flt.operator)) throw new BadRequestException('Filtro incompatível com o catálogo.'); } return {cat,by}; }
  private async previewConfig(tenantId:string,cfg:Config,indicatorId?:string,userId?:string){ try { const {by}=await this.validate(tenantId,cfg); const rows=await this.supabase.select<Record<string,unknown>[]>(cfg.base_table,`select=*&tenant_id=eq.${tenantId}&deleted_at=is.null&limit=10000`); const filtered=rows.filter(r=>this.matchAll(r,cfg)); if(!rows.length) return this.result('empty',null,[],[],0,cfg,by,'Dados ainda não disponíveis para este indicador. Mapeie os campos necessários na integração ou escolha outro campo.'); if(!filtered.length) return this.result('insufficient_data',null,[],[],0,cfg,by,'Não há registros tratados suficientes para calcular este indicador.'); const r=this.calculate(filtered,cfg); const res=this.result('success',r.value,r.series,r.table,filtered.length,cfg,by,'Prévia calculada com sucesso.'); await this.log(tenantId,indicatorId,userId,res); return res; } catch { return this.result('failed',null,[],[],0,cfg,new Map(),'Não foi possível calcular este indicador. Revise a configuração.'); } }
  private calculate(rows:Record<string,unknown>[],c:Config){ const f=c.primary_field??'id'; const nums=rows.map(r=>Number(r[f])).filter(Number.isFinite); if(c.operation_key==='CONTAGEM') return {value:rows.length,series:[],table:[]}; if(c.operation_key==='CONTAGEM_DISTINTA') return {value:new Set(rows.map(r=>r[f])).size,series:[],table:[]}; if(c.operation_key==='SOMA') return {value:nums.reduce((a,b)=>a+b,0),series:[],table:[]}; if(c.operation_key==='MÉDIA') return {value:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null,series:[],table:[]}; if(c.operation_key==='MÍNIMO') return {value:nums.length?Math.min(...nums):null,series:[],table:[]}; if(c.operation_key==='MÁXIMO') return {value:nums.length?Math.max(...nums):null,series:[],table:[]}; if(c.operation_key==='RAZÃO_DIVISÃO') { const n=rows.map(r=>Number(r[c.numerator_field??f])).filter(Number.isFinite).reduce((a,b)=>a+b,0); const d=rows.map(r=>Number(r[c.denominator_field??c.secondary_field??'id'])).filter(Number.isFinite).reduce((a,b)=>a+b,0) || rows.length; return {value:d?n/d:null,series:[],table:[]}; } if(c.operation_key==='PERCENTUAL') return {value:rows.length?100:null,series:[],table:[]}; if(c.operation_key==='TEMPO_MÉDIO_ENTRE_DATAS') { const diffs=rows.map(r=>Date.parse(String(r[c.secondary_field??'']))-Date.parse(String(r[f]))).filter(Number.isFinite).filter(n=>n>=0); return {value:diffs.length?diffs.reduce((a,b)=>a+b,0)/diffs.length/3600000:null,series:[],table:[]}; } const dim=c.grouping?.dimension_field??f; const metric=c.grouping?.metric_field; const map=new Map<string,number>(); rows.forEach(r=>map.set(String(r[dim]??'Não informado'),(map.get(String(r[dim]??'Não informado'))??0)+(metric?(Number(r[metric])||0):1))); const table=[...map.entries()].map(([label,value])=>({label,value})).sort((a,b)=>(c.grouping?.sort==='asc'?a.value-b.value:b.value-a.value)).slice(0,c.grouping?.limit??20); return {value:null,series:table,table:c.operation_key==='RANKING'?table:[]}; }
  private matchAll(row:Record<string,unknown>,c:Config){ return (c.filters??[]).every(f=>this.match(row[f.field],f.operator,f.value,f.value_to)); }
  private match(v:unknown,op:string,value?:unknown,to?:unknown){ if(op==='preenchido') return v!==null&&v!==undefined&&v!==''; if(op==='não preenchido') return v===null||v===undefined||v===''; if(op==='igual a') return String(v)===String(value); if(op==='diferente de') return String(v)!==String(value); if(op==='contém') return String(v??'').toLowerCase().includes(String(value??'').toLowerCase()); if(op==='maior que') return Number(v)>Number(value); if(op==='menor que') return Number(v)<Number(value); if(op==='entre') return Number(v)>=Number(value)&&Number(v)<=Number(to); return false; }
  private formula(c:Config){ const label=(f?:string)=>f?f.replace(/_/g,' '):'Registros'; if(c.operation_key==='RAZÃO_DIVISÃO') return `SOMA(${label(c.numerator_field)}) / SOMA(${label(c.denominator_field)})`; if(c.operation_key==='TEMPO_MÉDIO_ENTRE_DATAS') return `TEMPO MÉDIO(${label(c.primary_field)} → ${label(c.secondary_field)})`; return `${c.operation_key}(${label(c.primary_field ?? c.grouping?.metric_field)})`; }
  private result(status:string,value:unknown,series:Record<string,unknown>[],table:Record<string,unknown>[],records:number,cfg:Config,by:Map<string,Field>,message:string){ const used=[cfg.primary_field,cfg.secondary_field,cfg.numerator_field,cfg.denominator_field,cfg.grouping?.dimension_field,cfg.grouping?.metric_field].filter(Boolean) as string[]; return { status, value, series, table, records_considered:records, formula_preview:this.formula(cfg), fields_used:used.map(f=>({field:f,label:by.get(f)?.label??f})), filters_used:cfg.filters??[], message }; }
  private async catalog(tenantId:string){ return this.supabase.select<Field[]>('indicator_field_catalog',`select=*&is_active=eq.true&or=(tenant_id.is.null,tenant_id.eq.${tenantId})&order=base_table.asc,label.asc`); }
  private async log(tenantId:string,custom_indicator_id:string|undefined,user_id:string|undefined,result:Record<string,unknown>){ await this.supabase.insert('custom_indicator_calculation_logs',{tenant_id:tenantId,custom_indicator_id:custom_indicator_id??null,user_id:user_id??null,status:result.status,records_considered:result.records_considered,formula_preview:result.formula_preview,fields_used:result.fields_used,filters_used:result.filters_used,result_preview:{value:result.value,series:result.series,table:result.table},message:result.message}); }
}
