-- Configura indicadores nativos priorizados para o motor genérico baseado em calculation_config.
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"id"}'::jsonb where indicator_key='total_native_records';
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"gross_weight"}'::jsonb where indicator_key='total_weight_informed';
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"freight_value"}'::jsonb where indicator_key='total_freight_informed';
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"volume_count"}'::jsonb where indicator_key='total_volumes_informed';
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"total_value"}'::jsonb where indicator_key='total_value_informed';
update public.native_indicator_definitions set calculation_config='{"table":"operation_records","field":"cubed_weight"}'::jsonb where indicator_key in ('total_cubed_weight','transport_total_cubed_weight');

insert into public.native_indicator_definitions (module_key,family_key,indicator_key,name,description,indicator_type,visualization_type,value_format,calculation_type,calculation_config,required_fields,optional_fields,availability_rules,sort_order) values
('core','peso_volume','total_cubed_weight','Peso cubado total','Somatório do peso cubado informado na base nativa tratada.','kpi','decimal','kg','sum','{"table":"operation_records","field":"cubed_weight"}'::jsonb,'[{"key":"cubed_weight","label":"Peso cubado","any_of":[{"table":"operation_records","field":"cubed_weight"}]}]'::jsonb,'[]'::jsonb,'{}'::jsonb,12),
('core','valor','value_per_kg','Valor por kg','Valor total dividido pelo peso bruto informado.','kpi','number','currency','ratio','{"numerator":{"table":"operation_records","operation":"sum","field":"total_value"},"denominator":{"table":"operation_records","operation":"sum","field":"gross_weight"}}'::jsonb,'[{"key":"total_value","label":"Valor total","any_of":[{"table":"operation_records","field":"total_value"}]},{"key":"gross_weight","label":"Peso bruto","any_of":[{"table":"operation_records","field":"gross_weight"}]}]'::jsonb,'[]'::jsonb,'{}'::jsonb,14)
on conflict (module_key, indicator_key) do update set family_key=excluded.family_key,name=excluded.name,description=excluded.description,indicator_type=excluded.indicator_type,visualization_type=excluded.visualization_type,value_format=excluded.value_format,calculation_type=excluded.calculation_type,calculation_config=excluded.calculation_config,required_fields=excluded.required_fields,optional_fields=excluded.optional_fields,availability_rules=excluded.availability_rules,sort_order=excluded.sort_order,updated_at=now();

update public.native_indicator_definitions set calculation_config='{"numerator":{"table":"operation_records","operation":"sum","field":"freight_value"},"denominator":{"table":"operation_records","operation":"sum","field":"gross_weight"}}'::jsonb where indicator_key='freight_per_kg';

update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','customer_name'),'limit',50) where indicator_key in ('records_by_customer','transport_deliveries_by_customer');
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','document_type'),'limit',50) where indicator_key='records_by_document_type';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','origin_state'),'limit',50) where indicator_key='records_by_origin_state';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','destination_state'),'limit',50) where indicator_key='records_by_destination_state';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','status'),'limit',50) where indicator_key='transport_deliveries_by_status';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','gross_weight','aggregation','sum'),'dimension',jsonb_build_object('table','operation_records','field','destination_state'),'limit',50) where indicator_key='weight_by_destination_state';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','volume_count','aggregation','sum'),'dimension',jsonb_build_object('table','operation_records','field','customer_name'),'limit',50) where indicator_key='transport_volumes_by_customer';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','driver_name'),'limit',50) where indicator_key='transport_deliveries_by_driver';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','operation_records','field','vehicle_plate'),'limit',50) where indicator_key='transport_deliveries_by_vehicle';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','transport_records','field','route_name'),'limit',50) where indicator_key='transport_deliveries_by_route';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','id','aggregation','count'),'dimension',jsonb_build_object('table','transport_records','field','vehicle_type'),'limit',50) where indicator_key='transport_deliveries_by_vehicle_type';
update public.native_indicator_definitions set calculation_config=jsonb_build_object('metric',jsonb_build_object('table','operation_records','field','gross_weight','aggregation','sum'),'dimension',jsonb_build_object('table','transport_records','field','route_name'),'limit',50) where indicator_key='transport_weight_by_route';

update public.native_indicator_definitions set calculation_config='{"denominator":{"filter":[{"table":"operation_records","field":"completed_at","operator":"not_null"},{"table":"operation_records","field":"expected_date","operator":"not_null"}]},"numerator":{"filter":[{"table":"operation_records","field":"completed_at","operator":"lte_field","compare_field":"expected_date"}]}}'::jsonb where indicator_key='transport_otd';
update public.native_indicator_definitions set calculation_config='{"date_pairs":[{"start":{"table":"operation_records","field":"issued_at"},"end":{"table":"operation_records","field":"completed_at"}},{"start":{"table":"operation_records","field":"issued_at"},"end":{"table":"transport_records","field":"delivered_at"}},{"start":{"table":"transport_records","field":"collected_at"},"end":{"table":"transport_records","field":"delivered_at"}}],"unit":"hours"}'::jsonb where indicator_key in ('transport_average_delivery_time','transport_avg_delivery_time');
update public.native_indicator_definitions set calculation_config='{"date_pairs":[{"start":{"table":"operation_records","field":"expected_date"},"end":{"table":"operation_records","field":"completed_at"}},{"start":{"table":"operation_records","field":"expected_date"},"end":{"table":"transport_records","field":"delivered_at"}}],"unit":"hours"}'::jsonb where indicator_key in ('transport_average_delay','transport_avg_delay');
update public.native_indicator_definitions set calculation_config='{"denominator":{"filter":[{"table":"transport_records","field":"sla_status","operator":"not_null"}]},"numerator":{"filter":[{"table":"transport_records","field":"sla_status","operator":"in","value":["met","on_time","cumprido","cumprida","ok"]}]}}'::jsonb where indicator_key='transport_sla_compliance';
