create table if not exists public.data_sources (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null, description text, source_type text not null, module_key text not null, status text not null default 'draft',
  owner_user_id uuid references public.users_profile(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  constraint data_sources_source_type_check check (source_type in ('manual_file','spreadsheet','api','database','email','other')),
  constraint data_sources_status_check check (status in ('draft','active','inactive','deprecated'))
);
create table if not exists public.data_contracts (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  data_source_id uuid not null references public.data_sources(id) on delete cascade, name text not null, description text, module_key text not null, entity_key text not null,
  contract_version integer not null default 1, format text not null, direction text not null default 'inbound', status text not null default 'draft', periodicity text, effective_from date, effective_until date,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique(tenant_id, data_source_id, entity_key, contract_version),
  constraint data_contracts_format_check check (format in ('csv','xlsx','json','api_json','fixed_width','other')),
  constraint data_contracts_direction_check check (direction in ('inbound','outbound')),
  constraint data_contracts_status_check check (status in ('draft','active','inactive','deprecated','rejected'))
);
create table if not exists public.data_contract_fields (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  data_contract_id uuid not null references public.data_contracts(id) on delete cascade, field_key text not null, source_field_name text not null, description text, data_type text not null,
  is_required boolean not null default false, is_unique boolean not null default false, allow_null boolean not null default true, min_length integer, max_length integer, min_value numeric, max_value numeric, regex_pattern text, date_format text, sort_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(data_contract_id, field_key),
  constraint data_contract_fields_data_type_check check (data_type in ('text','integer','decimal','boolean','date','datetime','enum','json'))
);
create table if not exists public.data_contract_allowed_values (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  data_contract_id uuid not null references public.data_contracts(id) on delete cascade, data_contract_field_id uuid not null references public.data_contract_fields(id) on delete cascade,
  value text not null, label text, normalized_value text, is_active boolean not null default true, sort_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(data_contract_field_id, value)
);
create index if not exists idx_data_sources_tenant_id on public.data_sources(tenant_id); create index if not exists idx_data_sources_status on public.data_sources(status); create index if not exists idx_data_sources_source_type on public.data_sources(source_type);
create index if not exists idx_data_contracts_tenant_id on public.data_contracts(tenant_id); create index if not exists idx_data_contracts_data_source_id on public.data_contracts(data_source_id); create index if not exists idx_data_contracts_status on public.data_contracts(status); create index if not exists idx_data_contracts_entity_key on public.data_contracts(entity_key);
create index if not exists idx_data_contract_fields_tenant_id on public.data_contract_fields(tenant_id); create index if not exists idx_data_contract_fields_data_contract_id on public.data_contract_fields(data_contract_id); create index if not exists idx_data_contract_fields_data_type on public.data_contract_fields(data_type);
create index if not exists idx_data_contract_allowed_values_tenant_id on public.data_contract_allowed_values(tenant_id); create index if not exists idx_data_contract_allowed_values_data_contract_id on public.data_contract_allowed_values(data_contract_id); create index if not exists idx_data_contract_allowed_values_data_contract_field_id on public.data_contract_allowed_values(data_contract_field_id);
create trigger set_data_sources_updated_at before update on public.data_sources for each row execute function public.set_updated_at();
create trigger set_data_contracts_updated_at before update on public.data_contracts for each row execute function public.set_updated_at();
create trigger set_data_contract_fields_updated_at before update on public.data_contract_fields for each row execute function public.set_updated_at();
create trigger set_data_contract_allowed_values_updated_at before update on public.data_contract_allowed_values for each row execute function public.set_updated_at();
alter table public.data_sources enable row level security; alter table public.data_contracts enable row level security; alter table public.data_contract_fields enable row level security; alter table public.data_contract_allowed_values enable row level security;
drop policy if exists "members can read own tenant data sources" on public.data_sources; create policy "members can read own tenant data sources" on public.data_sources for select to authenticated using (public.is_member_of_tenant(tenant_id));
drop policy if exists "members can create data sources with permission" on public.data_sources; create policy "members can create data sources with permission" on public.data_sources for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_sources.create'));
drop policy if exists "members can update data sources with permission" on public.data_sources; create policy "members can update data sources with permission" on public.data_sources for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_sources.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_sources.update'));
drop policy if exists "members can read own tenant data contracts" on public.data_contracts; create policy "members can read own tenant data contracts" on public.data_contracts for select to authenticated using (public.is_member_of_tenant(tenant_id));
drop policy if exists "members can create data contracts with permission" on public.data_contracts; create policy "members can create data contracts with permission" on public.data_contracts for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contracts.create'));
drop policy if exists "members can update data contracts with permission" on public.data_contracts; create policy "members can update data contracts with permission" on public.data_contracts for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contracts.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contracts.update'));
drop policy if exists "members can read own tenant data contract fields" on public.data_contract_fields; create policy "members can read own tenant data contract fields" on public.data_contract_fields for select to authenticated using (public.is_member_of_tenant(tenant_id));
drop policy if exists "members can create data contract fields with permission" on public.data_contract_fields; create policy "members can create data contract fields with permission" on public.data_contract_fields for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update'));
drop policy if exists "members can update data contract fields with permission" on public.data_contract_fields; create policy "members can update data contract fields with permission" on public.data_contract_fields for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update'));
drop policy if exists "members can read own tenant data contract allowed values" on public.data_contract_allowed_values; create policy "members can read own tenant data contract allowed values" on public.data_contract_allowed_values for select to authenticated using (public.is_member_of_tenant(tenant_id));
drop policy if exists "members can create data contract allowed values with permission" on public.data_contract_allowed_values; create policy "members can create data contract allowed values with permission" on public.data_contract_allowed_values for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update'));
drop policy if exists "members can update data contract allowed values with permission" on public.data_contract_allowed_values; create policy "members can update data contract allowed values with permission" on public.data_contract_allowed_values for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id, 'core.data_contract_fields.update'));
with permission_seed(key,name,module_key,resource,action,description) as (values
('core.data_sources.view','Visualizar fontes de dados','core','data_sources','view','Permite visualizar fontes de dados declarativas.'),('core.data_sources.create','Criar fontes de dados','core','data_sources','create','Permite criar fontes de dados declarativas.'),('core.data_sources.update','Atualizar fontes de dados','core','data_sources','update','Permite atualizar fontes de dados declarativas.'),('core.data_contracts.view','Visualizar contratos de dados','core','data_contracts','view','Permite visualizar contratos de dados.'),('core.data_contracts.create','Criar contratos de dados','core','data_contracts','create','Permite criar contratos de dados.'),('core.data_contracts.update','Atualizar contratos de dados','core','data_contracts','update','Permite atualizar contratos de dados.'),('core.data_contracts.activate','Ativar contratos de dados','core','data_contracts','activate','Permite ativar contratos de dados.'),('core.data_contract_fields.view','Visualizar campos de contratos','core','data_contract_fields','view','Permite visualizar campos e valores aceitos.'),('core.data_contract_fields.update','Atualizar campos de contratos','core','data_contract_fields','update','Permite atualizar campos e valores aceitos.'))
insert into public.permissions (key,name,module_key,resource,action,description) select * from permission_seed on conflict (key) do update set name=excluded.name,module_key=excluded.module_key,resource=excluded.resource,action=excluded.action,description=excluded.description,updated_at=now();
insert into public.role_permissions (tenant_id, role_id, permission_id) select r.tenant_id,r.id,p.id from public.roles r cross join public.permissions p where r.key='owner' and p.key in ('core.data_sources.view','core.data_sources.create','core.data_sources.update','core.data_contracts.view','core.data_contracts.create','core.data_contracts.update','core.data_contracts.activate','core.data_contract_fields.view','core.data_contract_fields.update') on conflict (tenant_id, role_id, permission_id) do nothing;
with t as (select id from public.tenants where slug='agentlog'), ds as (insert into public.data_sources (tenant_id,name,description,source_type,module_key,status) select id,'Planilha modelo de entregas','Fonte declarativa inicial para contrato de entregas.','spreadsheet','transporte','active' from t where not exists (select 1 from public.data_sources d join t on t.id=d.tenant_id where d.name='Planilha modelo de entregas') returning id,tenant_id), src as (select * from ds union all select d.id,d.tenant_id from public.data_sources d join t on t.id=d.tenant_id where d.name='Planilha modelo de entregas' limit 1), dc as (insert into public.data_contracts (tenant_id,data_source_id,name,description,module_key,entity_key,contract_version,format,direction,status,periodicity) select tenant_id,id,'Contrato inicial de entregas','Contrato declarativo inicial para entregas. Não realiza importação nesta sprint.','transporte','deliveries',1,'xlsx','inbound','draft','on_demand' from src on conflict (tenant_id,data_source_id,entity_key,contract_version) do nothing returning id,tenant_id), contract as (select * from dc union all select c.id,c.tenant_id from public.data_contracts c join src s on s.id=c.data_source_id where c.entity_key='deliveries' and c.contract_version=1 limit 1), field_seed(field_key,source_field_name,data_type,is_required,date_format,sort_order) as (values ('delivery_number','Numero Entrega','text',true,null,10),('customer_document','Documento Cliente','text',true,null,20),('customer_name','Nome Cliente','text',true,null,30),('delivery_status','Status Entrega','enum',true,null,40),('expected_delivery_date','Data Prevista','date',false,'YYYY-MM-DD',50),('delivered_at','Data Entrega','datetime',false,null,60),('total_value','Valor Total','decimal',false,null,70))
insert into public.data_contract_fields (tenant_id,data_contract_id,field_key,source_field_name,data_type,is_required,date_format,sort_order) select c.tenant_id,c.id,f.field_key,f.source_field_name,f.data_type,f.is_required,f.date_format,f.sort_order from contract c cross join field_seed f on conflict (data_contract_id,field_key) do nothing;
with status_field as (select f.id field_id,f.tenant_id,f.data_contract_id from public.data_contract_fields f join public.data_contracts c on c.id=f.data_contract_id join public.tenants t on t.id=f.tenant_id where t.slug='agentlog' and c.entity_key='deliveries' and f.field_key='delivery_status'), value_seed(value,sort_order) as (values ('pending',10),('in_transit',20),('delivered',30),('failed',40),('cancelled',50))
insert into public.data_contract_allowed_values (tenant_id,data_contract_id,data_contract_field_id,value,label,normalized_value,sort_order) select sf.tenant_id,sf.data_contract_id,sf.field_id,v.value,v.value,v.value,v.sort_order from status_field sf cross join value_seed v on conflict (data_contract_field_id,value) do nothing;
