-- Sprint 10R-B: tenant-aware native reason catalog and configurable validation.
create table public.occurrence_reason_requirements (
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), reason_id uuid not null references public.occurrence_reasons(id) on delete cascade,
 stage text not null check(stage in ('opening','update','resolution','closing')), field_key text not null, is_required boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(tenant_id,reason_id,stage,field_key)
);
create index occurrence_reason_requirements_tenant_idx on public.occurrence_reason_requirements(tenant_id,reason_id,stage);
alter table public.occurrence_reason_requirements enable row level security;
create policy "tenant members read occurrence requirements" on public.occurrence_reason_requirements for select to authenticated using(public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'occurrence_reasons.view'));
create policy "tenant members create occurrence requirements" on public.occurrence_reason_requirements for insert to authenticated with check(public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'occurrence_reasons.create'));
create policy "tenant members update occurrence requirements" on public.occurrence_reason_requirements for update to authenticated using(public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'occurrence_reasons.update')) with check(public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'occurrence_reasons.update'));

alter table public.occurrence_reasons add column if not exists sla_minutes integer check(sla_minutes is null or sla_minutes >= 0), add column if not exists responsible_team text, add column if not exists external_code text, add column if not exists proceda_code text, add column if not exists tms_code text, add column if not exists erp_code text;

create or replace function public.seed_native_occurrence_reasons(target_tenant uuid) returns void language plpgsql security definer set search_path=public as $$
begin
 with native(category_name,code,reason_name) as (values
  ('Entrega realizada','entrega_realizada_normalmente','Entrega realizada normalmente'),
  ('Entrega realizada','entrega_realizada_antecipadamente','Entrega realizada antecipadamente'),
  ('Entrega realizada','entrega_realizada_com_atraso','Entrega realizada com atraso'),
  ('Entrega realizada','entrega_parcial','Entrega parcial'),
  ('Entrega realizada','entrega_com_ressalva','Entrega com ressalva'),
  ('Entrega realizada','comprovante_de_entrega_recebido','Comprovante de entrega recebido'),
  ('Entrega realizada','comprovante_de_entrega_pendente','Comprovante de entrega pendente'),
  ('Destinatário e endereço','destinatario_ausente','Destinatário ausente'),
  ('Destinatário e endereço','destinatario_desconhecido_no_endereco','Destinatário desconhecido no endereço'),
  ('Destinatário e endereço','destinatario_mudou_se','Destinatário mudou-se'),
  ('Destinatário e endereço','destinatario_recusou_o_recebimento','Destinatário recusou o recebimento'),
  ('Destinatário e endereço','endereco_incorreto','Endereço incorreto'),
  ('Destinatário e endereço','endereco_incompleto','Endereço incompleto'),
  ('Destinatário e endereço','endereco_nao_localizado','Endereço não localizado'),
  ('Destinatário e endereço','area_de_dificil_acesso','Área de difícil acesso'),
  ('Destinatário e endereço','area_de_risco','Área de risco'),
  ('Destinatário e endereço','local_fechado','Local fechado'),
  ('Destinatário e endereço','entrega_fora_do_horario_de_recebimento','Entrega fora do horário de recebimento'),
  ('Agendamento e restrições do cliente','entrega_aguardando_agendamento','Entrega aguardando agendamento'),
  ('Agendamento e restrições do cliente','entrega_agendada','Entrega agendada'),
  ('Agendamento e restrições do cliente','agendamento_nao_confirmado','Agendamento não confirmado'),
  ('Agendamento e restrições do cliente','agendamento_cancelado_pelo_cliente','Agendamento cancelado pelo cliente'),
  ('Agendamento e restrições do cliente','agendamento_reagendado','Agendamento reagendado'),
  ('Agendamento e restrições do cliente','cliente_solicitou_alteracao_da_data','Cliente solicitou alteração da data'),
  ('Agendamento e restrições do cliente','veiculo_chegou_fora_da_janela_de_entrega','Veículo chegou fora da janela de entrega'),
  ('Agendamento e restrições do cliente','restricao_de_veiculo_no_local','Restrição de veículo no local'),
  ('Agendamento e restrições do cliente','necessidade_de_autorizacao_previa','Necessidade de autorização prévia'),
  ('Documentação e divergência cadastral','nota_fiscal_nao_localizada','Nota fiscal não localizada'),
  ('Documentação e divergência cadastral','nota_fiscal_incorreta','Nota fiscal incorreta'),
  ('Documentação e divergência cadastral','nota_fiscal_cancelada','Nota fiscal cancelada'),
  ('Documentação e divergência cadastral','nota_fiscal_divergente_do_pedido','Nota fiscal divergente do pedido'),
  ('Documentação e divergência cadastral','falta_de_documento_fiscal','Falta de documento fiscal'),
  ('Documentação e divergência cadastral','divergencia_de_peso','Divergência de peso'),
  ('Documentação e divergência cadastral','divergencia_de_valor','Divergência de valor'),
  ('Documentação e divergência cadastral','divergencia_de_sku_produto','Divergência de SKU/produto'),
  ('Documentação e divergência cadastral','pedido_nao_localizado_pelo_cliente','Pedido não localizado pelo cliente'),
  ('Documentação e divergência cadastral','cnpj_divergente','CNPJ divergente'),
  ('Documentação e divergência cadastral','ct_e_ou_mdf_e_com_pendencia','CT-e ou MDF-e com pendência'),
  ('Falta, sobra e inversão','falta_total_de_mercadoria','Falta total de mercadoria'),
  ('Falta, sobra e inversão','falta_parcial_de_mercadoria','Falta parcial de mercadoria'),
  ('Falta, sobra e inversão','falta_de_volume','Falta de volume'),
  ('Falta, sobra e inversão','falta_de_item_sku','Falta de item/SKU'),
  ('Falta, sobra e inversão','sobra_de_mercadoria','Sobra de mercadoria'),
  ('Falta, sobra e inversão','sobra_de_volume','Sobra de volume'),
  ('Falta, sobra e inversão','sobra_de_item_sku','Sobra de item/SKU'),
  ('Falta, sobra e inversão','mercadoria_invertida','Mercadoria invertida'),
  ('Falta, sobra e inversão','volume_invertido','Volume invertido'),
  ('Falta, sobra e inversão','produto_trocado','Produto trocado'),
  ('Falta, sobra e inversão','divergencia_entre_volume_fisico_e_documento','Divergência entre volume físico e documento'),
  ('Avaria e condição da mercadoria','mercadoria_avariada','Mercadoria avariada'),
  ('Avaria e condição da mercadoria','embalagem_avariada','Embalagem avariada'),
  ('Avaria e condição da mercadoria','produto_quebrado','Produto quebrado'),
  ('Avaria e condição da mercadoria','produto_amassado','Produto amassado'),
  ('Avaria e condição da mercadoria','produto_molhado','Produto molhado'),
  ('Avaria e condição da mercadoria','lacre_violado','Lacre violado'),
  ('Avaria e condição da mercadoria','embalagem_aberta','Embalagem aberta'),
  ('Avaria e condição da mercadoria','produto_vencido','Produto vencido'),
  ('Avaria e condição da mercadoria','temperatura_fora_do_padrao','Temperatura fora do padrão'),
  ('Avaria e condição da mercadoria','mercadoria_sem_condicoes_de_entrega','Mercadoria sem condições de entrega'),
  ('Recusa e devolução','recusa_total','Recusa total'),
  ('Recusa e devolução','recusa_parcial','Recusa parcial'),
  ('Recusa e devolução','devolucao_total','Devolução total'),
  ('Recusa e devolução','devolucao_parcial','Devolução parcial'),
  ('Recusa e devolução','devolucao_solicitada_pelo_cliente','Devolução solicitada pelo cliente'),
  ('Recusa e devolução','devolucao_solicitada_pelo_embarcador','Devolução solicitada pelo embarcador'),
  ('Recusa e devolução','devolucao_por_avaria','Devolução por avaria'),
  ('Recusa e devolução','devolucao_por_falta_ou_divergencia','Devolução por falta ou divergência'),
  ('Recusa e devolução','devolucao_por_produto_incorreto','Devolução por produto incorreto'),
  ('Recusa e devolução','devolucao_por_pedido_cancelado','Devolução por pedido cancelado'),
  ('Recusa e devolução','nota_fiscal_de_devolucao_pendente','Nota fiscal de devolução pendente'),
  ('Recusa e devolução','nota_fiscal_de_devolucao_emitida','Nota fiscal de devolução emitida'),
  ('Descarga e despesas operacionais','cobranca_de_descarga','Cobrança de descarga'),
  ('Descarga e despesas operacionais','pagamento_de_descarga_solicitado','Pagamento de descarga solicitado'),
  ('Descarga e despesas operacionais','pagamento_de_descarga_autorizado','Pagamento de descarga autorizado'),
  ('Descarga e despesas operacionais','pagamento_de_descarga_recusado','Pagamento de descarga recusado'),
  ('Descarga e despesas operacionais','pagamento_de_descarga_realizado','Pagamento de descarga realizado'),
  ('Descarga e despesas operacionais','comprovante_de_descarga_pendente','Comprovante de descarga pendente'),
  ('Descarga e despesas operacionais','valor_de_descarga_divergente','Valor de descarga divergente'),
  ('Descarga e despesas operacionais','cobranca_de_diaria','Cobrança de diária'),
  ('Descarga e despesas operacionais','cobranca_de_estadia','Cobrança de estadia'),
  ('Descarga e despesas operacionais','cobranca_de_ajudante','Cobrança de ajudante'),
  ('Descarga e despesas operacionais','cobranca_de_taxa_adicional_nao_prevista','Cobrança de taxa adicional não prevista'),
  ('Descarga e despesas operacionais','motorista_aguardando_liberacao_para_descarga','Motorista aguardando liberação para descarga'),
  ('Descarga e despesas operacionais','descarga_iniciada','Descarga iniciada'),
  ('Descarga e despesas operacionais','descarga_concluida','Descarga concluída'),
  ('Veículo e motorista','veiculo_avariado','Veículo avariado'),
  ('Veículo e motorista','pane_mecanica','Pane mecânica'),
  ('Veículo e motorista','pneu_danificado','Pneu danificado'),
  ('Veículo e motorista','acidente_de_transito','Acidente de trânsito'),
  ('Veículo e motorista','veiculo_retido','Veículo retido'),
  ('Veículo e motorista','veiculo_incompativel_com_o_local','Veículo incompatível com o local'),
  ('Veículo e motorista','motorista_impossibilitado_de_prosseguir','Motorista impossibilitado de prosseguir'),
  ('Veículo e motorista','troca_de_motorista','Troca de motorista'),
  ('Veículo e motorista','troca_de_veiculo','Troca de veículo'),
  ('Veículo e motorista','aguardando_veiculo_substituto','Aguardando veículo substituto'),
  ('Veículo e motorista','problema_com_documentacao_do_veiculo','Problema com documentação do veículo'),
  ('Veículo e motorista','problema_com_documentacao_do_motorista','Problema com documentação do motorista'),
  ('Veículo e motorista','jornada_do_motorista_encerrada','Jornada do motorista encerrada'),
  ('Veículo e motorista','atraso_na_saida_do_veiculo','Atraso na saída do veículo'),
  ('Segurança e perda da carga','roubo_de_carga','Roubo de carga'),
  ('Segurança e perda da carga','furto_de_carga','Furto de carga'),
  ('Segurança e perda da carga','tentativa_de_roubo','Tentativa de roubo'),
  ('Segurança e perda da carga','extravio_total','Extravio total'),
  ('Segurança e perda da carga','extravio_parcial','Extravio parcial'),
  ('Segurança e perda da carga','volume_nao_localizado','Volume não localizado'),
  ('Segurança e perda da carga','carga_violada','Carga violada'),
  ('Segurança e perda da carga','sinistro_com_a_carga','Sinistro com a carga'),
  ('Segurança e perda da carga','mercadoria_apreendida','Mercadoria apreendida'),
  ('Segurança e perda da carga','ocorrencia_de_seguranca_em_apuracao','Ocorrência de segurança em apuração'),
  ('Fiscal e órgãos de controle','retencao_em_posto_fiscal','Retenção em posto fiscal'),
  ('Fiscal e órgãos de controle','fiscalizacao_em_andamento','Fiscalização em andamento'),
  ('Fiscal e órgãos de controle','mercadoria_apreendida_pela_fiscalizacao','Mercadoria apreendida pela fiscalização'),
  ('Fiscal e órgãos de controle','documento_fiscal_rejeitado','Documento fiscal rejeitado'),
  ('Fiscal e órgãos de controle','pendencia_tributaria','Pendência tributária'),
  ('Fiscal e órgãos de controle','pendencia_sanitaria','Pendência sanitária'),
  ('Fiscal e órgãos de controle','pendencia_aduaneira','Pendência aduaneira'),
  ('Fiscal e órgãos de controle','aguardando_liberacao_fiscal','Aguardando liberação fiscal'),
  ('Fiscal e órgãos de controle','carga_liberada_pela_fiscalizacao','Carga liberada pela fiscalização'),
  ('Trânsito, rota e condições externas','transito_intenso','Trânsito intenso'),
  ('Trânsito, rota e condições externas','via_interditada','Via interditada'),
  ('Trânsito, rota e condições externas','bloqueio_de_estrada','Bloqueio de estrada'),
  ('Trânsito, rota e condições externas','desvio_de_rota','Desvio de rota'),
  ('Trânsito, rota e condições externas','restricao_de_circulacao','Restrição de circulação'),
  ('Trânsito, rota e condições externas','condicao_climatica_adversa','Condição climática adversa'),
  ('Trânsito, rota e condições externas','alagamento','Alagamento'),
  ('Trânsito, rota e condições externas','queda_de_barreira','Queda de barreira'),
  ('Trânsito, rota e condições externas','manifestacao_ou_paralisacao','Manifestação ou paralisação'),
  ('Trânsito, rota e condições externas','greve','Greve'),
  ('Trânsito, rota e condições externas','atraso_em_balsa_ou_travessia','Atraso em balsa ou travessia'),
  ('Trânsito, rota e condições externas','acesso_impossibilitado','Acesso impossibilitado'),
  ('Trânsito, rota e condições externas','caso_fortuito_ou_forca_maior','Caso fortuito ou força maior'),
  ('Movimentação e rastreamento','coleta_solicitada','Coleta solicitada'),
  ('Movimentação e rastreamento','coleta_agendada','Coleta agendada'),
  ('Movimentação e rastreamento','coleta_realizada','Coleta realizada'),
  ('Movimentação e rastreamento','coleta_nao_realizada','Coleta não realizada'),
  ('Movimentação e rastreamento','carga_recebida_pela_transportadora','Carga recebida pela transportadora'),
  ('Movimentação e rastreamento','transporte_iniciado','Transporte iniciado'),
  ('Movimentação e rastreamento','em_transito','Em trânsito'),
  ('Movimentação e rastreamento','em_transferencia_entre_unidades','Em transferência entre unidades'),
  ('Movimentação e rastreamento','chegada_a_unidade_de_destino','Chegada à unidade de destino'),
  ('Movimentação e rastreamento','carga_em_tratamento_na_unidade','Carga em tratamento na unidade'),
  ('Movimentação e rastreamento','carga_redespachada','Carga redespachada'),
  ('Movimentação e rastreamento','saiu_para_entrega','Saiu para entrega'),
  ('Movimentação e rastreamento','entrega_em_andamento','Entrega em andamento'),
  ('Movimentação e rastreamento','retorno_a_unidade','Retorno à unidade'),
  ('Movimentação e rastreamento','em_processo_de_reentrega','Em processo de reentrega'),
  ('Movimentação e rastreamento','reentrega_solicitada','Reentrega solicitada'),
  ('Movimentação e rastreamento','reentrega_realizada','Reentrega realizada'),
  ('Movimentação e rastreamento','ocorrencia_em_analise','Ocorrência em análise'),
  ('Movimentação e rastreamento','ocorrencia_solucionada','Ocorrência solucionada')
 ), categories as (
  insert into public.occurrence_reason_categories(tenant_id,name,is_system) select target_tenant,category_name,true from native group by category_name on conflict(tenant_id,name) do update set is_system=true returning id,name
 ), templates as (
  insert into public.occurrence_reason_templates(tenant_id,category_id,code,name,is_system) select target_tenant,c.id,n.code,n.reason_name,true from native n join categories c on c.name=n.category_name on conflict(tenant_id,code) do update set name=excluded.name,is_system=true returning id,category_id,code,name
 )
 insert into public.occurrence_reasons(tenant_id,template_id,category_id,code,name,is_custom) select target_tenant,t.id,t.category_id,t.code,t.name,false from templates t on conflict(tenant_id,code) do nothing;

 insert into public.occurrence_reason_requirements(tenant_id,reason_id,stage,field_key)
 select target_tenant,r.id,x.stage,x.field_key from public.occurrence_reasons r join (values
 ('falta_parcial_de_mercadoria','opening','quantity'),('falta_parcial_de_mercadoria','opening','sku'),('falta_de_item_sku','opening','quantity'),('falta_de_item_sku','opening','sku'),('sobra_de_item_sku','opening','quantity'),('sobra_de_item_sku','opening','sku'),('divergencia_de_valor','opening','amount'),
 ('pagamento_de_descarga_realizado','update','payment_amount'),('pagamento_de_descarga_realizado','update','attachment_required'),('comprovante_de_entrega_pendente','opening','document_number'),('agendamento_reagendado','update','redelivery_date'),('entrega_realizada_normalmente','opening','occurred_at')
 ) x(code,stage,field_key) on x.code=r.code where r.tenant_id=target_tenant on conflict do nothing;
 insert into public.occurrence_reason_requirements(tenant_id,reason_id,stage,field_key) select target_tenant,r.id,'opening',f.field_key from public.occurrence_reasons r cross join(values('event_description'),('evidence_required'))f(field_key) where r.tenant_id=target_tenant and (r.name ilike '%avariad%' or r.name in ('Roubo de carga','Furto de carga','Sinistro com a carga')) on conflict do nothing;
 insert into public.occurrence_reason_requirements(tenant_id,reason_id,stage,field_key) select target_tenant,r.id,s.stage,'return_invoice_number' from public.occurrence_reasons r cross join(values('resolution'),('closing'))s(stage) where r.tenant_id=target_tenant and r.name ilike 'Devolução%' on conflict do nothing;
end $$;

do $$ declare t record; begin for t in select id from public.tenants loop perform public.seed_native_occurrence_reasons(t.id); end loop; end $$;
create or replace function public.seed_occurrence_catalog_for_tenant() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.seed_native_occurrence_reasons(new.id); return new; end $$;
create trigger tenants_seed_occurrence_catalog after insert on public.tenants for each row execute function public.seed_occurrence_catalog_for_tenant();
