-- Sprint 9 — Normalização determinística: staging validado + field_mappings -> base operacional nativa
create table if not exists public.normalization_runs (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  staging_batch_id uuid not null references public.staging_batches(id) on delete cascade, data_source_id uuid references public.data_sources(id) on delete set null, data_contract_id uuid references public.data_contracts(id) on delete set null,
  status text not null default 'pending', total_records integer not null default 0, processed_records integer not null default 0,
  created_operation_records integer not null default 0, updated_operation_records integer not null default 0, created_extension_records integer not null default 0, updated_extension_records integer not null default 0, error_records integer not null default 0,
  started_at timestamptz, finished_at timestamptz, error_summary jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint normalization_runs_status_check check (status in ('pending','running','completed','completed_with_errors','failed'))
);
create table if not exists public.normalization_errors (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  normalization_run_id uuid not null references public.normalization_runs(id) on delete cascade, staging_batch_id uuid not null references public.staging_batches(id) on delete cascade, staging_record_id uuid references public.staging_records(id) on delete set null, field_mapping_id uuid references public.field_mappings(id) on delete set null,
  canonical_entity_key text, canonical_field_key text, error_code text not null, error_message text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(),
  constraint normalization_errors_code_check check (error_code in ('NO_VALID_RECORDS','NO_FIELD_MAPPINGS','INVALID_STAGING_BATCH','INVALID_STAGING_RECORD','MISSING_OPERATION_RECORD','INVALID_CANONICAL_ENTITY','INVALID_CANONICAL_FIELD','INVALID_VALUE_TYPE','REQUIRED_VALUE_MISSING','MODULE_NOT_ENABLED','UPSERT_FAILED','UNKNOWN_ERROR'))
);
drop trigger if exists set_normalization_runs_updated_at on public.normalization_runs; create trigger set_normalization_runs_updated_at before update on public.normalization_runs for each row execute function public.set_updated_at();
alter table public.normalization_runs enable row level security; alter table public.normalization_errors enable row level security;
create index if not exists idx_normalization_runs_tenant_id on public.normalization_runs(tenant_id); create index if not exists idx_normalization_runs_tenant_batch on public.normalization_runs(tenant_id,staging_batch_id); create index if not exists idx_normalization_runs_tenant_status on public.normalization_runs(tenant_id,status); create index if not exists idx_normalization_runs_tenant_created_at on public.normalization_runs(tenant_id,created_at);
create index if not exists idx_normalization_errors_tenant_id on public.normalization_errors(tenant_id); create index if not exists idx_normalization_errors_tenant_run on public.normalization_errors(tenant_id,normalization_run_id); create index if not exists idx_normalization_errors_tenant_batch on public.normalization_errors(tenant_id,staging_batch_id); create index if not exists idx_normalization_errors_tenant_record on public.normalization_errors(tenant_id,staging_record_id); create index if not exists idx_normalization_errors_tenant_code on public.normalization_errors(tenant_id,error_code);
drop policy if exists "members can read normalization_runs" on public.normalization_runs; create policy "members can read normalization_runs" on public.normalization_runs for select to authenticated using (public.is_member_of_tenant(tenant_id) and (public.user_has_permission(tenant_id,'normalization.view') or public.user_has_permission(tenant_id,'normalization.run')));
drop policy if exists "members can run normalization_runs" on public.normalization_runs; create policy "members can run normalization_runs" on public.normalization_runs for all to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'normalization.run')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'normalization.run'));
drop policy if exists "members can read normalization_errors" on public.normalization_errors; create policy "members can read normalization_errors" on public.normalization_errors for select to authenticated using (public.is_member_of_tenant(tenant_id) and (public.user_has_permission(tenant_id,'normalization.view') or public.user_has_permission(tenant_id,'normalization.run')));
drop policy if exists "members can run normalization_errors" on public.normalization_errors; create policy "members can run normalization_errors" on public.normalization_errors for all to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'normalization.run')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'normalization.run'));
with permission_seed(key,name,module_key,resource,action,description) as (values ('normalization.view','Visualizar normalização','core','normalization','view','Permite consultar execuções e erros de normalização.'),('normalization.run','Executar normalização','core','normalization','run','Permite processar staging validado para a base nativa.')) insert into public.permissions (key,name,module_key,resource,action,description) select * from permission_seed on conflict (key) do update set name=excluded.name,module_key=excluded.module_key,resource=excluded.resource,action=excluded.action,description=excluded.description,updated_at=now();
insert into public.role_permissions (tenant_id,role_id,permission_id) select r.tenant_id,r.id,p.id from public.roles r cross join public.permissions p where r.key='owner' and p.key in ('normalization.view','normalization.run') on conflict (tenant_id,role_id,permission_id) do nothing;
