-- Sprint 16A: relatórios configuráveis, sem entrega/agendamento automático.
create table public.report_definitions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, name text not null, description text, module_key text not null, layout_key text not null default 'standard_report', status text not null default 'draft' check(status in ('draft','active','archived')), ai_enabled boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.report_blocks (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, block_key text not null, block_type text not null check(block_type in ('kpi','table','matrix','bar','pie','line','ai_summary','ai_section_note')), title text not null, source_type text not null check(source_type in ('native_indicator','custom_indicator')), source_id text not null, visual_type text not null check(visual_type in ('kpi','table','matrix','bar','pie','line')), position jsonb not null default '{}'::jsonb, config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.report_filters (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, filter_key text not null, label text not null, filter_type text not null check(filter_type in ('date_range','multi_select')), default_value jsonb not null default '{}'::jsonb, locked boolean not null default false, user_can_override boolean not null default true, required boolean not null default false, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.report_user_settings (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, user_id uuid not null references auth.users(id), filters_override jsonb not null default '{}'::jsonb, preferred_format text not null default 'preview', send_enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id,report_definition_id,user_id));
create table public.report_schedules (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, user_id uuid not null references auth.users(id), enabled boolean not null default false, frequency text not null default 'daily' check(frequency in ('daily','weekly','monthly')), day_of_week integer, day_of_month integer, time_of_day text, timezone text not null default 'America/Sao_Paulo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id,report_definition_id,user_id));
create table public.report_recipients (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, user_id uuid not null references auth.users(id), recipient_name text, recipient_email text not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.report_jobs (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, report_definition_id uuid not null references public.report_definitions(id) on delete cascade, requested_by uuid references auth.users(id), trigger_type text not null default 'manual' check(trigger_type in ('manual','scheduled')), status text not null default 'pending' check(status in ('pending','processing','completed','failed')), filters_snapshot jsonb not null default '{}'::jsonb, data_snapshot jsonb not null default '{}'::jsonb, ai_snapshot jsonb, render_snapshot jsonb not null default '{}'::jsonb, error_message text, started_at timestamptz, finished_at timestamptz, created_at timestamptz not null default now());
create index on public.report_definitions(tenant_id,status,updated_at desc); create index on public.report_blocks(tenant_id,report_definition_id); create index on public.report_filters(tenant_id,report_definition_id); create index on public.report_jobs(tenant_id,report_definition_id,created_at desc);
do $$ declare t text; begin foreach t in array array['report_definitions','report_blocks','report_filters','report_user_settings','report_schedules','report_recipients','report_jobs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "tenant members %s" on public.%I for all to authenticated using (public.is_member_of_tenant(tenant_id)) with check (public.is_member_of_tenant(tenant_id))',t,t); end loop; end $$;
insert into public.permissions(key,name,module_key,resource,action,description) values
('reports.view','Visualizar relatórios','reports','reports','view','Permite visualizar relatórios.'),('reports.configure','Configurar relatórios','reports','reports','configure','Permite criar e editar relatórios.'),('reports.manage_structure','Gerenciar estrutura de relatórios','reports','reports','manage_structure','Permite configurar blocos e filtros.'),('reports.generate','Gerar relatórios','reports','reports','generate','Permite gerar prévias manuais.'),('reports.manage_recipients','Gerenciar destinatários','reports','reports','manage_recipients','Permite gerenciar destinatários próprios.'),('reports.manage_schedule','Gerenciar periodicidade','reports','reports','manage_schedule','Permite salvar periodicidade própria.'),('reports.view_jobs','Visualizar execuções de relatórios','reports','reports','view_jobs','Permite visualizar execuções.') on conflict(key) do update set name=excluded.name,description=excluded.description,updated_at=now();
insert into public.role_permissions(tenant_id,role_id,permission_id) select r.tenant_id,r.id,p.id from public.roles r cross join public.permissions p where r.key in ('owner','admin','super_admin','administrador') and p.key like 'reports.%' on conflict do nothing;
