-- Sprint 8: labels em português para campos canônicos exibidos na UI de mapeamento.
-- Mantém field_key e colunas físicas em inglês; altera apenas o nome visual gravado em canonical_fields.name.
with label_seed(field_key, name) as (values
  ('operation_record_id','Registro operacional'),('external_id','ID externo'),('external_code','Código externo'),('source_system','Sistema de origem'),('source_data_source_id','Fonte de dados de origem'),('source_data_contract_id','Contrato de dados de origem'),('source_staging_batch_id','Lote de preparação de origem'),('source_staging_record_id','Registro de preparação de origem'),('source_payload_hash','Hash do payload de origem'),('module_origin','Módulo de origem'),('record_type','Tipo de registro'),('document_number','Número do documento'),('document_type','Tipo do documento'),('cte_number','Número do CT-e'),('cte_key','Chave do CT-e'),('invoice_number','Número da NF'),('invoice_key','Chave da NF'),('manifest_number','Número do manifesto'),('order_number','Número do pedido'),('delivery_number','Número da entrega'),('customer_name','Nome do cliente'),('customer_document','Documento do cliente'),('shipper_name','Nome do embarcador'),('shipper_document','Documento do embarcador'),('recipient_name','Nome do destinatário'),('recipient_document','Documento do destinatário'),('payer_name','Nome do pagador'),('payer_document','Documento do pagador'),('origin_city','Cidade de origem'),('origin_state','UF de origem'),('destination_city','Cidade de destino'),('destination_state','UF de destino'),('vehicle_plate','Placa do veículo'),('driver_name','Nome do motorista'),('driver_document','Documento do motorista'),('status','Status'),('status_updated_at','Data da atualização do status'),('occurrence_status','Status da ocorrência'),('last_event_at','Data do último evento'),('gross_weight','Peso bruto'),('cubed_weight','Peso cubado'),('volume_count','Quantidade de volumes'),('total_value','Valor total'),('freight_value','Valor do frete'),('issued_at','Data de emissão'),('expected_date','Data prevista'),('completed_at','Data de conclusão'),('data_quality_status','Qualidade do dado'),
  ('transport_status','Status do transporte'),('route_name','Rota'),('trip_number','Número da viagem'),('vehicle_type','Tipo de veículo'),('driver_phone','Telefone do motorista'),('collected_at','Data da coleta'),('delivered_at','Data da entrega'),('delivery_performance_status','Performance da entrega'),('sla_status','Status do SLA'),('cost_center','Centro de custo'),
  ('ticket_number','Número do ticket'),('channel','Canal'),('subject','Assunto'),('description','Descrição'),('occurrence_code','Código da ocorrência'),('occurrence_type','Tipo da ocorrência'),('occurrence_reason','Motivo da ocorrência'),('priority','Prioridade'),('attendance_status','Status do atendimento'),('assigned_to','Responsável'),('opened_at','Data de abertura'),('first_response_at','Primeira resposta'),('last_interaction_at','Última interação'),('resolved_at','Data de resolução'),('closed_at','Data de fechamento'),('sla_due_at','Vencimento do SLA'),
  ('billing_reference','Referência de faturamento'),('billing_period','Período de faturamento'),('billing_status','Status do faturamento'),('proof_of_delivery_status','Status do canhoto'),('proof_received_at','Data de recebimento do canhoto'),('ready_to_bill','Pronto para faturar'),('blocked_amount','Valor bloqueado'),('block_status','Status do bloqueio'),('block_reason','Motivo do bloqueio'),('extra_cost_value','Valor de custo extra'),('discount_value','Valor de desconto'),('total_amount','Valor total'),('due_at','Data de vencimento'),('paid_at','Data de pagamento'),
  ('product_code','Código do produto'),('sku','SKU'),('product_name','Nome do produto'),('warehouse_code','Código do armazém'),('warehouse_name','Nome do armazém'),('location_code','Código do endereço'),('batch_number','Lote'),('serial_number','Número de série'),('quantity_available','Quantidade disponível'),('quantity_reserved','Quantidade reservada'),('quantity_blocked','Quantidade bloqueada'),('unit_of_measure','Unidade de medida'),('last_movement_type','Tipo da última movimentação'),('last_movement_at','Data da última movimentação'),('warehouse_status','Status do armazém'),
  ('employee_code','Código do colaborador'),('employee_name','Nome do colaborador'),('employee_document','Documento do colaborador'),('email','E-mail'),('phone','Telefone'),('department_name','Setor'),('position_name','Cargo'),('manager_name','Gestor'),('team_status','Status do colaborador'),('admission_date','Data de admissão'),('termination_date','Data de desligamento'),('shift_name','Turno'),('workload_hours','Carga horária'),('overtime_hours','Horas extras'),('worked_at','Data trabalhada')
)
update public.canonical_fields cf
set name = ls.name,
    updated_at = now()
from label_seed ls
where cf.field_key = ls.field_key
  and cf.name is distinct from ls.name;
