create table if not exists public.canonical_entities (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  module_key text not null, entity_key text not null, name text not null, description text, status text not null default 'active', is_system boolean not null default false, sort_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique(tenant_id, entity_key), constraint canonical_entities_status_check check (status in ('active','inactive','deprecated'))
);
create table if not exists public.canonical_fields (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  canonical_entity_id uuid not null references public.canonical_entities(id) on delete cascade, field_key text not null, name text not null, description text, data_type text not null,
  is_required boolean not null default false, is_system boolean not null default false, sort_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique(canonical_entity_id, field_key), constraint canonical_fields_data_type_check check (data_type in ('text','integer','decimal','boolean','date','datetime','enum','json'))
);
create table if not exists public.field_mappings (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  data_contract_id uuid not null references public.data_contracts(id) on delete cascade, data_contract_field_id uuid not null references public.data_contract_fields(id) on delete cascade,
  canonical_entity_id uuid not null references public.canonical_entities(id) on delete cascade, canonical_field_id uuid not null references public.canonical_fields(id) on delete cascade,
  mapping_type text not null default 'direct', status text not null default 'draft', notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique(data_contract_id, data_contract_field_id), constraint field_mappings_mapping_type_check check (mapping_type in ('direct','default_value','transformed','ignored')), constraint field_mappings_status_check check (status in ('draft','active','inactive','rejected'))
);
create table if not exists public.transformation_rules (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  field_mapping_id uuid not null references public.field_mappings(id) on delete cascade, rule_type text not null, rule_config jsonb not null default '{}'::jsonb, sort_order integer not null default 0, is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  constraint transformation_rules_rule_type_check check (rule_type in ('trim','uppercase','lowercase','replace','parse_date','cast_type','default_value','enum_map','numeric_round'))
);
create table if not exists public.validation_rules (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
  canonical_entity_id uuid not null references public.canonical_entities(id) on delete cascade, canonical_field_id uuid references public.canonical_fields(id) on delete cascade,
  rule_type text not null, rule_config jsonb not null default '{}'::jsonb, severity text not null default 'error', is_active boolean not null default true, message text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  constraint validation_rules_rule_type_check check (rule_type in ('required','min_length','max_length','min_value','max_value','regex','allowed_values','date_format')), constraint validation_rules_severity_check check (severity in ('info','warning','error'))
);

do $$ begin
  alter table public.canonical_entities add constraint canonical_entities_id_tenant_id_key unique (id, tenant_id);
exception when duplicate_object then null; end $$;
do $$ begin alter table public.canonical_fields add constraint canonical_fields_id_tenant_id_key unique (id, tenant_id); exception when duplicate_object then null; end $$;
do $$ begin alter table public.field_mappings add constraint field_mappings_id_tenant_id_key unique (id, tenant_id); exception when duplicate_object then null; end $$;
do $$ begin alter table public.canonical_fields add constraint canonical_fields_entity_tenant_fk foreign key (canonical_entity_id, tenant_id) references public.canonical_entities(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.field_mappings add constraint field_mappings_contract_tenant_fk foreign key (data_contract_id, tenant_id) references public.data_contracts(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.field_mappings add constraint field_mappings_contract_field_tenant_fk foreign key (data_contract_field_id, tenant_id) references public.data_contract_fields(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.field_mappings add constraint field_mappings_entity_tenant_fk foreign key (canonical_entity_id, tenant_id) references public.canonical_entities(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.field_mappings add constraint field_mappings_canonical_field_tenant_fk foreign key (canonical_field_id, tenant_id) references public.canonical_fields(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.transformation_rules add constraint transformation_rules_mapping_tenant_fk foreign key (field_mapping_id, tenant_id) references public.field_mappings(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.validation_rules add constraint validation_rules_entity_tenant_fk foreign key (canonical_entity_id, tenant_id) references public.canonical_entities(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;
do $$ begin alter table public.validation_rules add constraint validation_rules_field_tenant_fk foreign key (canonical_field_id, tenant_id) references public.canonical_fields(id, tenant_id) on delete cascade; exception when duplicate_object then null; end $$;

create index if not exists idx_canonical_entities_tenant_id on public.canonical_entities(tenant_id); create index if not exists idx_canonical_entities_entity_key on public.canonical_entities(entity_key); create index if not exists idx_canonical_entities_module_key on public.canonical_entities(module_key); create index if not exists idx_canonical_entities_status on public.canonical_entities(status);
create index if not exists idx_canonical_fields_tenant_id on public.canonical_fields(tenant_id); create index if not exists idx_canonical_fields_canonical_entity_id on public.canonical_fields(canonical_entity_id); create index if not exists idx_canonical_fields_field_key on public.canonical_fields(field_key);
create index if not exists idx_field_mappings_tenant_id on public.field_mappings(tenant_id); create index if not exists idx_field_mappings_data_contract_id on public.field_mappings(data_contract_id); create index if not exists idx_field_mappings_data_contract_field_id on public.field_mappings(data_contract_field_id); create index if not exists idx_field_mappings_canonical_entity_id on public.field_mappings(canonical_entity_id); create index if not exists idx_field_mappings_canonical_field_id on public.field_mappings(canonical_field_id); create index if not exists idx_field_mappings_status on public.field_mappings(status);
create index if not exists idx_transformation_rules_tenant_id on public.transformation_rules(tenant_id); create index if not exists idx_transformation_rules_field_mapping_id on public.transformation_rules(field_mapping_id);
create index if not exists idx_validation_rules_tenant_id on public.validation_rules(tenant_id); create index if not exists idx_validation_rules_canonical_entity_id on public.validation_rules(canonical_entity_id); create index if not exists idx_validation_rules_canonical_field_id on public.validation_rules(canonical_field_id);

create trigger set_canonical_entities_updated_at before update on public.canonical_entities for each row execute function public.set_updated_at();
create trigger set_canonical_fields_updated_at before update on public.canonical_fields for each row execute function public.set_updated_at();
create trigger set_field_mappings_updated_at before update on public.field_mappings for each row execute function public.set_updated_at();
create trigger set_transformation_rules_updated_at before update on public.transformation_rules for each row execute function public.set_updated_at();
create trigger set_validation_rules_updated_at before update on public.validation_rules for each row execute function public.set_updated_at();

alter table public.canonical_entities enable row level security; alter table public.canonical_fields enable row level security; alter table public.field_mappings enable row level security; alter table public.transformation_rules enable row level security; alter table public.validation_rules enable row level security;

drop policy if exists "members can read canonical entities with permission" on public.canonical_entities; create policy "members can read canonical entities with permission" on public.canonical_entities for select to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_entities.view'));
drop policy if exists "members can create canonical entities with permission" on public.canonical_entities; create policy "members can create canonical entities with permission" on public.canonical_entities for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_entities.create'));
drop policy if exists "members can update canonical entities with permission" on public.canonical_entities; create policy "members can update canonical entities with permission" on public.canonical_entities for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_entities.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_entities.update'));
drop policy if exists "members can read canonical fields with permission" on public.canonical_fields; create policy "members can read canonical fields with permission" on public.canonical_fields for select to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_fields.view'));
drop policy if exists "members can create canonical fields with permission" on public.canonical_fields; create policy "members can create canonical fields with permission" on public.canonical_fields for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_fields.create'));
drop policy if exists "members can update canonical fields with permission" on public.canonical_fields; create policy "members can update canonical fields with permission" on public.canonical_fields for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_fields.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.canonical_fields.update'));
drop policy if exists "members can read field mappings with permission" on public.field_mappings; create policy "members can read field mappings with permission" on public.field_mappings for select to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.field_mappings.view'));
drop policy if exists "members can create field mappings with permission" on public.field_mappings; create policy "members can create field mappings with permission" on public.field_mappings for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.field_mappings.create'));
drop policy if exists "members can update field mappings with permission" on public.field_mappings; create policy "members can update field mappings with permission" on public.field_mappings for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.field_mappings.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.field_mappings.update'));
drop policy if exists "members can read transformation rules with permission" on public.transformation_rules; create policy "members can read transformation rules with permission" on public.transformation_rules for select to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.transformation_rules.view'));
drop policy if exists "members can create transformation rules with permission" on public.transformation_rules; create policy "members can create transformation rules with permission" on public.transformation_rules for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.transformation_rules.create'));
drop policy if exists "members can update transformation rules with permission" on public.transformation_rules; create policy "members can update transformation rules with permission" on public.transformation_rules for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.transformation_rules.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.transformation_rules.update'));
drop policy if exists "members can read validation rules with permission" on public.validation_rules; create policy "members can read validation rules with permission" on public.validation_rules for select to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.validation_rules.view'));
drop policy if exists "members can create validation rules with permission" on public.validation_rules; create policy "members can create validation rules with permission" on public.validation_rules for insert to authenticated with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.validation_rules.create'));
drop policy if exists "members can update validation rules with permission" on public.validation_rules; create policy "members can update validation rules with permission" on public.validation_rules for update to authenticated using (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.validation_rules.update')) with check (public.is_member_of_tenant(tenant_id) and public.user_has_permission(tenant_id,'core.validation_rules.update'));

with permission_seed(key,name,module_key,resource,action,description) as (values
('core.canonical_entities.view','Visualizar entidades canônicas','core','canonical_entities','view','Permite visualizar entidades canônicas.'),('core.canonical_entities.create','Criar entidades canônicas','core','canonical_entities','create','Permite criar entidades canônicas.'),('core.canonical_entities.update','Atualizar entidades canônicas','core','canonical_entities','update','Permite atualizar entidades canônicas.'),
('core.canonical_fields.view','Visualizar campos canônicos','core','canonical_fields','view','Permite visualizar campos canônicos.'),('core.canonical_fields.create','Criar campos canônicos','core','canonical_fields','create','Permite criar campos canônicos.'),('core.canonical_fields.update','Atualizar campos canônicos','core','canonical_fields','update','Permite atualizar campos canônicos.'),
('core.field_mappings.view','Visualizar pareamentos','core','field_mappings','view','Permite visualizar pareamentos de campos.'),('core.field_mappings.create','Criar pareamentos','core','field_mappings','create','Permite criar pareamentos de campos.'),('core.field_mappings.update','Atualizar pareamentos','core','field_mappings','update','Permite atualizar pareamentos de campos.'),
('core.transformation_rules.view','Visualizar regras de transformação','core','transformation_rules','view','Permite visualizar regras de transformação controladas.'),('core.transformation_rules.create','Criar regras de transformação','core','transformation_rules','create','Permite criar regras de transformação controladas.'),('core.transformation_rules.update','Atualizar regras de transformação','core','transformation_rules','update','Permite atualizar regras de transformação controladas.'),
('core.validation_rules.view','Visualizar regras de validação canônica','core','validation_rules','view','Permite visualizar regras de validação canônica.'),('core.validation_rules.create','Criar regras de validação canônica','core','validation_rules','create','Permite criar regras de validação canônica.'),('core.validation_rules.update','Atualizar regras de validação canônica','core','validation_rules','update','Permite atualizar regras de validação canônica.'))
insert into public.permissions (key,name,module_key,resource,action,description) select * from permission_seed on conflict (key) do update set name=excluded.name,module_key=excluded.module_key,resource=excluded.resource,action=excluded.action,description=excluded.description,updated_at=now();
insert into public.role_permissions (tenant_id,role_id,permission_id) select r.tenant_id,r.id,p.id from public.roles r cross join public.permissions p where r.key='owner' and p.key in ('core.canonical_entities.view','core.canonical_entities.create','core.canonical_entities.update','core.canonical_fields.view','core.canonical_fields.create','core.canonical_fields.update','core.field_mappings.view','core.field_mappings.create','core.field_mappings.update','core.transformation_rules.view','core.transformation_rules.create','core.transformation_rules.update','core.validation_rules.view','core.validation_rules.create','core.validation_rules.update') on conflict (tenant_id,role_id,permission_id) do nothing;

with t as (select id from public.tenants where slug='agentlog'), ce as (insert into public.canonical_entities (tenant_id,module_key,entity_key,name,description,status,is_system,sort_order) select id,'transporte','deliveries','Entregas','Entidade canônica inicial para entregas.','active',true,10 from t on conflict (tenant_id,entity_key) do update set name=excluded.name,description=excluded.description,status=excluded.status,is_system=true returning id,tenant_id), entity as (select * from ce union all select c.id,c.tenant_id from public.canonical_entities c join t on t.id=c.tenant_id where c.entity_key='deliveries' limit 1), field_seed(field_key,name,data_type,is_required,sort_order) as (values ('delivery_number','Número da entrega','text',true,10),('customer_document','Documento do cliente','text',true,20),('customer_name','Nome do cliente','text',true,30),('delivery_status','Status da entrega','enum',true,40),('expected_delivery_date','Data prevista','date',false,50),('delivered_at','Data de entrega','datetime',false,60),('total_value','Valor total','decimal',false,70))
insert into public.canonical_fields (tenant_id,canonical_entity_id,field_key,name,data_type,is_required,is_system,sort_order) select e.tenant_id,e.id,f.field_key,f.name,f.data_type,f.is_required,true,f.sort_order from entity e cross join field_seed f on conflict (canonical_entity_id,field_key) do update set name=excluded.name,data_type=excluded.data_type,is_required=excluded.is_required,is_system=true,sort_order=excluded.sort_order;
with t as (select id from public.tenants where slug='agentlog'), ce as (select c.id,c.tenant_id from public.canonical_entities c join t on t.id=c.tenant_id where c.entity_key='deliveries'), dc as (select d.id,d.tenant_id from public.data_contracts d join t on t.id=d.tenant_id where d.entity_key='deliveries' and d.name='Contrato inicial de entregas' order by d.contract_version limit 1)
insert into public.field_mappings (tenant_id,data_contract_id,data_contract_field_id,canonical_entity_id,canonical_field_id,mapping_type,status,notes)
select dc.tenant_id,dc.id,dcf.id,ce.id,cf.id,'direct','draft','Seed controlado Sprint 7: field_key do contrato igual ao field_key canônico.' from dc join ce on ce.tenant_id=dc.tenant_id join public.data_contract_fields dcf on dcf.tenant_id=dc.tenant_id and dcf.data_contract_id=dc.id join public.canonical_fields cf on cf.tenant_id=dc.tenant_id and cf.canonical_entity_id=ce.id and cf.field_key=dcf.field_key where dcf.field_key in ('delivery_number','customer_document','customer_name','delivery_status','expected_delivery_date','delivered_at','total_value') on conflict (data_contract_id,data_contract_field_id) do nothing;
