/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {createBrowserSupabaseClient} from '../../../../../lib/supabase';
import {getAgent,listAgentRuns,listAgentToolsCatalog,testRunAgent,updateAgent,updateAgentTools} from '../../../../../lib/agents-api';

const typeLabels:any={dashboard_analyst:'Agente de Dashboard',report_writer:'Agente de Relatório',general_chat:'Chat Geral',attendance_inbox:'Atendimento / Inbox',financial:'Financeiro',transport:'Transporte',warehouse:'Armazém',teams:'Equipes',saas_admin:'SaaSAdmin',setup_dev:'SetupDev'};
const statusLabels:any={draft:'Rascunho',active:'Ativo',inactive:'Inativo',archived:'Arquivado',pending:'Pendente',processing:'Processando',completed:'Concluído',failed:'Falhou'};
const generalChatToolKeys=new Set(['analytics.map.get','analytics.result.get','analytics.context.analyze','operational.record.find','knowledge.guidance.search']);
const modules=[['core','Core'],['transport','Transporte'],['finance','Financeiro'],['attendance','Atendimento'],['warehouse','Armazém'],['team','Equipes']];
type SaveState='idle'|'saving'|'success'|'error';

export default function Edit(){
  const{id}=useParams<{id:string}>();
  const[tenant,setTenant]=useState(''),[agent,setAgent]=useState<any>(),[tools,setTools]=useState<any[]>([]),[enabled,setEnabled]=useState<string[]>([]),[runs,setRuns]=useState<any[]>([]),[prompt,setPrompt]=useState(''),[output,setOutput]=useState<any>(),[saveStates,setSaveStates]=useState<Record<string,SaveState>>({info:'idle',behavior:'idle',model:'idle',tools:'idle'}),[saveErrors,setSaveErrors]=useState<Record<string,string>>({});
  const load=async(t:string)=>{const a=await getAgent(t,id),catalog=(await listAgentToolsCatalog(t)).data,allowed=new Set(catalog.map((tool:any)=>tool.tool_key));setAgent(a);setTools(catalog);setEnabled((a.tools||[]).filter((x:any)=>x.is_enabled&&allowed.has(x.ai_tools?.tool_key)).map((x:any)=>x.ai_tools.tool_key));setRuns((await listAgentRuns(t,id)).data)};
  useEffect(()=>{createBrowserSupabaseClient().from('users_profile').select('active_tenant_id').maybeSingle().then(async({data}:any)=>{if(data?.active_tenant_id){setTenant(data.active_tenant_id);await load(data.active_tenant_id)}})},[id]);
  const saveSection=async(section:string,action:()=>Promise<unknown>)=>{setSaveStates(s=>({...s,[section]:'saving'}));setSaveErrors(e=>({...e,[section]:''}));try{await action();await load(tenant);setSaveStates(s=>({...s,[section]:'success'}));setTimeout(()=>setSaveStates(s=>s[section]==='success'?{...s,[section]:'idle'}:s),2000)}catch(error){setSaveStates(s=>({...s,[section]:'error'}));setSaveErrors(e=>({...e,[section]:error instanceof Error?error.message:'Não foi possível salvar.'}))}};
  const saveInfo=()=>saveSection('info',()=>updateAgent(tenant,id,{name:agent.name,description:agent.description,module_key:agent.module_key,status:agent.status}));
  const saveBehavior=()=>saveSection('behavior',()=>updateAgent(tenant,id,{behavior_profile:agent.behavior_profile,system_instructions:agent.system_instructions,response_style:agent.response_style||{},language:agent.language,source_citation_policy:agent.source_citation_policy,fallback_policy:agent.fallback_policy,clarification_policy:agent.clarification_policy,guardrails:agent.guardrails||{}}));
  const saveModel=()=>saveSection('model',()=>updateAgent(tenant,id,{model_provider:agent.model_provider||'openai',model_name:agent.model_name,temperature:agent.temperature,max_output_tokens:agent.max_output_tokens}));
  const visibleTools=agent?.agent_type==='general_chat'?tools.filter(tool=>generalChatToolKeys.has(tool.tool_key)):tools;
  const saveTools=()=>saveSection('tools',()=>updateAgentTools(tenant,id,{tool_keys:[...new Set(enabled.filter(key=>visibleTools.some(tool=>tool.tool_key===key)))]}));
  const saveButton=(section:string,onClick:()=>void,label='Salvar')=><><button className="btn-primary" disabled={saveStates[section]==='saving'} onClick={onClick}>{saveStates[section]==='saving'?'Salvando...':saveStates[section]==='success'?'Salvo':label}</button>{saveStates[section]==='error'&&<p className="text-sm text-red-600">{saveErrors[section]}</p>}</>;
  if(!agent)return <p>Carregando...</p>;
  const field=(key:string,label:string,area=false)=><label className="block">{label}{area?<textarea className="w-full rounded border p-2" value={agent[key]||''} onChange={e=>setAgent({...agent,[key]:e.target.value})}/>:<input className="w-full rounded border p-2" value={agent[key]||''} onChange={e=>setAgent({...agent,[key]:e.target.value})}/>}</label>;
  const styleField=(key:string,label:string,area=false)=><label className="block">{label}{area?<textarea className="w-full rounded border p-2" value={agent.response_style?.[key]||''} onChange={e=>setAgent({...agent,response_style:{...(agent.response_style||{}),[key]:e.target.value}})}/>:<input className="w-full rounded border p-2" value={agent.response_style?.[key]||''} onChange={e=>setAgent({...agent,response_style:{...(agent.response_style||{}),[key]:e.target.value}})}/>}</label>;
  return <section className="mx-auto max-w-4xl space-y-5"><h1 className="text-2xl font-bold">Configurar {typeLabels[agent.agent_type]}</h1>
    <div className="rounded-xl border bg-white p-5 space-y-2"><h2 className="font-bold">Informações</h2>{field('name','Nome')}{field('description','Descrição',true)}<label>Tipo de agente<input readOnly value={typeLabels[agent.agent_type]||''}/></label><label>Módulo<select value={agent.module_key||'core'} onChange={e=>setAgent({...agent,module_key:e.target.value})}>{modules.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label><label>Status<select value={agent.status} onChange={e=>setAgent({...agent,status:e.target.value})}>{['draft','active','inactive','archived'].map(x=><option value={x} key={x}>{statusLabels[x]}</option>)}</select></label>{saveButton('info',saveInfo)}</div>
    <div className="rounded-xl border bg-white p-5 space-y-2"><h2 className="font-bold">Comportamento e linguagem</h2>{field('behavior_profile','Perfil de comportamento')}{field('system_instructions','Instruções principais',true)}{styleField('tone','Tom de voz')}{styleField('detail_level','Nível de detalhe')}{field('language','Idioma padrão')}{styleField('greeting_policy','Como tratar saudação',true)}{styleField('greeting_response','Resposta curta para saudação')}{field('fallback_policy','Como tratar falta de dados',true)}{field('source_citation_policy','Como tratar fontes',true)}{field('clarification_policy','Quando pedir esclarecimento',true)}{styleField('internal_terms','Termos internos que não devem aparecer',true)}<p className="text-sm">Guardrails fixos: sem banco cru, SQL livre, staging, dados de outro cliente ou exposição de secrets. Eles não podem ser removidos.</p>{saveButton('behavior',saveBehavior)}</div>
    <div className="rounded-xl border bg-white p-5 space-y-2"><h2 className="font-bold">Modelo</h2><label>Provider<select value={agent.model_provider||'openai'} onChange={e=>setAgent({...agent,model_provider:e.target.value})}><option value="openai">OpenAI</option></select></label><label>Modelo<select value={agent.model_name||''} onChange={e=>setAgent({...agent,model_name:e.target.value||null})}><option value="">Padrão do sistema</option><option>gpt-4.1-mini</option><option>gpt-4.1</option></select></label><label>Temperatura<input type="number" value={agent.temperature} onChange={e=>setAgent({...agent,temperature:+e.target.value})}/></label><label>Máximo de tokens<input type="number" value={agent.max_output_tokens} onChange={e=>setAgent({...agent,max_output_tokens:+e.target.value})}/></label>{saveButton('model',saveModel)}</div>
    <div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Ferramentas permitidas</h2>{visibleTools.map(x=><label className="block" key={x.id}><input type="checkbox" checked={enabled.includes(x.tool_key)} onChange={e=>setEnabled(v=>e.target.checked?[...new Set([...v,x.tool_key])]:v.filter(k=>k!==x.tool_key))}/> {x.name} — {x.description}</label>)}<div className="mt-3">{saveButton('tools',saveTools,'Salvar ferramentas')}</div></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Teste manual controlado</h2><textarea className="w-full border" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="btn-primary" onClick={async()=>{const r=await testRunAgent(tenant,id,{prompt});setOutput(r.output_json);await load(tenant)}}>Executar teste</button>{output&&<pre>{JSON.stringify(output,null,2)}</pre>}<p>O resultado indica simulação quando o dry-run está ativo.</p></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Histórico e governança</h2>{runs.map(x=><p key={x.id}>{statusLabels[x.status]||x.status} · {x.run_type==='manual_test'?'Teste manual':'Análise de dashboard'} · {x.total_tokens||0} tokens{x.error_message?` · ${x.error_message}`:''}</p>)}</div>
  </section>;
}
