'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Card, EmptyState, SectionHeader, StatusBadge } from '../../../../components/ui';
import { getCurrentUserPermissions, hasPermission, type UserPermission } from '../../../../lib/rbac';
import { getSessionContext } from '../../../../lib/setup-api';
import { listStagingBatches, type StagingBatch } from '../../../../lib/staging-api';
const statuses = ['draft','received','validating','validated','partially_valid','rejected','cancelled'];
export default function StagingPage(){const [batches,setBatches]=useState<StagingBatch[]>([]);const [permissions,setPermissions]=useState<UserPermission[]>([]);const [tenantId,setTenantId]=useState<string|null>(null);const [message,setMessage]=useState('Carregando staging...');useEffect(()=>{getSessionContext().then(async(ctx)=>{if(!ctx.user){setMessage('Faça login para visualizar Staging.');return;} if(!ctx.tenantId){setMessage('Selecione um tenant ativo.');return;} setTenantId(ctx.tenantId);const perms=await getCurrentUserPermissions(ctx.tenantId);setPermissions(perms);if(!hasPermission(perms,'core.staging_batches.view')){setMessage('Acesso negado: permissão core.staging_batches.view é necessária.');return;} const rows=await listStagingBatches(ctx.tenantId);setBatches(rows);setMessage('');}).catch((e:Error)=>setMessage(e.message));},[]);const counts=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,batches.filter(b=>b.status===s).length])),[batches]);const valid=batches.reduce((s,b)=>s+b.valid_records,0);const invalid=batches.reduce((s,b)=>s+b.invalid_records,0);return <div className="mx-auto max-w-6xl space-y-8"><SectionHeader eyebrow="Setup" title="Staging" description="Camada mínima para receber registros brutos e validar deterministicamente contra contratos de dados." />{message?<EmptyState title="Status do staging" description={message}/>:null}{hasPermission(permissions,'core.staging_batches.view')?<><Card><p className="text-sm text-slate-500">Tenant ativo</p><p className="mt-1 font-semibold">{tenantId}</p><p className="mt-4 text-3xl font-bold">{batches.length}</p><p className="text-sm text-slate-600">lotes de staging</p><p className="mt-2 text-sm text-slate-600">Registros válidos: {valid} · inválidos: {invalid}</p><Link className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" href="/app/setup/staging/batches">Ver lotes</Link></Card><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">{statuses.map(s=><Card key={s}><StatusBadge>{s}</StatusBadge><p className="mt-4 text-3xl font-bold">{counts[s]??0}</p></Card>)}</div></>:null}</div>}
